from __future__ import annotations

from itertools import product
from math import gcd
from typing import Iterable, Iterator, Mapping, Sequence, Tuple

from .artin_longitudes import FreeWord, evaluate_free_word, invert_free_word, reduce_free_word
from .finite_group import FiniteGroup, GroupElement


def lcm(a: int, b: int) -> int:
    if a == 0 or b == 0:
        return 0
    return abs(a * b) // gcd(a, b)


def lcm_upto(n: int) -> int:
    if n < 1:
        raise ValueError("n must be positive")
    out = 1
    for value in range(1, n + 1):
        out = lcm(out, value)
    return out


def free_word_power(generator: int, exponent: int) -> FreeWord:
    if exponent == 0:
        return tuple()
    letter = (generator, 1 if exponent > 0 else -1)
    return tuple(letter for _ in range(abs(exponent)))


def multiply_free_words(*words: FreeWord) -> FreeWord:
    letters = []
    for word in words:
        letters.extend(word)
    return reduce_free_word(letters)


def commutator(left: FreeWord, right: FreeWord) -> FreeWord:
    return multiply_free_words(left, right, invert_free_word(left), invert_free_word(right))


def exponent_law_word(bound: int, generator: int = 0) -> FreeWord:
    """Return x_generator^lcm(1,...,bound)."""

    return free_word_power(generator, lcm_upto(bound))


def two_strand_pure_power(power: int) -> Tuple[int, ...]:
    """Return (sigma_1^2)^power in B_2."""

    if power < 0:
        return tuple(-1 for _ in range(-2 * power))
    return tuple(1 for _ in range(2 * power))


def two_strand_exponent_law_braid(bound: int) -> Tuple[int, ...]:
    """Return (sigma_1^2)^lcm(1,...,bound)."""

    return two_strand_pure_power(lcm_upto(bound))


def two_strand_longitude_period(group: FiniteGroup) -> int:
    """Return the exact positive period of finite-G longitude data on B_2.

    The braid group ``B_2`` is generated by ``sigma_1``.  For a finite group
    ``G``, the finite-G Artin-longitude signature of ``sigma_1^k`` is the
    identity for all assignments exactly when ``k`` is divisible by
    ``2*exp(G)``.
    """

    return 2 * group_exponent(group)


def two_strand_symmetric_longitude_period(size: int) -> int:
    """Return the exact B_2 period for the detector ``Sym(size)``."""

    return 2 * lcm_upto(size)


def element_order(group: FiniteGroup, element: GroupElement) -> int:
    value = group.identity
    for order in range(1, len(group.elements) + 1):
        value = group.mul(value, element)
        if value == group.identity:
            return order
    raise ValueError("group element order exceeded group size")


def group_exponent(group: FiniteGroup) -> int:
    out = 1
    for element in group.elements:
        out = lcm(out, element_order(group, element))
    return out


def is_law_on_group(group: FiniteGroup, word: FreeWord, arity: int | None = None) -> bool:
    if arity is None:
        arity = 1 + max((generator for generator, _exp in word), default=-1)
    if arity < 0:
        raise ValueError("arity must be nonnegative")
    for assignment in product(group.elements, repeat=arity):
        if evaluate_free_word(group, assignment, word) != group.identity:
            return False
    return True


def law_profile(groups: Mapping[str, FiniteGroup], word: FreeWord, arity: int | None = None):
    laws = []
    failures = []
    for name, group in groups.items():
        if is_law_on_group(group, word, arity=arity):
            laws.append(name)
        else:
            failures.append(name)
    return tuple(laws), tuple(failures)


def exponent_law_profile(groups: Mapping[str, FiniteGroup], bound: int):
    word = exponent_law_word(bound)
    laws, failures = law_profile(groups, word, arity=1)
    return {
        "bound": bound,
        "exponent": lcm_upto(bound),
        "laws": laws,
        "failures": failures,
    }


def reduced_free_words(arity: int, max_length: int) -> Iterator[FreeWord]:
    """Yield nonempty freely reduced words up to the requested length."""

    if arity < 1:
        raise ValueError("arity must be positive")
    if max_length < 1:
        return
    letters = tuple((generator, exponent) for generator in range(arity) for exponent in (1, -1))

    def extend(prefix: Tuple[Tuple[int, int], ...], target_length: int):
        if len(prefix) == target_length:
            yield prefix
            return
        for letter in letters:
            if prefix and prefix[-1][0] == letter[0] and prefix[-1][1] == -letter[1]:
                continue
            yield from extend(prefix + (letter,), target_length)

    for length in range(1, max_length + 1):
        yield from extend(tuple(), length)


def short_law_separating_groups(
    law_groups: Sequence[FiniteGroup],
    target_group: FiniteGroup,
    *,
    arity: int,
    max_length: int,
) -> FreeWord | None:
    """Return a short word law on all `law_groups` but not on `target_group`.

    This is a finite diagnostic for the normalized-law B route.  A returned
    word proves a separation for the supplied finite groups only; it is not a
    substitute for an all-bound symbolic sequence.
    """

    for word in reduced_free_words(arity, max_length):
        if all(is_law_on_group(group, word, arity=arity) for group in law_groups):
            if not is_law_on_group(target_group, word, arity=arity):
                return word
    return None


def short_law_escaping_variety(
    generating_group: FiniteGroup,
    target_group: FiniteGroup,
    *,
    arity: int,
    max_length: int,
) -> FreeWord | None:
    """Return a short law of `generating_group` that fails on `target_group`.

    A finite target group satisfies every law of a finite group `G` exactly
    when it belongs to the group variety generated by `G`.  This helper is a
    bounded diagnostic for that condition: a returned word certifies escape
    from `var(G)`, while `None` is only bounded evidence.
    """

    return short_law_separating_groups(
        (generating_group,),
        target_group,
        arity=arity,
        max_length=max_length,
    )
