from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from itertools import product
from typing import Dict, Literal, Mapping, Sequence, Tuple

from .artin_longitudes import (
    artin_longitudes,
    evaluate_free_word,
    has_identity_longitude_signature,
    longitude_value_generators,
    longitude_value_subgroup_elements,
)
from .context_retraction import (
    DirectProductWitness,
    ProductPermutationWitness,
    direct_product_witness,
    product_permutation_witness,
)
from .finite_group import (
    FiniteGroup,
    Permutation,
    compose_permutations,
    permutation_group_from_generators,
    subgroup_generated_elements,
)
from .finite_braided_set import FiniteBraidedSet
from .local_interval import Color, FibrePoint, LocalInterval
from .detector_candidates import (
    _apply_group_detector_generator_int,
    _compose_permutation,
    _group_detector_initial_int_state,
    _group_int_tables,
    _solution_generator_permutation,
)
from .product_permutation import ProductLabel
from .product_permutation import (
    direct_product_action,
    direct_product_label_word_action,
    product_holonomy_closed_label_permutations,
    product_holonomy_groups,
    product_permutation_action,
    swapped_product_label_word_action,
)

TaggedPoint = Tuple[Color, FibrePoint]
ProductBranch = Literal["swapped", "direct"]


@dataclass(frozen=True)
class ProductLabelGroup:
    """A finite permutation group generated by totalized product labels."""

    branch: ProductBranch
    universe: Tuple[TaggedPoint, ...]
    generators: Tuple[Tuple[ProductLabel, Permutation], ...]
    group: FiniteGroup


@dataclass(frozen=True)
class ProductClosedLabelLongitudeWitness:
    """A finite-group longitude evaluation hitting one closed product label."""

    coordinate: int
    closed_label: Permutation
    longitude_index: int
    assignment: Tuple[Permutation, ...]


@dataclass(frozen=True)
class ProductClosedLabelLongitudeSubgroupRow:
    """Membership of one closed product label in the longitude-value subgroup."""

    coordinate: int
    closed_label: Permutation
    in_longitude_subgroup: bool


@dataclass(frozen=True)
class ProductClosedLabelLongitudeSubgroupAudit:
    """Audit the verbal subgroup generated by all finite-label longitude values."""

    generator_count: int
    subgroup_size: int
    rows: Tuple[ProductClosedLabelLongitudeSubgroupRow, ...]

    @property
    def all_closed_labels_detected(self) -> bool:
        return all(row.in_longitude_subgroup for row in self.rows)


@dataclass(frozen=True)
class ProductClosedLabelLongitudeRouteRow:
    """Compare the available longitude routes for one closed product label."""

    coordinate: int
    closed_label: Permutation
    has_single_longitude_witness: bool
    in_longitude_subgroup: bool
    witness_longitude_index: int | None = None
    witness_assignment: Tuple[Permutation, ...] | None = None


@dataclass(frozen=True)
class ProductClosedLabelLongitudeRouteAudit:
    """One-word audit of common, single-value, and subgroup product routes."""

    common_assignment_count: int
    longitude_generator_count: int
    longitude_subgroup_size: int
    rows: Tuple[ProductClosedLabelLongitudeRouteRow, ...]

    @property
    def has_common_assignment(self) -> bool:
        return self.common_assignment_count > 0

    @property
    def all_single_witnessed(self) -> bool:
        return all(row.has_single_longitude_witness for row in self.rows)

    @property
    def all_in_longitude_subgroup(self) -> bool:
        return all(row.in_longitude_subgroup for row in self.rows)

    @property
    def subgroup_only_rows(self) -> Tuple[ProductClosedLabelLongitudeRouteRow, ...]:
        return tuple(
            row
            for row in self.rows
            if row.in_longitude_subgroup and not row.has_single_longitude_witness
        )

    @property
    def failed_rows(self) -> Tuple[ProductClosedLabelLongitudeRouteRow, ...]:
        return tuple(row for row in self.rows if not row.in_longitude_subgroup)


@dataclass(frozen=True)
class ProductClosedLabelLongitudeSubgroupFailure:
    """A closed product label outside the longitude-value subgroup."""

    braid_word: Tuple[int, ...]
    audit: ProductClosedLabelLongitudeSubgroupAudit
    bad_rows: Tuple[ProductClosedLabelLongitudeSubgroupRow, ...]


@dataclass(frozen=True)
class ProductHolonomyLongitudeSubgroupRow:
    """Membership of one normalized product holonomy label."""

    coordinate: int
    model_points: Tuple[FibrePoint, ...]
    closed_holonomy: Permutation
    in_longitude_subgroup: bool


@dataclass(frozen=True)
class ProductHolonomyLongitudeSubgroupAudit:
    """Audit normalized product holonomies against longitude-value subgroups."""

    generator_counts: Mapping[Tuple[FibrePoint, ...], int]
    subgroup_sizes: Mapping[Tuple[FibrePoint, ...], int]
    rows: Tuple[ProductHolonomyLongitudeSubgroupRow, ...]

    @property
    def all_closed_holonomies_detected(self) -> bool:
        return all(row.in_longitude_subgroup for row in self.rows)


@dataclass(frozen=True)
class ProductHolonomyLongitudeSubgroupFailure:
    """A normalized product holonomy outside the longitude-value subgroup."""

    braid_word: Tuple[int, ...]
    audit: ProductHolonomyLongitudeSubgroupAudit
    bad_rows: Tuple[ProductHolonomyLongitudeSubgroupRow, ...]


@dataclass(frozen=True)
class ProductHolonomyExactFailure:
    """A fixed-degree normalized holonomy invisible to the detector states."""

    braid_word: Tuple[int, ...]
    coordinate: int
    model_points: Tuple[FibrePoint, ...]
    closed_holonomy: Permutation


@dataclass(frozen=True)
class ProductHolonomyExactAudit:
    """Exact fixed-degree image audit for normalized product holonomy."""

    n: int
    visited_state_count: int
    base_state_count: int
    product_state_count: int
    detector_state_count: int
    closed_state_count: int
    identity_detector_closed_state_count: int
    holonomy_group_orders: Tuple[int, ...]
    extra_group_orders: Tuple[int, ...]
    truncated: bool
    failure: ProductHolonomyExactFailure | None

    @property
    def proves_fixed_tuple_kernel_implication(self) -> bool:
        return not self.truncated and self.failure is None


@dataclass(frozen=True)
class ProductClosedLabelExactFailure:
    """A fixed-degree closed product label invisible to the detector states."""

    braid_word: Tuple[int, ...]
    coordinate: int
    closed_label: Tuple[Tuple[FibrePoint, FibrePoint], ...]


@dataclass(frozen=True)
class ProductClosedLabelExactAudit:
    """Exact fixed-degree image audit for product closed-label detection."""

    n: int
    visited_state_count: int
    base_state_count: int
    product_state_count: int
    detector_state_count: int
    closed_state_count: int
    identity_detector_closed_state_count: int
    truncated: bool
    failure: ProductClosedLabelExactFailure | None

    @property
    def proves_fixed_tuple_kernel_implication(self) -> bool:
        return not self.truncated and self.failure is None


def product_label_universe(interval: LocalInterval) -> Tuple[TaggedPoint, ...]:
    """Return the disjoint tagged union of all local fibres."""

    return tuple(
        (color, point)
        for color in interval.colors
        for point in interval.fibres[color]
    )


def _invert_map(mapping: Mapping[FibrePoint, FibrePoint]) -> Dict[FibrePoint, FibrePoint]:
    return {value: key for key, value in mapping.items()}


def _swapped_label_data(
    interval: LocalInterval,
    label: ProductLabel,
    witness: ProductPermutationWitness,
) -> Tuple[Color, Color, Dict[FibrePoint, FibrePoint]]:
    kind, a, b, sign = label
    c, d = interval.base_R[(a, b)]
    if kind == "L":
        source, target = (b, c) if sign == 1 else (c, b)
        mapping = dict(witness.left_maps[(a, b)])
    elif kind == "R":
        source, target = (a, d) if sign == 1 else (d, a)
        mapping = dict(witness.right_maps[(a, b)])
    else:
        raise ValueError(f"unknown product label kind {kind!r}")
    if sign == -1:
        mapping = _invert_map(mapping)
    elif sign != 1:
        raise ValueError("product label sign must be +/-1")
    return source, target, mapping


def _direct_label_data(
    interval: LocalInterval,
    label: ProductLabel,
    witness: DirectProductWitness,
) -> Tuple[Color, Color, Dict[FibrePoint, FibrePoint]]:
    kind, a, b, sign = label
    c, d = interval.base_R[(a, b)]
    if kind == "L":
        source, target = (a, c) if sign == 1 else (c, a)
        mapping = dict(witness.left_maps[(a, b)])
    elif kind == "R":
        source, target = (b, d) if sign == 1 else (d, b)
        mapping = dict(witness.right_maps[(a, b)])
    else:
        raise ValueError(f"unknown product label kind {kind!r}")
    if sign == -1:
        mapping = _invert_map(mapping)
    elif sign != 1:
        raise ValueError("product label sign must be +/-1")
    return source, target, mapping


def _totalize_partial_label(
    interval: LocalInterval,
    universe: Sequence[TaggedPoint],
    source: Color,
    target: Color,
    mapping: Mapping[FibrePoint, FibrePoint],
) -> Permutation:
    """Extend a fibre bijection to a permutation of the tagged fibre union.

    If source and target are distinct tagged fibres, the extension swaps the
    two fibres by the given bijection and its inverse.  If source equals
    target, it is simply the fibre permutation on that block.  All unrelated
    fibres are fixed.
    """

    expected_source = set(interval.fibres[source])
    expected_target = set(interval.fibres[target])
    if set(mapping.keys()) != expected_source:
        raise ValueError("label source mismatch")
    if set(mapping.values()) != expected_target:
        raise ValueError("label target mismatch")

    index = {tagged: i for i, tagged in enumerate(universe)}
    image = list(range(len(universe)))
    if source == target:
        for point, mapped in mapping.items():
            image[index[(source, point)]] = index[(target, mapped)]
        return tuple(image)

    inverse = _invert_map(mapping)
    for point, mapped in mapping.items():
        image[index[(source, point)]] = index[(target, mapped)]
    for point, mapped in inverse.items():
        image[index[(target, point)]] = index[(source, mapped)]
    return tuple(image)


def swapped_product_label_permutation(
    interval: LocalInterval,
    label: ProductLabel,
    witness: ProductPermutationWitness | None = None,
) -> Permutation:
    """Return the total permutation attached to one swapped product label."""

    witness = product_permutation_witness(interval) if witness is None else witness
    if witness is None:
        raise ValueError("interval is not in product-permutation form")
    source, target, mapping = _swapped_label_data(interval, label, witness)
    return _totalize_partial_label(
        interval,
        product_label_universe(interval),
        source,
        target,
        mapping,
    )


def direct_product_label_permutation(
    interval: LocalInterval,
    label: ProductLabel,
    witness: DirectProductWitness | None = None,
) -> Permutation:
    """Return the total permutation attached to one direct product label."""

    witness = direct_product_witness(interval) if witness is None else witness
    if witness is None:
        raise ValueError("interval is not in direct product-permutation form")
    source, target, mapping = _direct_label_data(interval, label, witness)
    return _totalize_partial_label(
        interval,
        product_label_universe(interval),
        source,
        target,
        mapping,
    )


def product_label_word_permutation(
    interval: LocalInterval,
    branch: ProductBranch,
    label_word: Sequence[ProductLabel],
    witness: ProductPermutationWitness | DirectProductWitness | None = None,
) -> Permutation:
    """Evaluate a product-label word inside the finite total label group."""

    universe = product_label_universe(interval)
    out = tuple(range(len(universe)))
    for label in label_word:
        if branch == "swapped":
            if witness is not None and not isinstance(witness, ProductPermutationWitness):
                raise ValueError("swapped branch needs a ProductPermutationWitness")
            step = swapped_product_label_permutation(
                interval,
                label,
                witness,
            )
        elif branch == "direct":
            if witness is not None and not isinstance(witness, DirectProductWitness):
                raise ValueError("direct branch needs a DirectProductWitness")
            step = direct_product_label_permutation(
                interval,
                label,
                witness,
            )
        else:
            raise ValueError(f"unknown product branch {branch!r}")
        out = compose_permutations(step, out)
    return out


def product_label_permutation_image(
    interval: LocalInterval,
    permutation: Permutation,
    source_color: Color,
    source_point: FibrePoint,
) -> TaggedPoint:
    """Apply a total label permutation to one tagged source point."""

    universe = product_label_universe(interval)
    index = {tagged: i for i, tagged in enumerate(universe)}
    return universe[permutation[index[(source_color, source_point)]]]


def product_closed_label_permutations(
    interval: LocalInterval,
    branch: ProductBranch,
    color_tuple: Sequence[Color],
    braid_word: Sequence[int],
) -> Tuple[Permutation, ...]:
    """Return closed totalized label permutations for a base-fixed braid.

    This is the executable form of the closed labels ``h_{z,j}(beta)`` in
    ``proofs/product_closed_label_cocycle.md``.  It requires the final colour
    tuple to equal the input colour tuple.  In the swapped branch it also
    requires the dependency vector to be the identity, which is the Artin
    permutation-trivial condition needed in the sharp detector kernel.
    """

    if branch == "swapped":
        action = swapped_product_label_word_action(interval, color_tuple, braid_word)
    elif branch == "direct":
        action = direct_product_label_word_action(interval, color_tuple, braid_word)
    else:
        raise ValueError(f"unknown product branch {branch!r}")

    identity_dependency = tuple(range(len(color_tuple)))
    if action.final_colors != tuple(color_tuple):
        raise ValueError("product label path is not base-colour closed")
    if action.dependency != identity_dependency:
        raise ValueError("product label path is not strand-permutation closed")
    return tuple(
        product_label_word_permutation(interval, branch, label_word)
        for label_word in action.label_words
    )


def first_nonidentity_product_closed_label(
    interval: LocalInterval,
    branch: ProductBranch,
    color_tuple: Sequence[Color],
    braid_word: Sequence[int],
) -> Tuple[int, Permutation] | None:
    """Return the first nonidentity closed product label, if any."""

    identity = tuple(range(len(product_label_universe(interval))))
    for index, permutation in enumerate(
        product_closed_label_permutations(interval, branch, color_tuple, braid_word)
    ):
        if permutation != identity:
            return index, permutation
    return None


def product_closed_label_blind_movers(
    interval: LocalInterval,
    branch: ProductBranch,
    groups: Sequence[FiniteGroup],
    color_tuple: Sequence[Color],
    braid_words: Sequence[Sequence[int]],
):
    """Return bounded closed-label movers invisible to all listed groups.

    This is a search helper only.  It supports the product-specific B route by
    finding words whose Artin longitude data is trivial for the listed finite
    groups while some closed product label remains nonidentity.
    """

    out = {}
    n = len(color_tuple)
    for braid_word in braid_words:
        word = tuple(braid_word)
        if not all(has_identity_longitude_signature(group, n, word) for group in groups):
            continue
        try:
            moved = first_nonidentity_product_closed_label(
                interval,
                branch,
                color_tuple,
                word,
            )
        except ValueError:
            continue
        if moved is not None:
            out[word] = moved
    return out


def _product_label_group_for_branch(
    interval: LocalInterval,
    branch: ProductBranch,
) -> ProductLabelGroup:
    if branch == "swapped":
        return swapped_product_label_group(interval)
    if branch == "direct":
        return direct_product_label_group(interval)
    raise ValueError(f"unknown product branch {branch!r}")


def _bounded_group_assignments(
    group: FiniteGroup,
    n: int,
    max_assignments: int,
) -> Tuple[Tuple[Permutation, ...], ...]:
    count = len(group.elements) ** n
    if count > max_assignments:
        raise ValueError(
            f"assignment search would enumerate {count} rows; "
            f"raise max_assignments above {max_assignments} explicitly"
        )
    return tuple(product(group.elements, repeat=n))


def product_closed_label_common_longitude_assignments(
    interval: LocalInterval,
    branch: ProductBranch,
    color_tuple: Sequence[Color],
    braid_word: Sequence[int],
    max_assignments: int = 100_000,
) -> Tuple[Tuple[Permutation, ...], ...]:
    """Return assignments making every closed label equal its longitude value.

    This checks the deliberately strong formula
    ``h_j(beta)=phi(L_j(beta))`` for one common homomorphism
    ``phi:F_n -> H_prod``.  It is a diagnostic only: the sharp obstruction
    theorem allows different homomorphisms for different coordinates and even
    for different factors in a proof of identity.
    """

    label_group = _product_label_group_for_branch(interval, branch)
    group = label_group.group
    n = len(color_tuple)
    data = artin_longitudes(n, braid_word)
    closed = product_closed_label_permutations(
        interval,
        branch,
        color_tuple,
        braid_word,
    )
    out = []
    for assignment in _bounded_group_assignments(group, n, max_assignments):
        values = tuple(
            evaluate_free_word(group, assignment, longitude)
            for longitude in data.longitudes
        )
        if values == closed:
            out.append(assignment)
    return tuple(out)


def product_closed_label_longitude_witnesses(
    interval: LocalInterval,
    branch: ProductBranch,
    color_tuple: Sequence[Color],
    braid_word: Sequence[int],
    max_assignments: int = 100_000,
) -> Tuple[ProductClosedLabelLongitudeWitness, ...]:
    """Find longitude evaluations hitting every nonidentity closed label.

    The returned witnesses are bounded diagnostics for the product A-route.
    If every nonidentity closed label is a value of some Artin longitude under
    some assignment into ``H_prod``, then identity ``H_prod``-longitude data
    would kill those labels.  A missing witness is not automatically a
    theorem-level counterexample; it is a concrete target for either a larger
    detector group or a normalized-law obstruction.
    """

    label_group = _product_label_group_for_branch(interval, branch)
    group = label_group.group
    n = len(color_tuple)
    data = artin_longitudes(n, braid_word)
    closed = product_closed_label_permutations(
        interval,
        branch,
        color_tuple,
        braid_word,
    )
    assignments = _bounded_group_assignments(group, n, max_assignments)
    witnesses = []
    for coordinate, closed_label in enumerate(closed):
        if closed_label == group.identity:
            continue
        found = None
        for longitude_index, longitude in enumerate(data.longitudes):
            for assignment in assignments:
                value = evaluate_free_word(group, assignment, longitude)
                if value == closed_label:
                    found = ProductClosedLabelLongitudeWitness(
                        coordinate=coordinate,
                        closed_label=closed_label,
                        longitude_index=longitude_index,
                        assignment=assignment,
                    )
                    break
            if found is not None:
                break
        if found is None:
            raise ValueError(
                f"no H_prod-longitude witness found for closed label {coordinate}"
            )
        witnesses.append(found)
    return tuple(witnesses)


def product_closed_label_longitude_subgroup_audit(
    interval: LocalInterval,
    branch: ProductBranch,
    color_tuple: Sequence[Color],
    braid_word: Sequence[int],
    max_assignments: int = 100_000,
) -> ProductClosedLabelLongitudeSubgroupAudit:
    """Check closed labels against the subgroup generated by longitude values.

    For a fixed braid word and fixed finite product-label group ``H_prod``,
    collect every value of every recursive Artin longitude under every
    assignment ``F_n -> H_prod``.  If a closed product label lies in the
    subgroup generated by those values, then identity ``H_prod``-longitude
    data kills that label.  This is a stronger diagnostic than asking for one
    longitude evaluation to hit the label directly, and it matches the
    theorem-level "finite product of longitude evaluations" criterion.
    """

    label_group = _product_label_group_for_branch(interval, branch)
    group = label_group.group
    n = len(color_tuple)
    closed = product_closed_label_permutations(
        interval,
        branch,
        color_tuple,
        braid_word,
    )
    generator_values = longitude_value_generators(
        group,
        n,
        braid_word,
        max_assignments=max_assignments,
    )
    subgroup = frozenset(
        longitude_value_subgroup_elements(
            group,
            n,
            braid_word,
            max_assignments=max_assignments,
        )
    )
    rows = tuple(
        ProductClosedLabelLongitudeSubgroupRow(
            coordinate=coordinate,
            closed_label=closed_label,
            in_longitude_subgroup=closed_label in subgroup,
        )
        for coordinate, closed_label in enumerate(closed)
        if closed_label != group.identity
    )
    return ProductClosedLabelLongitudeSubgroupAudit(
        generator_count=len(generator_values),
        subgroup_size=len(subgroup),
        rows=rows,
    )


def product_closed_label_longitude_route_audit(
    interval: LocalInterval,
    branch: ProductBranch,
    color_tuple: Sequence[Color],
    braid_word: Sequence[int],
    max_assignments: int = 100_000,
) -> ProductClosedLabelLongitudeRouteAudit:
    """Compare product closed-label detection routes for one braid word.

    This is still a fixed-word finite diagnostic.  It is useful because it
    records the strict implications among the candidate product proofs:
    one common assignment, per-label single longitude values, and membership
    in the subgroup generated by all longitude values in the fixed label group.
    """

    label_group = _product_label_group_for_branch(interval, branch)
    group = label_group.group
    n = len(color_tuple)
    data = artin_longitudes(n, braid_word)
    closed = product_closed_label_permutations(
        interval,
        branch,
        color_tuple,
        braid_word,
    )
    assignments = _bounded_group_assignments(group, n, max_assignments)

    common_assignment_count = 0
    generator_values = set()
    single_witnesses: Dict[
        int,
        Tuple[int, Tuple[Permutation, ...]],
    ] = {}
    for assignment in assignments:
        values = tuple(
            evaluate_free_word(group, assignment, longitude)
            for longitude in data.longitudes
        )
        generator_values.update(values)
        if values == closed:
            common_assignment_count += 1
        for coordinate, closed_label in enumerate(closed):
            if closed_label == group.identity or coordinate in single_witnesses:
                continue
            for longitude_index, value in enumerate(values):
                if value == closed_label:
                    single_witnesses[coordinate] = (longitude_index, assignment)
                    break

    subgroup = frozenset(subgroup_generated_elements(group, generator_values))
    rows = []
    for coordinate, closed_label in enumerate(closed):
        if closed_label == group.identity:
            continue
        witness = single_witnesses.get(coordinate)
        rows.append(
            ProductClosedLabelLongitudeRouteRow(
                coordinate=coordinate,
                closed_label=closed_label,
                has_single_longitude_witness=witness is not None,
                in_longitude_subgroup=closed_label in subgroup,
                witness_longitude_index=None if witness is None else witness[0],
                witness_assignment=None if witness is None else witness[1],
            )
        )

    return ProductClosedLabelLongitudeRouteAudit(
        common_assignment_count=common_assignment_count,
        longitude_generator_count=len(generator_values),
        longitude_subgroup_size=len(subgroup),
        rows=tuple(rows),
    )


def product_closed_label_longitude_subgroup_failures(
    interval: LocalInterval,
    branch: ProductBranch,
    color_tuple: Sequence[Color],
    braid_words: Sequence[Sequence[int]],
    max_assignments: int = 100_000,
    max_failures: int = 5,
) -> Tuple[ProductClosedLabelLongitudeSubgroupFailure, ...]:
    """Find bounded closed-label failures of the longitude-subgroup criterion."""

    failures = []
    for braid_word in braid_words:
        word = tuple(braid_word)
        try:
            audit = product_closed_label_longitude_subgroup_audit(
                interval,
                branch,
                color_tuple,
                word,
                max_assignments=max_assignments,
            )
        except ValueError:
            continue
        bad_rows = tuple(
            row for row in audit.rows if not row.in_longitude_subgroup
        )
        if not bad_rows:
            continue
        failures.append(
            ProductClosedLabelLongitudeSubgroupFailure(
                braid_word=word,
                audit=audit,
                bad_rows=bad_rows,
            )
        )
        if len(failures) >= max_failures:
            break
    return tuple(failures)


def product_holonomy_longitude_subgroup_audit(
    interval: LocalInterval,
    branch: ProductBranch,
    color_tuple: Sequence[Color],
    braid_word: Sequence[int],
    max_assignments: int = 100_000,
) -> ProductHolonomyLongitudeSubgroupAudit:
    """Check normalized product holonomies against longitude-value subgroups."""

    n = len(color_tuple)
    closed = product_holonomy_closed_label_permutations(
        interval,
        branch,
        color_tuple,
        braid_word,
    )
    groups = {
        target.model_points: target.group
        for target in product_holonomy_groups(interval, branch)
    }
    cache: Dict[
        Tuple[FibrePoint, ...],
        Tuple[Tuple[Permutation, ...], frozenset[Permutation]],
    ] = {}
    generator_counts: Dict[Tuple[FibrePoint, ...], int] = {}
    subgroup_sizes: Dict[Tuple[FibrePoint, ...], int] = {}
    rows = []
    for coordinate, (model_points, permutation) in enumerate(closed):
        identity = tuple(range(len(model_points)))
        if permutation == identity:
            continue
        group = groups.get(model_points)
        if group is None:
            raise ValueError("closed holonomy has no generated holonomy group")
        if model_points not in cache:
            generator_values = longitude_value_generators(
                group,
                n,
                braid_word,
                max_assignments=max_assignments,
            )
            subgroup = frozenset(
                longitude_value_subgroup_elements(
                    group,
                    n,
                    braid_word,
                    max_assignments=max_assignments,
                )
            )
            cache[model_points] = (generator_values, subgroup)
            generator_counts[model_points] = len(generator_values)
            subgroup_sizes[model_points] = len(subgroup)
        _generator_values, subgroup = cache[model_points]
        rows.append(
            ProductHolonomyLongitudeSubgroupRow(
                coordinate=coordinate,
                model_points=model_points,
                closed_holonomy=permutation,
                in_longitude_subgroup=permutation in subgroup,
            )
        )
    return ProductHolonomyLongitudeSubgroupAudit(
        generator_counts=generator_counts,
        subgroup_sizes=subgroup_sizes,
        rows=tuple(rows),
    )


def product_holonomy_longitude_subgroup_failures(
    interval: LocalInterval,
    branch: ProductBranch,
    color_tuple: Sequence[Color],
    braid_words: Sequence[Sequence[int]],
    max_assignments: int = 100_000,
    max_failures: int = 5,
) -> Tuple[ProductHolonomyLongitudeSubgroupFailure, ...]:
    """Find bounded failures of the normalized holonomy subgroup criterion."""

    failures = []
    for braid_word in braid_words:
        word = tuple(braid_word)
        try:
            audit = product_holonomy_longitude_subgroup_audit(
                interval,
                branch,
                color_tuple,
                word,
                max_assignments=max_assignments,
            )
        except ValueError:
            continue
        bad_rows = tuple(row for row in audit.rows if not row.in_longitude_subgroup)
        if not bad_rows:
            continue
        failures.append(
            ProductHolonomyLongitudeSubgroupFailure(
                braid_word=word,
                audit=audit,
                bad_rows=bad_rows,
            )
        )
        if len(failures) >= max_failures:
            break
    return tuple(failures)


def _normalized_holonomy_failure(
    interval: LocalInterval,
    branch: ProductBranch,
    color_tuple: Sequence[Color],
    action,
    braid_word: Tuple[int, ...],
) -> ProductHolonomyExactFailure | None:
    identity_dependency = tuple(range(len(color_tuple)))
    if action.final_colors != tuple(color_tuple):
        return None
    if action.dependency != identity_dependency:
        return None
    for coordinate, (model_points, permutation) in enumerate(
        product_holonomy_closed_label_permutations(
            interval,
            branch,
            color_tuple,
            braid_word,
        )
    ):
        if permutation != tuple(range(len(model_points))):
            return ProductHolonomyExactFailure(
                braid_word=braid_word,
                coordinate=coordinate,
                model_points=model_points,
                closed_holonomy=permutation,
            )
    return None


def product_holonomy_exact_audit(
    interval: LocalInterval,
    branch: ProductBranch,
    color_tuple: Sequence[Color],
    *,
    base_detector: FiniteBraidedSet | None = None,
    extra_groups: Sequence[FiniteGroup] = (),
    state_limit: int = 10000,
) -> ProductHolonomyExactAudit:
    """Close the fixed-degree normalized-holonomy/detector image exactly.

    The bounded subgroup audit checks supplied braid words.  This audit closes
    the finite joint image at one braid degree and one colour tuple, using the
    gauge-normalized product holonomy groups themselves as finite-G detector
    factors.  A nontruncated run with no failure proves the normalized
    holonomy kernel implication only for this fixed degree, tuple, base
    detector, and interval.
    """

    n = len(color_tuple)
    if n < 1:
        raise ValueError("colour tuple must be nonempty")
    if any(color not in interval.colors for color in color_tuple):
        raise ValueError("unknown colour in tuple")

    alphabet = tuple(i for generator in range(1, n) for i in (generator, -generator))
    identity_permutation = tuple(range(n))
    if base_detector is None:
        base_detector = FiniteBraidedSet(interval.colors, interval.base_R)
    base_identity = tuple(range(len(base_detector.elements) ** n))
    base_generators = {
        signed: _solution_generator_permutation(base_detector, n, signed)
        for signed in alphabet
    }
    holonomy_targets = product_holonomy_groups(interval, branch)
    holonomy_groups = tuple(target.group for target in holonomy_targets)
    groups = holonomy_groups + tuple(extra_groups)
    group_initial = tuple(_group_detector_initial_int_state(group, n) for group in groups)
    group_tables = tuple(_group_int_tables(group) for group in groups)
    initial_action = _product_action_state(interval, branch, color_tuple, tuple())
    initial = (base_identity, identity_permutation, initial_action, group_initial, tuple())

    queue = deque([initial])
    visited = {(base_identity, identity_permutation, initial_action, group_initial)}
    base_states = {base_identity}
    product_states = {initial_action}
    detector_states = {(base_identity, identity_permutation, group_initial)}
    closed_states = set()
    identity_detector_closed_states = set()

    while queue:
        base_state, permutation, action, group_state, word = queue.popleft()
        for signed in alphabet:
            next_word = word + (signed,)
            next_base = _compose_permutation(base_generators[signed], base_state)
            next_permutation = _next_braid_permutation(permutation, signed)
            next_action = _product_action_state(
                interval,
                branch,
                color_tuple,
                next_word,
            )
            next_groups = tuple(
                _apply_group_detector_generator_int(group, state, signed, n, tables)
                for group, state, tables in zip(groups, group_state, group_tables)
            )
            key = (next_base, next_permutation, next_action, next_groups)
            if key in visited:
                continue
            visited.add(key)
            base_states.add(next_base)
            product_states.add(next_action)
            detector_states.add((next_base, next_permutation, next_groups))

            closed = (
                next_base == base_identity
                and next_permutation == identity_permutation
                and next_action.final_colors == tuple(color_tuple)
                and next_action.dependency == identity_permutation
            )
            if closed:
                closed_states.add((next_permutation, next_action))
                if next_groups == group_initial:
                    identity_detector_closed_states.add((next_permutation, next_action))
                    failure = _normalized_holonomy_failure(
                        interval,
                        branch,
                        color_tuple,
                        next_action,
                        next_word,
                    )
                    if failure is not None:
                        return ProductHolonomyExactAudit(
                            n=n,
                            visited_state_count=len(visited),
                            base_state_count=len(base_states),
                            product_state_count=len(product_states),
                            detector_state_count=len(detector_states),
                            closed_state_count=len(closed_states),
                            identity_detector_closed_state_count=len(
                                identity_detector_closed_states
                            ),
                            holonomy_group_orders=tuple(
                                len(group.elements) for group in holonomy_groups
                            ),
                            extra_group_orders=tuple(
                                len(group.elements) for group in extra_groups
                            ),
                            truncated=False,
                            failure=failure,
                        )

            if len(visited) > state_limit:
                return ProductHolonomyExactAudit(
                    n=n,
                    visited_state_count=len(visited),
                    base_state_count=len(base_states),
                    product_state_count=len(product_states),
                    detector_state_count=len(detector_states),
                    closed_state_count=len(closed_states),
                    identity_detector_closed_state_count=len(
                        identity_detector_closed_states
                    ),
                    holonomy_group_orders=tuple(
                        len(group.elements) for group in holonomy_groups
                    ),
                    extra_group_orders=tuple(
                        len(group.elements) for group in extra_groups
                    ),
                    truncated=True,
                    failure=None,
                )
            queue.append((next_base, next_permutation, next_action, next_groups, next_word))

    return ProductHolonomyExactAudit(
        n=n,
        visited_state_count=len(visited),
        base_state_count=len(base_states),
        product_state_count=len(product_states),
        detector_state_count=len(detector_states),
        closed_state_count=len(closed_states),
        identity_detector_closed_state_count=len(identity_detector_closed_states),
        holonomy_group_orders=tuple(len(group.elements) for group in holonomy_groups),
        extra_group_orders=tuple(len(group.elements) for group in extra_groups),
        truncated=False,
        failure=None,
    )


def _product_action_state(
    interval: LocalInterval,
    branch: ProductBranch,
    color_tuple: Sequence[Color],
    braid_word: Sequence[int],
):
    if branch == "swapped":
        return product_permutation_action(interval, color_tuple, braid_word)
    if branch == "direct":
        return direct_product_action(interval, color_tuple, braid_word)
    raise ValueError(f"unknown product branch {branch!r}")


def _next_braid_permutation(
    permutation: Tuple[int, ...],
    signed_generator: int,
) -> Tuple[int, ...]:
    out = list(permutation)
    index = abs(signed_generator) - 1
    out[index], out[index + 1] = out[index + 1], out[index]
    return tuple(out)


def _closed_label_failure(
    interval: LocalInterval,
    color_tuple: Sequence[Color],
    action,
    braid_word: Tuple[int, ...],
) -> ProductClosedLabelExactFailure | None:
    identity_dependency = tuple(range(len(color_tuple)))
    if action.final_colors != tuple(color_tuple):
        return None
    if action.dependency != identity_dependency:
        return None
    for coordinate, mapping in enumerate(action.coordinate_maps):
        if any(source != target for source, target in mapping):
            return ProductClosedLabelExactFailure(
                braid_word=braid_word,
                coordinate=coordinate,
                closed_label=tuple(mapping),
            )
    return None


def product_closed_label_exact_audit(
    interval: LocalInterval,
    branch: ProductBranch,
    groups: Sequence[FiniteGroup],
    color_tuple: Sequence[Color],
    *,
    base_detector: FiniteBraidedSet | None = None,
    state_limit: int = 10000,
) -> ProductClosedLabelExactAudit:
    """Close the fixed-degree product-label/detector image exactly.

    This is the product-branch analogue of a fixed-``n`` residual image
    audit.  It explores the finite joint image of:

    - the base detector action, defaulting to the quotient colour action;
    - the product label action on one supplied colour tuple;
    - the Artin strand permutation; and
    - the finite-group Artin-longitude detector states for ``groups``.

    A failure is a braid with identity base-detector action, identity Artin
    permutation, identity detector state, and a nonidentity closed product
    label on the supplied tuple.  A nontruncated run with no failure proves
    the kernel implication only for this fixed colour tuple, fixed braid
    degree, base detector, and detector list.
    """

    n = len(color_tuple)
    if n < 1:
        raise ValueError("colour tuple must be nonempty")
    if any(color not in interval.colors for color in color_tuple):
        raise ValueError("unknown colour in tuple")

    alphabet = tuple(i for generator in range(1, n) for i in (generator, -generator))
    identity_permutation = tuple(range(n))
    if base_detector is None:
        base_detector = FiniteBraidedSet(interval.colors, interval.base_R)
    base_identity = tuple(range(len(base_detector.elements) ** n))
    base_generators = {
        signed: _solution_generator_permutation(base_detector, n, signed)
        for signed in alphabet
    }
    group_initial = tuple(_group_detector_initial_int_state(group, n) for group in groups)
    group_tables = tuple(_group_int_tables(group) for group in groups)
    initial_action = _product_action_state(interval, branch, color_tuple, tuple())
    initial = (base_identity, identity_permutation, initial_action, group_initial, tuple())

    queue = deque([initial])
    visited = {(base_identity, identity_permutation, initial_action, group_initial)}
    base_states = {base_identity}
    product_states = {initial_action}
    detector_states = {(base_identity, identity_permutation, group_initial)}
    closed_states = set()
    identity_detector_closed_states = set()

    while queue:
        base_state, permutation, action, group_state, word = queue.popleft()
        for signed in alphabet:
            index = abs(signed) - 1
            if index < 0 or index + 1 >= n:
                raise IndexError(index)
            next_word = word + (signed,)
            next_base = _compose_permutation(base_generators[signed], base_state)
            next_permutation = _next_braid_permutation(permutation, signed)
            next_action = _product_action_state(
                interval,
                branch,
                color_tuple,
                next_word,
            )
            next_groups = tuple(
                _apply_group_detector_generator_int(group, state, signed, n, tables)
                for group, state, tables in zip(groups, group_state, group_tables)
            )
            key = (next_base, next_permutation, next_action, next_groups)
            if key in visited:
                continue
            visited.add(key)
            base_states.add(next_base)
            product_states.add(next_action)
            detector_states.add((next_base, next_permutation, next_groups))

            closed = (
                next_base == base_identity
                and next_permutation == identity_permutation
                and next_action.final_colors == tuple(color_tuple)
                and next_action.dependency == identity_permutation
            )
            if closed:
                closed_states.add((next_permutation, next_action))
                if next_groups == group_initial:
                    identity_detector_closed_states.add((next_permutation, next_action))
                    failure = _closed_label_failure(
                        interval,
                        color_tuple,
                        next_action,
                        next_word,
                    )
                    if failure is not None:
                        return ProductClosedLabelExactAudit(
                            n=n,
                            visited_state_count=len(visited),
                            base_state_count=len(base_states),
                            product_state_count=len(product_states),
                            detector_state_count=len(detector_states),
                            closed_state_count=len(closed_states),
                            identity_detector_closed_state_count=len(
                                identity_detector_closed_states
                            ),
                            truncated=False,
                            failure=failure,
                        )

            if len(visited) > state_limit:
                return ProductClosedLabelExactAudit(
                    n=n,
                    visited_state_count=len(visited),
                    base_state_count=len(base_states),
                    product_state_count=len(product_states),
                    detector_state_count=len(detector_states),
                    closed_state_count=len(closed_states),
                    identity_detector_closed_state_count=len(
                        identity_detector_closed_states
                    ),
                    truncated=True,
                    failure=None,
                )
            queue.append((next_base, next_permutation, next_action, next_groups, next_word))

    return ProductClosedLabelExactAudit(
        n=n,
        visited_state_count=len(visited),
        base_state_count=len(base_states),
        product_state_count=len(product_states),
        detector_state_count=len(detector_states),
        closed_state_count=len(closed_states),
        identity_detector_closed_state_count=len(identity_detector_closed_states),
        truncated=False,
        failure=None,
    )


def swapped_product_label_group(
    interval: LocalInterval,
    witness: ProductPermutationWitness | None = None,
) -> ProductLabelGroup:
    """Return the finite group generated by swapped product labels."""

    witness = product_permutation_witness(interval) if witness is None else witness
    if witness is None:
        raise ValueError("interval is not in product-permutation form")
    labels = tuple(
        (kind, a, b, 1)
        for a, b in product(interval.colors, repeat=2)
        for kind in ("L", "R")
    )
    generators = tuple(
        (label, swapped_product_label_permutation(interval, label, witness))
        for label in labels
    )
    universe = product_label_universe(interval)
    group = permutation_group_from_generators(
        (permutation for _label, permutation in generators),
        degree=len(universe),
    )
    return ProductLabelGroup("swapped", universe, generators, group)


def direct_product_label_group(
    interval: LocalInterval,
    witness: DirectProductWitness | None = None,
) -> ProductLabelGroup:
    """Return the finite group generated by direct product labels."""

    witness = direct_product_witness(interval) if witness is None else witness
    if witness is None:
        raise ValueError("interval is not in direct product-permutation form")
    labels = tuple(
        (kind, a, b, 1)
        for a, b in product(interval.colors, repeat=2)
        for kind in ("L", "R")
    )
    generators = tuple(
        (label, direct_product_label_permutation(interval, label, witness))
        for label in labels
    )
    universe = product_label_universe(interval)
    group = permutation_group_from_generators(
        (permutation for _label, permutation in generators),
        degree=len(universe),
    )
    return ProductLabelGroup("direct", universe, generators, group)
