from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations, product
from typing import Dict, FrozenSet, Hashable, Iterable, List, Mapping, Sequence, Tuple

Color = Hashable
FibrePoint = Hashable
ReadoutLabel = Hashable
Block = FrozenSet[FibrePoint]
Partition = Tuple[Block, ...]
PairFamily = Mapping[Color, Iterable[Tuple[FibrePoint, FibrePoint]]]
ReadoutLabels = Mapping[Color, Mapping[FibrePoint, ReadoutLabel]]


@dataclass(frozen=True)
class TransportFailure:
    a: Color
    b: Color
    c: Color
    d: Color
    side: str
    witness: Tuple[Tuple[FibrePoint, FibrePoint], Tuple[FibrePoint, FibrePoint]]


@dataclass(frozen=True)
class SemisplitAudit:
    universal_colors: Tuple[Color, ...]
    family: Mapping[Color, Partition]
    admissible: bool
    failure: TransportFailure | None


@dataclass(frozen=True)
class SemisplitConstraintRow:
    """Allowed equality/universal bit patterns for one coloured crossing.

    Patterns are ordered as `(source_a, source_b, target_c, target_d)`, where
    `0` means equality on that fibre and `1` means universal.
    """

    a: Color
    b: Color
    c: Color
    d: Color
    allowed_patterns: Tuple[Tuple[int, int, int, int], ...]


@dataclass(frozen=True)
class GeneratedCongruenceDerivationRow:
    """First derivation of one nontrivial relation edge in a closure audit."""

    depth: int
    color: Color
    left: FibrePoint
    right: FibrePoint
    source: str
    crossing: Tuple[Color, Color] | None
    source_pairs: Tuple[Tuple[Color, FibrePoint, FibrePoint], ...]


@dataclass(frozen=True)
class GeneratedCongruenceAudit:
    seed_pair_count: int
    stable_depth: int
    family: Mapping[Color, Partition]
    kind: str
    pair_count_rows: Tuple[Tuple[Color, int], ...]
    edge_count_rows: Tuple[Tuple[Color, int], ...]
    component_count_rows: Tuple[Tuple[Color, int], ...]
    diameter_rows: Tuple[Tuple[Color, int], ...]
    derivation_rows: Tuple[GeneratedCongruenceDerivationRow, ...] = ()

    @property
    def derivation_count_rows(self) -> Tuple[Tuple[Color, int], ...]:
        return tuple(
            (color, sum(1 for row in self.derivation_rows if row.color == color))
            for color, _count in self.edge_count_rows
        )


@dataclass(frozen=True)
class PairGeneratedLocalMinimalityAudit:
    """Least admissible family generated by one nontrivial fibre pair."""

    color: Color
    left: FibrePoint
    right: FibrePoint
    generated: GeneratedCongruenceAudit


@dataclass(frozen=True)
class CoordinateKernelPairClosureAudit:
    """Least admissible family generated by one coordinate-kernel pair."""

    color: Color
    left: FibrePoint
    right: FibrePoint
    include_coretraction_kernels: bool
    generated: GeneratedCongruenceAudit


@dataclass(frozen=True)
class ContinuationSeedRow:
    """One second-output change of the strand-continuing coordinate."""

    left_color: Color
    right_color: Color
    output_left_color: Color
    output_right_color: Color
    left_input: FibrePoint
    right_input: FibrePoint
    continuing_output: FibrePoint


@dataclass(frozen=True)
class ContinuationCongruenceAudit:
    """Least admissible closure of all strand-continuation changes."""

    seed_rows: Tuple[ContinuationSeedRow, ...]
    non_rack_base_rows: Tuple[Tuple[Color, Color, Color, Color], ...]
    generated: GeneratedCongruenceAudit

    @property
    def nontrivial_seed_count(self) -> int:
        return len(self.seed_rows)

    @property
    def base_rows_are_left_rack_form(self) -> bool:
        return not self.non_rack_base_rows

    @property
    def is_strand_continuing_on_the_nose(self) -> bool:
        return self.base_rows_are_left_rack_form and not self.seed_rows

    @property
    def continuation_closure_is_universal(self) -> bool:
        return self.generated.kind == "universal"

    @property
    def continuation_closure_is_proper(self) -> bool:
        return self.generated.kind not in ("equality", "universal")

    @property
    def proves_transport_or_universal_dichotomy(self) -> bool:
        return self.base_rows_are_left_rack_form and (
            self.is_strand_continuing_on_the_nose
            or self.continuation_closure_is_universal
        )


@dataclass(frozen=True)
class SectionUnitRowAudit:
    """Coordinate-section bijectivity for one coloured local row."""

    left_color: Color
    right_color: Color
    output_left_color: Color
    output_right_color: Color
    left_unit_inputs: Tuple[FibrePoint, ...]
    left_nonunit_inputs: Tuple[FibrePoint, ...]
    right_unit_inputs: Tuple[FibrePoint, ...]
    right_nonunit_inputs: Tuple[FibrePoint, ...]

    @property
    def all_left_sections_bijective(self) -> bool:
        return not self.left_nonunit_inputs

    @property
    def all_right_sections_bijective(self) -> bool:
        return not self.right_nonunit_inputs

    @property
    def row_is_two_sided_unit(self) -> bool:
        return self.all_left_sections_bijective and self.all_right_sections_bijective

    @property
    def row_has_unit_section(self) -> bool:
        return bool(self.left_unit_inputs or self.right_unit_inputs)

    @property
    def row_has_nonunit_section(self) -> bool:
        return bool(self.left_nonunit_inputs or self.right_nonunit_inputs)

    @property
    def row_is_mixed_unit(self) -> bool:
        return self.row_has_unit_section and self.row_has_nonunit_section


@dataclass(frozen=True)
class TwoSidedUnitCollapseAudit:
    """Classify the final continuation row by coordinate-section units."""

    colored_ybe: bool
    continuation: ContinuationCongruenceAudit
    row_audits: Tuple[SectionUnitRowAudit, ...]

    @property
    def all_rows_two_sided_unit(self) -> bool:
        return all(row.row_is_two_sided_unit for row in self.row_audits)

    @property
    def mixed_unit_rows(self) -> Tuple[SectionUnitRowAudit, ...]:
        return tuple(row for row in self.row_audits if row.row_is_mixed_unit)

    @property
    def non_two_sided_rows(self) -> Tuple[SectionUnitRowAudit, ...]:
        return tuple(row for row in self.row_audits if not row.row_is_two_sided_unit)

    @property
    def strand_continuing_case(self) -> bool:
        return self.continuation.is_strand_continuing_on_the_nose

    @property
    def two_sided_unit_closed_branch(self) -> bool:
        return (
            self.colored_ybe
            and self.all_rows_two_sided_unit
            and not self.strand_continuing_case
        )

    @property
    def locally_nondegenerate_closed_branch(self) -> bool:
        return self.colored_ybe and self.all_rows_two_sided_unit

    @property
    def mixed_unit_context_recovery_remaining(self) -> bool:
        return (
            self.colored_ybe
            and not self.strand_continuing_case
            and not self.all_rows_two_sided_unit
            and bool(self.mixed_unit_rows)
        )

    @property
    def only_mixed_unit_obstruction_rows(self) -> Tuple[SectionUnitRowAudit, ...]:
        if not self.mixed_unit_context_recovery_remaining:
            return ()
        return self.mixed_unit_rows


@dataclass(frozen=True)
class SectionKernelCompanionRow:
    """One coordinate-section collision and its companion-output separation."""

    side: str
    left_color: Color
    right_color: Color
    output_left_color: Color
    output_right_color: Color
    fixed_input: FibrePoint
    collapsed_inputs: Tuple[FibrePoint, FibrePoint]
    common_output: FibrePoint
    companion_outputs: Tuple[FibrePoint, FibrePoint]

    @property
    def companion_outputs_distinct(self) -> bool:
        return self.companion_outputs[0] != self.companion_outputs[1]


@dataclass(frozen=True)
class SectionKernelCompanionAudit:
    """Finite ledger for where nonunit section kernels are recovered."""

    collision_rows: Tuple[SectionKernelCompanionRow, ...]

    @property
    def has_section_kernel(self) -> bool:
        return bool(self.collision_rows)

    @property
    def every_collision_companion_separated(self) -> bool:
        return all(row.companion_outputs_distinct for row in self.collision_rows)

    @property
    def left_section_collision_rows(self) -> Tuple[SectionKernelCompanionRow, ...]:
        return tuple(row for row in self.collision_rows if row.side == "left")

    @property
    def right_section_collision_rows(self) -> Tuple[SectionKernelCompanionRow, ...]:
        return tuple(row for row in self.collision_rows if row.side == "right")


@dataclass(frozen=True)
class SectionRankProfileRow:
    """Rank and kernel profile for one coordinate section."""

    side: str
    left_color: Color
    right_color: Color
    output_left_color: Color
    output_right_color: Color
    fixed_input: FibrePoint
    domain_size: int
    codomain_size: int
    rank: int
    kernel_blocks: Tuple[Tuple[FibrePoint, ...], ...]
    image: Tuple[FibrePoint, ...]

    @property
    def kernel_block_sizes(self) -> Tuple[int, ...]:
        return tuple(len(block) for block in self.kernel_blocks)

    @property
    def kernel_kind(self) -> str:
        if all(size == 1 for size in self.kernel_block_sizes):
            return "equality"
        if len(self.kernel_blocks) == 1:
            return "universal"
        return "proper"

    @property
    def is_injective(self) -> bool:
        return self.kernel_kind == "equality"

    @property
    def is_surjective(self) -> bool:
        return self.rank == self.codomain_size

    @property
    def is_bijective(self) -> bool:
        return self.is_injective and self.is_surjective

    @property
    def is_constant(self) -> bool:
        return self.rank == 1

    @property
    def has_proper_nontrivial_kernel(self) -> bool:
        return self.kernel_kind == "proper"

    @property
    def is_injective_non_surjective(self) -> bool:
        return self.is_injective and not self.is_surjective


@dataclass(frozen=True)
class SectionRankProfileCollapseAudit:
    """Rank-profile split for the mixed-unit continuation obstruction."""

    rows: Tuple[SectionRankProfileRow, ...]

    @property
    def proper_kernel_rows(self) -> Tuple[SectionRankProfileRow, ...]:
        return tuple(row for row in self.rows if row.has_proper_nontrivial_kernel)

    @property
    def constant_section_rows(self) -> Tuple[SectionRankProfileRow, ...]:
        return tuple(row for row in self.rows if row.kernel_kind == "universal")

    @property
    def injective_non_surjective_rows(self) -> Tuple[SectionRankProfileRow, ...]:
        return tuple(row for row in self.rows if row.is_injective_non_surjective)

    @property
    def nonunit_rows(self) -> Tuple[SectionRankProfileRow, ...]:
        return tuple(row for row in self.rows if not row.is_bijective)

    @property
    def hidden_kernel_rows_after_proper_profiles_removed(
        self,
    ) -> Tuple[SectionRankProfileRow, ...]:
        return tuple(
            row
            for row in self.nonunit_rows
            if not row.has_proper_nontrivial_kernel
            and not row.is_injective_non_surjective
        )

    @property
    def hidden_kernel_rows_are_constant(self) -> bool:
        return all(
            row.is_constant
            for row in self.hidden_kernel_rows_after_proper_profiles_removed
        )


@dataclass(frozen=True)
class ContinuationSeedPairClosureAudit:
    """Least admissible closure generated by one continuation-change pair."""

    color: Color
    left: FibrePoint
    right: FibrePoint
    seed_rows: Tuple[ContinuationSeedRow, ...]
    generated: GeneratedCongruenceAudit


@dataclass(frozen=True)
class ContinuationSeedUniversalDerivationAudit:
    """Derivation coverage of a single continuation seed's universal closure."""

    seed_closure: ContinuationSeedPairClosureAudit
    edge_count_rows: Tuple[Tuple[Color, int], ...]
    derivation_count_rows: Tuple[Tuple[Color, int], ...]
    missing_derivation_count_rows: Tuple[Tuple[Color, int], ...]

    @property
    def closure_is_universal(self) -> bool:
        return self.seed_closure.generated.kind == "universal"

    @property
    def every_edge_has_derivation(self) -> bool:
        return all(count == 0 for _color, count in self.missing_derivation_count_rows)

    @property
    def proves_single_seed_universal_derivation(self) -> bool:
        return self.closure_is_universal and self.every_edge_has_derivation


@dataclass(frozen=True)
class ContinuationSeedReadoutPropagationAudit:
    """Containment of a continuation seed closure in a fixed readout relation."""

    seed_closure: ContinuationSeedPairClosureAudit
    readout_family: Mapping[Color, Partition]
    readout_kind: str
    readout_is_admissible: bool
    seed_contained: bool
    generated_contained: bool
    missing_generated_edges: Tuple[Tuple[Color, FibrePoint, FibrePoint], ...]

    @property
    def proves_readout_propagation(self) -> bool:
        return (
            self.readout_is_admissible
            and self.seed_contained
            and self.generated_contained
        )

    @property
    def forces_universal_readout(self) -> bool:
        return (
            self.proves_readout_propagation
            and self.seed_closure.generated.kind == "universal"
            and self.readout_kind == "universal"
        )


@dataclass(frozen=True)
class ReadoutKernelAudit:
    """Kernel congruence audit for a finite fibrewise readout."""

    family: Mapping[Color, Partition]
    kind: str
    label_count_rows: Tuple[Tuple[Color, int], ...]
    block_count_rows: Tuple[Tuple[Color, int], ...]
    admissible: bool
    failure: TransportFailure | None

    @property
    def proves_readout_kernel_admissible(self) -> bool:
        return self.admissible


@dataclass(frozen=True)
class ProductReadoutKernelAudit:
    """Assembly audit for tuple-valued products of finite readout labels."""

    factor_audits: Tuple[ReadoutKernelAudit, ...]
    product_labels: ReadoutLabels
    product_audit: ReadoutKernelAudit
    meet_family: Mapping[Color, Partition]
    product_family_is_factor_meet: bool

    @property
    def all_factors_admissible(self) -> bool:
        return all(audit.admissible for audit in self.factor_audits)

    @property
    def proves_product_readout_kernel_admissible(self) -> bool:
        return (
            self.factor_audits != ()
            and self.all_factors_admissible
            and self.product_family_is_factor_meet
            and self.product_audit.admissible
        )


@dataclass(frozen=True)
class ReadoutDescentSeparationAudit:
    """Descent-separation certificate for finite readout labels."""

    readout_kernel: ReadoutKernelAudit
    continuation: ContinuationCongruenceAudit
    propagation_audits: Tuple[ContinuationSeedReadoutPropagationAudit, ...]
    surviving_seed_rows: Tuple[ContinuationSeedRow, ...]
    quotient_interval: LocalInterval | None
    quotient_continuation: ContinuationCongruenceAudit | None

    @property
    def readout_is_admissible(self) -> bool:
        return self.readout_kernel.admissible

    @property
    def all_seed_closures_propagate(self) -> bool:
        return all(audit.proves_readout_propagation for audit in self.propagation_audits)

    @property
    def all_continuation_seeds_killed(self) -> bool:
        return not self.surviving_seed_rows

    @property
    def quotient_is_strand_continuing(self) -> bool:
        return (
            self.continuation.base_rows_are_left_rack_form
            and self.readout_is_admissible
            and self.all_continuation_seeds_killed
            and self.quotient_continuation is not None
            and self.quotient_continuation.is_strand_continuing_on_the_nose
        )

    @property
    def proves_descent_separation_readout(self) -> bool:
        return self.quotient_is_strand_continuing and self.all_seed_closures_propagate


@dataclass(frozen=True)
class ProductReadoutDescentSeparationAudit:
    """Integrated certificate for product readout descent separation."""

    product_kernel: ProductReadoutKernelAudit
    descent: ReadoutDescentSeparationAudit
    factor_surviving_seed_rows: Tuple[Tuple[int, Tuple[ContinuationSeedRow, ...]], ...]
    product_surviving_seed_rows: Tuple[ContinuationSeedRow, ...]
    factor_survival_union: Tuple[ContinuationSeedRow, ...]
    product_survival_is_factor_union: bool

    @property
    def all_factor_seed_rows_killed(self) -> bool:
        return all(not rows for _index, rows in self.factor_surviving_seed_rows)

    @property
    def proves_product_descent_separation(self) -> bool:
        return (
            self.product_kernel.proves_product_readout_kernel_admissible
            and self.product_survival_is_factor_union
            and self.all_factor_seed_rows_killed
            and self.descent.proves_descent_separation_readout
        )


@dataclass(frozen=True)
class ReadoutSeedSaturationAudit:
    """Least admissible coarsening that contains readout and continuation seeds."""

    readout_kernel: ReadoutKernelAudit
    continuation: ContinuationCongruenceAudit
    saturation: GeneratedCongruenceAudit
    saturated_labels: ReadoutLabels
    saturated_readout_kernel: ReadoutKernelAudit
    saturated_descent: ReadoutDescentSeparationAudit
    original_surviving_seed_rows: Tuple[ContinuationSeedRow, ...]
    missing_readout_kernel_edges: Tuple[Tuple[Color, FibrePoint, FibrePoint], ...]
    new_saturation_edges: Tuple[Tuple[Color, FibrePoint, FibrePoint], ...]

    @property
    def saturation_contains_readout_kernel(self) -> bool:
        return not self.missing_readout_kernel_edges

    @property
    def saturation_adds_no_new_edges(self) -> bool:
        return not self.new_saturation_edges

    @property
    def proves_admissible_seed_saturation(self) -> bool:
        return (
            self.readout_kernel.admissible
            and self.saturation_contains_readout_kernel
            and self.saturated_readout_kernel.admissible
            and self.saturated_readout_kernel.family == self.saturation.family
            and self.saturated_descent.all_continuation_seeds_killed
        )

    @property
    def proves_saturated_descent_separation(self) -> bool:
        return (
            self.proves_admissible_seed_saturation
            and self.saturated_descent.proves_descent_separation_readout
        )


@dataclass(frozen=True)
class LocalMinimalSeedSaturationDichotomyAudit:
    """Local-minimal dichotomy for an admissible readout seed-saturation."""

    seed_saturation: ReadoutSeedSaturationAudit
    interval_is_local_minimal: bool
    expected_saturation_kind: str | None

    @property
    def readout_kernel_has_local_minimal_kind(self) -> bool:
        return self.seed_saturation.readout_kernel.kind in ("equality", "universal")

    @property
    def saturation_has_local_minimal_kind(self) -> bool:
        return self.seed_saturation.saturation.kind in ("equality", "universal")

    @property
    def forced_universal_collapse(self) -> bool:
        return (
            self.expected_saturation_kind == "universal"
            and self.seed_saturation.readout_kernel.kind == "equality"
            and bool(self.seed_saturation.original_surviving_seed_rows)
        )

    @property
    def needs_external_routing_after_collapse(self) -> bool:
        return self.forced_universal_collapse

    @property
    def proves_local_minimal_seed_saturation_dichotomy(self) -> bool:
        return (
            self.interval_is_local_minimal
            and self.seed_saturation.readout_kernel.admissible
            and self.readout_kernel_has_local_minimal_kind
            and self.saturation_has_local_minimal_kind
            and self.expected_saturation_kind is not None
            and self.seed_saturation.saturation.kind == self.expected_saturation_kind
        )


@dataclass(frozen=True)
class LostEdgeExternalRoutingAudit:
    """External routing ledger for edges collapsed by seed-saturation."""

    dichotomy: LocalMinimalSeedSaturationDichotomyAudit
    routing_labels: ReadoutLabels
    routing_kernel: ReadoutKernelAudit
    lost_edges: Tuple[Tuple[Color, FibrePoint, FibrePoint], ...]
    routed_edges: Tuple[Tuple[Color, FibrePoint, FibrePoint], ...]
    unrouted_edges: Tuple[Tuple[Color, FibrePoint, FibrePoint], ...]

    @property
    def forced_collapse_requires_routing(self) -> bool:
        return self.dichotomy.needs_external_routing_after_collapse

    @property
    def all_lost_edges_routed(self) -> bool:
        return not self.unrouted_edges

    @property
    def proves_external_routing_ledger(self) -> bool:
        return (
            self.dichotomy.proves_local_minimal_seed_saturation_dichotomy
            and (
                not self.forced_collapse_requires_routing
                or self.all_lost_edges_routed
            )
        )


def equality_partition(items: Sequence[FibrePoint]) -> Partition:
    return canonical_partition(frozenset([item]) for item in items)


def universal_partition(items: Sequence[FibrePoint]) -> Partition:
    return (frozenset(items),)


def canonical_partition(blocks: Iterable[Iterable[FibrePoint]]) -> Partition:
    frozen = [frozenset(block) for block in blocks if block]
    return tuple(
        sorted(frozen, key=lambda block: (len(block), tuple(sorted(map(repr, block)))))
    )


def same_block(partition: Partition, a: FibrePoint, b: FibrePoint) -> bool:
    return any(a in block and b in block for block in partition)


def partition_pairs(partition: Partition) -> FrozenSet[Tuple[FibrePoint, FibrePoint]]:
    pairs = set()
    for block in partition:
        for left in block:
            for right in block:
                pairs.add((left, right))
    return frozenset(pairs)


def set_partitions(items: Sequence[FibrePoint]) -> List[Partition]:
    """Enumerate set partitions. Suitable only for small audit examples."""

    ordered = list(items)
    if not ordered:
        return [tuple()]
    first, rest = ordered[0], ordered[1:]
    if not rest:
        return [(frozenset([first]),)]
    out: List[Partition] = []
    for partition in set_partitions(rest):
        out.append(canonical_partition([frozenset([first]), *partition]))
        for i, block in enumerate(partition):
            new_blocks = list(partition)
            new_blocks[i] = block.union([first])
            out.append(canonical_partition(new_blocks))
    unique = []
    seen = set()
    for partition in out:
        if partition not in seen:
            seen.add(partition)
            unique.append(partition)
    return unique


def relation_family_kind(
    interval: "LocalInterval", family: Mapping[Color, Partition]
) -> str:
    equality = all(len(family[color]) == len(interval.fibres[color]) for color in interval.colors)
    universal = all(
        family[color] == universal_partition(interval.fibres[color])
        for color in interval.colors
    )
    if equality:
        return "equality"
    if universal:
        return "universal"
    if any(family[color] == universal_partition(interval.fibres[color]) for color in interval.colors):
        return "semisplit_or_mixed"
    return "proper_mixed"


def readout_kernel_family(
    interval: "LocalInterval",
    labels: ReadoutLabels,
) -> Dict[Color, Partition]:
    """Return fibre partitions induced by equality of finite readout labels."""

    family = {}
    for color in interval.colors:
        if color not in labels:
            raise ValueError(f"missing readout labels for color {color!r}")
        color_labels = labels[color]
        expected = set(interval.fibres[color])
        actual = set(color_labels)
        if actual != expected:
            raise ValueError(f"readout label domain mismatch for color {color!r}")
        blocks_by_label: Dict[ReadoutLabel, List[FibrePoint]] = {}
        for point in interval.fibres[color]:
            blocks_by_label.setdefault(color_labels[point], []).append(point)
        family[color] = canonical_partition(blocks_by_label.values())
    return family


def readout_kernel_audit(
    interval: "LocalInterval",
    labels: ReadoutLabels,
) -> ReadoutKernelAudit:
    """Audit whether finite readout equality is an admissible congruence."""

    family = readout_kernel_family(interval, labels)
    failure = interval.congruence_family_failure(family)
    return ReadoutKernelAudit(
        family=family,
        kind=relation_family_kind(interval, family),
        label_count_rows=tuple(
            (color, len(set(labels[color].values())))
            for color in interval.colors
        ),
        block_count_rows=tuple(
            (color, len(family[color]))
            for color in interval.colors
        ),
        admissible=failure is None,
        failure=failure,
    )


def _meet_partition(left: Partition, right: Partition) -> Partition:
    return canonical_partition(
        left_block.intersection(right_block)
        for left_block in left
        for right_block in right
    )


def _meet_families(
    interval: "LocalInterval",
    families: Sequence[Mapping[Color, Partition]],
) -> Dict[Color, Partition]:
    if not families:
        raise ValueError("at least one family is required")
    current = {color: families[0][color] for color in interval.colors}
    for family in families[1:]:
        current = {
            color: _meet_partition(current[color], family[color])
            for color in interval.colors
        }
    return current


def product_readout_labels(
    interval: "LocalInterval",
    *label_families: ReadoutLabels,
) -> Dict[Color, Dict[FibrePoint, Tuple[ReadoutLabel, ...]]]:
    """Return tuple-valued labels combining fixed readout factors."""

    if not label_families:
        raise ValueError("at least one readout label family is required")
    for labels in label_families:
        readout_kernel_family(interval, labels)
    return {
        color: {
            point: tuple(labels[color][point] for labels in label_families)
            for point in interval.fibres[color]
        }
        for color in interval.colors
    }


def product_readout_kernel_audit(
    interval: "LocalInterval",
    *label_families: ReadoutLabels,
) -> ProductReadoutKernelAudit:
    """Audit the kernel of a product of finite readout label systems."""

    factor_audits = tuple(
        readout_kernel_audit(interval, labels)
        for labels in label_families
    )
    product_labels = product_readout_labels(interval, *label_families)
    product_audit = readout_kernel_audit(interval, product_labels)
    meet_family = _meet_families(
        interval,
        tuple(audit.family for audit in factor_audits),
    )
    return ProductReadoutKernelAudit(
        factor_audits=factor_audits,
        product_labels=product_labels,
        product_audit=product_audit,
        meet_family=meet_family,
        product_family_is_factor_meet=product_audit.family == meet_family,
    )


def _partition_block_lookup(partition: Partition) -> Dict[FibrePoint, Block]:
    lookup: Dict[FibrePoint, Block] = {}
    for block in partition:
        for point in block:
            lookup[point] = block
    return lookup


def quotient_interval_by_family(
    interval: "LocalInterval",
    family: Mapping[Color, Partition],
) -> "LocalInterval":
    """Return the local interval quotient by an admissible fibre congruence."""

    if not interval.is_admissible_congruence_family(family):
        raise ValueError("family must be an admissible local congruence")
    lookups = {
        color: _partition_block_lookup(family[color])
        for color in interval.colors
    }
    fibres: Dict[Color, Tuple[Block, ...]] = {
        color: tuple(family[color])
        for color in interval.colors
    }
    table = {}
    for a, b in product(interval.colors, repeat=2):
        c, d = interval.base_R[(a, b)]
        for block_x in fibres[a]:
            for block_y in fibres[b]:
                x = next(iter(block_x))
                y = next(iter(block_y))
                u, v = interval.T[(a, b, x, y)]
                table[(a, b, block_x, block_y)] = (
                    lookups[c][u],
                    lookups[d][v],
                )
    return LocalInterval(
        interval.colors,
        fibres,
        interval.base_R,
        table,
    )


def readout_kernel_quotient_interval(
    interval: "LocalInterval",
    labels: ReadoutLabels,
) -> "LocalInterval":
    """Return the quotient interval induced by admissible readout labels."""

    return quotient_interval_by_family(interval, readout_kernel_family(interval, labels))


def _pairs_from_value_fibres(
    domain: Sequence[FibrePoint],
    values_by_input: Mapping[FibrePoint, FibrePoint],
) -> Tuple[Tuple[FibrePoint, FibrePoint], ...]:
    fibres: Dict[FibrePoint, List[FibrePoint]] = {}
    for item in domain:
        fibres.setdefault(values_by_input[item], []).append(item)
    pairs = []
    for block in fibres.values():
        for left in block:
            for right in block:
                if left != right:
                    pairs.append((left, right))
    return tuple(pairs)


def coordinate_kernel_seed_pairs(
    interval: "LocalInterval",
    *,
    include_coretraction_kernels: bool = False,
) -> Dict[Color, Tuple[Tuple[FibrePoint, FibrePoint], ...]]:
    """Return nontrivial coordinate-kernel pairs for a local interval.

    By default this uses the two nondegeneracy coordinate families:
    `y -> pr_1 T(x,y)` and `x -> pr_2 T(x,y)`.  With
    `include_coretraction_kernels=True`, it also includes the dual coordinate
    families `x -> pr_1 T(x,y)` and `y -> pr_2 T(x,y)`.
    """

    pairs: Dict[Color, List[Tuple[FibrePoint, FibrePoint]]] = {
        color: [] for color in interval.colors
    }
    for a, b in product(interval.colors, repeat=2):
        for x in interval.fibres[a]:
            pairs[b].extend(
                _pairs_from_value_fibres(
                    interval.fibres[b],
                    {
                        y: interval.T[(a, b, x, y)][0]
                        for y in interval.fibres[b]
                    },
                )
            )
            if include_coretraction_kernels:
                pairs[b].extend(
                    _pairs_from_value_fibres(
                        interval.fibres[b],
                        {
                            y: interval.T[(a, b, x, y)][1]
                            for y in interval.fibres[b]
                        },
                    )
                )
        for y in interval.fibres[b]:
            pairs[a].extend(
                _pairs_from_value_fibres(
                    interval.fibres[a],
                    {
                        x: interval.T[(a, b, x, y)][1]
                        for x in interval.fibres[a]
                    },
                )
            )
            if include_coretraction_kernels:
                pairs[a].extend(
                    _pairs_from_value_fibres(
                        interval.fibres[a],
                        {
                            x: interval.T[(a, b, x, y)][0]
                            for x in interval.fibres[a]
                        },
                    )
                )
    return {
        color: tuple(sorted(set(color_pairs), key=repr))
        for color, color_pairs in pairs.items()
    }


def generated_admissible_congruence_family(
    interval: "LocalInterval", seed_pairs: PairFamily
) -> Dict[Color, Partition]:
    """Return the least admissible family containing the given seed pairs.

    The closure repeatedly transports related product pairs through every
    coloured bijection `T_{a,b}` and through its inverse.  Since the fibres are
    finite, this reaches the least equivalence-family whose product relations
    are transported exactly by all local tables.
    """

    return dict(generated_admissible_congruence_audit(interval, seed_pairs).family)


def coordinate_kernel_pair_closure_audits(
    interval: "LocalInterval",
    *,
    include_coretraction_kernels: bool = False,
) -> Tuple[CoordinateKernelPairClosureAudit, ...]:
    """Return single-pair closures for coordinate-kernel degeneracies."""

    audits = []
    seed_pairs = coordinate_kernel_seed_pairs(
        interval,
        include_coretraction_kernels=include_coretraction_kernels,
    )
    seen = set()
    for color in interval.colors:
        for left, right in seed_pairs[color]:
            if left == right:
                continue
            key = (color, tuple(sorted((left, right), key=repr)))
            if key in seen:
                continue
            seen.add(key)
            generated = generated_admissible_congruence_audit(
                interval,
                {color: ((left, right),)},
            )
            audits.append(
                CoordinateKernelPairClosureAudit(
                    color=color,
                    left=left,
                    right=right,
                    include_coretraction_kernels=include_coretraction_kernels,
                    generated=generated,
                )
            )
    return tuple(audits)


def coordinate_kernel_pair_closure_failures(
    interval: "LocalInterval",
    *,
    include_coretraction_kernels: bool = False,
) -> Tuple[CoordinateKernelPairClosureAudit, ...]:
    """Return coordinate-kernel pair closures that are not universal."""

    return tuple(
        audit
        for audit in coordinate_kernel_pair_closure_audits(
            interval,
            include_coretraction_kernels=include_coretraction_kernels,
        )
        if audit.generated.kind != "universal"
    )


def continuation_seed_rows(
    interval: "LocalInterval",
) -> Tuple[ContinuationSeedRow, ...]:
    """Return rows where the rack-continuing second output changes state.

    This is meaningful after the base row is in left rack convention, so that
    `base_R(a,b)=(a*b,a)`.  Rows whose second output colour is not `a` are
    reported separately by `continuation_congruence_audit`.
    """

    rows: List[ContinuationSeedRow] = []
    for a, b in product(interval.colors, repeat=2):
        c, d = interval.base_R[(a, b)]
        if d != a:
            continue
        for x in interval.fibres[a]:
            for y in interval.fibres[b]:
                _u, v = interval.T[(a, b, x, y)]
                if v != x:
                    rows.append(
                        ContinuationSeedRow(
                            left_color=a,
                            right_color=b,
                            output_left_color=c,
                            output_right_color=d,
                            left_input=x,
                            right_input=y,
                            continuing_output=v,
                        )
                    )
    return tuple(rows)


def continuation_seed_pairs(
    interval: "LocalInterval",
) -> Dict[Color, Tuple[Tuple[FibrePoint, FibrePoint], ...]]:
    """Return seed pairs `x ~ v` forced by non-strand-continuing outputs."""

    pairs: Dict[Color, set[Tuple[FibrePoint, FibrePoint]]] = {
        color: set() for color in interval.colors
    }
    for row in continuation_seed_rows(interval):
        pairs[row.left_color].add((row.left_input, row.continuing_output))
    return {
        color: tuple(sorted(color_pairs, key=repr))
        for color, color_pairs in pairs.items()
    }


def continuation_congruence_audit(
    interval: "LocalInterval",
) -> ContinuationCongruenceAudit:
    """Audit the continuation-change closure used in descent separation."""

    non_rack_base_rows = tuple(
        (a, b, c, d)
        for a, b in product(interval.colors, repeat=2)
        for c, d in (interval.base_R[(a, b)],)
        if d != a
    )
    seed_rows = continuation_seed_rows(interval)
    generated = generated_admissible_congruence_audit(
        interval,
        continuation_seed_pairs(interval),
    )
    return ContinuationCongruenceAudit(
        seed_rows=seed_rows,
        non_rack_base_rows=non_rack_base_rows,
        generated=generated,
    )


def _is_bijection_to(values: Iterable[FibrePoint], codomain: Sequence[FibrePoint]) -> bool:
    values_tuple = tuple(values)
    return len(values_tuple) == len(codomain) and set(values_tuple) == set(codomain)


def section_unit_row_audits(interval: "LocalInterval") -> Tuple[SectionUnitRowAudit, ...]:
    """Return coordinate-section unit data for every coloured local row."""

    audits: List[SectionUnitRowAudit] = []
    for a, b in product(interval.colors, repeat=2):
        c, d = interval.base_R[(a, b)]
        left_unit_inputs = []
        left_nonunit_inputs = []
        right_unit_inputs = []
        right_nonunit_inputs = []

        for x in interval.fibres[a]:
            values = (
                interval.T[(a, b, x, y)][0]
                for y in interval.fibres[b]
            )
            if _is_bijection_to(values, interval.fibres[c]):
                left_unit_inputs.append(x)
            else:
                left_nonunit_inputs.append(x)

        for y in interval.fibres[b]:
            values = (
                interval.T[(a, b, x, y)][1]
                for x in interval.fibres[a]
            )
            if _is_bijection_to(values, interval.fibres[d]):
                right_unit_inputs.append(y)
            else:
                right_nonunit_inputs.append(y)

        audits.append(
            SectionUnitRowAudit(
                left_color=a,
                right_color=b,
                output_left_color=c,
                output_right_color=d,
                left_unit_inputs=tuple(left_unit_inputs),
                left_nonunit_inputs=tuple(left_nonunit_inputs),
                right_unit_inputs=tuple(right_unit_inputs),
                right_nonunit_inputs=tuple(right_nonunit_inputs),
            )
        )
    return tuple(audits)


def two_sided_unit_collapse_audit(interval: "LocalInterval") -> TwoSidedUnitCollapseAudit:
    """Classify the two-sided-unit collapse split for a local interval."""

    return TwoSidedUnitCollapseAudit(
        colored_ybe=interval.is_colored_ybe(),
        continuation=continuation_congruence_audit(interval),
        row_audits=section_unit_row_audits(interval),
    )


def section_kernel_companion_audit(
    interval: "LocalInterval",
) -> SectionKernelCompanionAudit:
    """Record companion-output recovery for noninjective coordinate sections."""

    rows: List[SectionKernelCompanionRow] = []
    for a, b in product(interval.colors, repeat=2):
        c, d = interval.base_R[(a, b)]

        for x in interval.fibres[a]:
            by_left_output: Dict[FibrePoint, List[Tuple[FibrePoint, FibrePoint]]] = {}
            for y in interval.fibres[b]:
                u, v = interval.T[(a, b, x, y)]
                by_left_output.setdefault(u, []).append((y, v))
            for u, entries in by_left_output.items():
                for (y0, v0), (y1, v1) in combinations(entries, 2):
                    rows.append(
                        SectionKernelCompanionRow(
                            side="left",
                            left_color=a,
                            right_color=b,
                            output_left_color=c,
                            output_right_color=d,
                            fixed_input=x,
                            collapsed_inputs=(y0, y1),
                            common_output=u,
                            companion_outputs=(v0, v1),
                        )
                    )

        for y in interval.fibres[b]:
            by_right_output: Dict[FibrePoint, List[Tuple[FibrePoint, FibrePoint]]] = {}
            for x in interval.fibres[a]:
                u, v = interval.T[(a, b, x, y)]
                by_right_output.setdefault(v, []).append((x, u))
            for v, entries in by_right_output.items():
                for (x0, u0), (x1, u1) in combinations(entries, 2):
                    rows.append(
                        SectionKernelCompanionRow(
                            side="right",
                            left_color=a,
                            right_color=b,
                            output_left_color=c,
                            output_right_color=d,
                            fixed_input=y,
                            collapsed_inputs=(x0, x1),
                            common_output=v,
                            companion_outputs=(u0, u1),
                        )
                    )

    return SectionKernelCompanionAudit(collision_rows=tuple(rows))


def _rank_profile_row(
    *,
    side: str,
    left_color: Color,
    right_color: Color,
    output_left_color: Color,
    output_right_color: Color,
    fixed_input: FibrePoint,
    domain: Sequence[FibrePoint],
    codomain: Sequence[FibrePoint],
    values: Mapping[FibrePoint, FibrePoint],
) -> SectionRankProfileRow:
    by_value: Dict[FibrePoint, List[FibrePoint]] = {}
    for item in domain:
        by_value.setdefault(values[item], []).append(item)
    kernel_blocks = tuple(
        tuple(sorted(block, key=repr))
        for _value, block in sorted(by_value.items(), key=lambda item: repr(item[0]))
    )
    return SectionRankProfileRow(
        side=side,
        left_color=left_color,
        right_color=right_color,
        output_left_color=output_left_color,
        output_right_color=output_right_color,
        fixed_input=fixed_input,
        domain_size=len(domain),
        codomain_size=len(codomain),
        rank=len(by_value),
        kernel_blocks=kernel_blocks,
        image=tuple(sorted(by_value, key=repr)),
    )


def section_rank_profile_collapse_audit(
    interval: "LocalInterval",
) -> SectionRankProfileCollapseAudit:
    """Return rank/kernel profiles for all coordinate sections."""

    rows: List[SectionRankProfileRow] = []
    for a, b in product(interval.colors, repeat=2):
        c, d = interval.base_R[(a, b)]
        for x in interval.fibres[a]:
            rows.append(
                _rank_profile_row(
                    side="left",
                    left_color=a,
                    right_color=b,
                    output_left_color=c,
                    output_right_color=d,
                    fixed_input=x,
                    domain=interval.fibres[b],
                    codomain=interval.fibres[c],
                    values={
                        y: interval.T[(a, b, x, y)][0]
                        for y in interval.fibres[b]
                    },
                )
            )
        for y in interval.fibres[b]:
            rows.append(
                _rank_profile_row(
                    side="right",
                    left_color=a,
                    right_color=b,
                    output_left_color=c,
                    output_right_color=d,
                    fixed_input=y,
                    domain=interval.fibres[a],
                    codomain=interval.fibres[d],
                    values={
                        x: interval.T[(a, b, x, y)][1]
                        for x in interval.fibres[a]
                    },
                )
            )
    return SectionRankProfileCollapseAudit(rows=tuple(rows))


def continuation_seed_pair_closure_audits(
    interval: "LocalInterval",
) -> Tuple[ContinuationSeedPairClosureAudit, ...]:
    """Return single-seed closures for continuation-change pairs.

    In a local-minimal rack-base interval, every nontrivial continuation
    change has either equality closure or universal closure.  Since the seed
    pair itself is nontrivial, equality is impossible, so universal closure is
    the only valid local-minimal outcome.
    """

    rows_by_pair: Dict[Tuple[Color, FibrePoint, FibrePoint], List[ContinuationSeedRow]] = {}
    for row in continuation_seed_rows(interval):
        key = (
            row.left_color,
            *tuple(sorted((row.left_input, row.continuing_output), key=repr)),
        )
        rows_by_pair.setdefault(key, []).append(row)
    audits = []
    for color, left, right in sorted(rows_by_pair, key=repr):
        generated = generated_admissible_congruence_audit(
            interval,
            {color: ((left, right),)},
        )
        audits.append(
            ContinuationSeedPairClosureAudit(
                color=color,
                left=left,
                right=right,
                seed_rows=tuple(rows_by_pair[(color, left, right)]),
                generated=generated,
            )
        )
    return tuple(audits)


def continuation_seed_pair_closure_failures(
    interval: "LocalInterval",
) -> Tuple[ContinuationSeedPairClosureAudit, ...]:
    """Return continuation seed-pair closures that are not universal."""

    return tuple(
        audit
        for audit in continuation_seed_pair_closure_audits(interval)
        if audit.generated.kind != "universal"
    )


def continuation_seed_universal_derivation_audits(
    interval: "LocalInterval",
) -> Tuple[ContinuationSeedUniversalDerivationAudit, ...]:
    """Return derivation coverage for every universal continuation seed.

    The generated-congruence engine records the first transport/inverse
    derivation of every nontrivial edge it creates.  For a universal closure,
    this audit exposes that edge-by-edge certificate so the descent-separation
    proof target can be checked seed-by-seed.
    """

    audits = []
    for seed_closure in continuation_seed_pair_closure_audits(interval):
        edge_counts = dict(seed_closure.generated.edge_count_rows)
        derivation_counts = dict(seed_closure.generated.derivation_count_rows)
        missing = tuple(
            (
                color,
                edge_counts[color] - derivation_counts.get(color, 0),
            )
            for color, _count in seed_closure.generated.edge_count_rows
        )
        audits.append(
            ContinuationSeedUniversalDerivationAudit(
                seed_closure=seed_closure,
                edge_count_rows=seed_closure.generated.edge_count_rows,
                derivation_count_rows=seed_closure.generated.derivation_count_rows,
                missing_derivation_count_rows=missing,
            )
        )
    return tuple(audits)


def continuation_seed_universal_derivation_failures(
    interval: "LocalInterval",
) -> Tuple[ContinuationSeedUniversalDerivationAudit, ...]:
    """Return seed derivation audits that do not certify universal closure."""

    return tuple(
        audit
        for audit in continuation_seed_universal_derivation_audits(interval)
        if not audit.proves_single_seed_universal_derivation
    )


def _family_contains_pair(
    family: Mapping[Color, Partition],
    color: Color,
    left: FibrePoint,
    right: FibrePoint,
) -> bool:
    return same_block(family[color], left, right)


def _missing_family_edges(
    contained: Mapping[Color, Partition],
    container: Mapping[Color, Partition],
) -> Tuple[Tuple[Color, FibrePoint, FibrePoint], ...]:
    missing: List[Tuple[Color, FibrePoint, FibrePoint]] = []
    for color in contained:
        for left, right in partition_pairs(contained[color]):
            if left == right:
                continue
            edge = tuple(sorted((left, right), key=repr))
            if not _family_contains_pair(container, color, edge[0], edge[1]):
                missing.append((color, edge[0], edge[1]))
    return tuple(sorted(set(missing), key=repr))


def continuation_seed_readout_propagation_audit(
    interval: "LocalInterval",
    seed_closure: ContinuationSeedPairClosureAudit,
    readout_family: Mapping[Color, Partition],
) -> ContinuationSeedReadoutPropagationAudit:
    """Check whether an admissible readout contains a seed's full closure.

    The proof use is minimality: the generated closure is the least admissible
    family containing the seed.  Therefore any admissible readout relation that
    contains the seed must contain every generated edge.  The audit records the
    containment directly, so proof notes and tests can expose failures without
    relying on a hidden enumeration argument.
    """

    seed_contained = _family_contains_pair(
        readout_family,
        seed_closure.color,
        seed_closure.left,
        seed_closure.right,
    )
    missing = _missing_family_edges(seed_closure.generated.family, readout_family)
    return ContinuationSeedReadoutPropagationAudit(
        seed_closure=seed_closure,
        readout_family=readout_family,
        readout_kind=relation_family_kind(interval, readout_family),
        readout_is_admissible=interval.is_admissible_congruence_family(readout_family),
        seed_contained=seed_contained,
        generated_contained=not missing,
        missing_generated_edges=missing,
    )


def continuation_seed_readout_propagation_audits(
    interval: "LocalInterval",
    readout_family: Mapping[Color, Partition],
) -> Tuple[ContinuationSeedReadoutPropagationAudit, ...]:
    """Apply the readout-propagation check to every continuation seed closure."""

    return tuple(
        continuation_seed_readout_propagation_audit(
            interval,
            seed_closure,
            readout_family,
        )
        for seed_closure in continuation_seed_pair_closure_audits(interval)
    )


def continuation_seed_readout_propagation_failures(
    interval: "LocalInterval",
    readout_family: Mapping[Color, Partition],
) -> Tuple[ContinuationSeedReadoutPropagationAudit, ...]:
    """Return continuation seed closures not certified by this readout."""

    return tuple(
        audit
        for audit in continuation_seed_readout_propagation_audits(
            interval,
            readout_family,
        )
        if not audit.proves_readout_propagation
    )


def readout_descent_separation_audit(
    interval: "LocalInterval",
    labels: ReadoutLabels,
) -> ReadoutDescentSeparationAudit:
    """Certify when finite readout labels make the quotient strand-continuing."""

    readout_kernel = readout_kernel_audit(interval, labels)
    continuation = continuation_congruence_audit(interval)
    propagation_audits = continuation_seed_readout_propagation_audits(
        interval,
        readout_kernel.family,
    )
    surviving_rows = tuple(
        row
        for row in continuation.seed_rows
        if not same_block(
            readout_kernel.family[row.left_color],
            row.left_input,
            row.continuing_output,
        )
    )
    quotient_interval = None
    quotient_continuation = None
    if readout_kernel.admissible:
        quotient_interval = quotient_interval_by_family(interval, readout_kernel.family)
        quotient_continuation = continuation_congruence_audit(quotient_interval)
    return ReadoutDescentSeparationAudit(
        readout_kernel=readout_kernel,
        continuation=continuation,
        propagation_audits=propagation_audits,
        surviving_seed_rows=surviving_rows,
        quotient_interval=quotient_interval,
        quotient_continuation=quotient_continuation,
    )


def readout_descent_separation_failures(
    interval: "LocalInterval",
    labels: ReadoutLabels,
) -> Tuple[ContinuationSeedRow, ...]:
    """Return continuation seed rows that survive this readout quotient."""

    return readout_descent_separation_audit(interval, labels).surviving_seed_rows


def _sorted_seed_rows(
    rows: Iterable[ContinuationSeedRow],
) -> Tuple[ContinuationSeedRow, ...]:
    return tuple(sorted(set(rows), key=repr))


def product_readout_descent_separation_audit(
    interval: "LocalInterval",
    *label_families: ReadoutLabels,
) -> ProductReadoutDescentSeparationAudit:
    """Audit descent separation for a tuple-valued product readout.

    A continuation seed survives the product kernel exactly when it survives
    at least one factor kernel, because the product kernel is the meet of the
    factor kernels.
    """

    product_kernel = product_readout_kernel_audit(interval, *label_families)
    descent = readout_descent_separation_audit(
        interval,
        product_kernel.product_labels,
    )
    factor_surviving_seed_rows = tuple(
        (index, readout_descent_separation_failures(interval, labels))
        for index, labels in enumerate(label_families)
    )
    factor_survival_union = _sorted_seed_rows(
        row
        for _index, rows in factor_surviving_seed_rows
        for row in rows
    )
    return ProductReadoutDescentSeparationAudit(
        product_kernel=product_kernel,
        descent=descent,
        factor_surviving_seed_rows=factor_surviving_seed_rows,
        product_surviving_seed_rows=descent.surviving_seed_rows,
        factor_survival_union=factor_survival_union,
        product_survival_is_factor_union=(
            set(descent.surviving_seed_rows) == set(factor_survival_union)
        ),
    )


def product_readout_descent_separation_failures(
    interval: "LocalInterval",
    *label_families: ReadoutLabels,
) -> Tuple[ContinuationSeedRow, ...]:
    """Return seed rows that survive a tuple-valued product readout."""

    return product_readout_descent_separation_audit(
        interval,
        *label_families,
    ).product_surviving_seed_rows


def partition_readout_labels(
    interval: "LocalInterval",
    family: Mapping[Color, Partition],
) -> Dict[Color, Dict[FibrePoint, Block]]:
    """Return labels by equivalence block for a fibre partition family."""

    lookups = {
        color: _partition_block_lookup(family[color])
        for color in interval.colors
    }
    return {
        color: {
            point: lookups[color][point]
            for point in interval.fibres[color]
        }
        for color in interval.colors
    }


def _pair_family_from_partition_family(
    interval: "LocalInterval",
    family: Mapping[Color, Partition],
) -> Dict[Color, Tuple[Tuple[FibrePoint, FibrePoint], ...]]:
    pairs: Dict[Color, set[Tuple[FibrePoint, FibrePoint]]] = {
        color: set() for color in interval.colors
    }
    for color in interval.colors:
        for block in family[color]:
            for left in block:
                for right in block:
                    if left != right:
                        pairs[color].add((left, right))
    return {
        color: tuple(sorted(color_pairs, key=repr))
        for color, color_pairs in pairs.items()
    }


def _merge_pair_families(
    interval: "LocalInterval",
    *families: PairFamily,
) -> Dict[Color, Tuple[Tuple[FibrePoint, FibrePoint], ...]]:
    merged: Dict[Color, set[Tuple[FibrePoint, FibrePoint]]] = {
        color: set() for color in interval.colors
    }
    for family in families:
        for color in interval.colors:
            merged[color].update(family.get(color, ()))
    return {
        color: tuple(sorted(color_pairs, key=repr))
        for color, color_pairs in merged.items()
    }


def readout_seed_saturation_audit(
    interval: "LocalInterval",
    labels: ReadoutLabels,
) -> ReadoutSeedSaturationAudit:
    """Audit the least admissible coarsening that kills continuation seeds."""

    readout_kernel = readout_kernel_audit(interval, labels)
    continuation = continuation_congruence_audit(interval)
    seed_pairs = _merge_pair_families(
        interval,
        _pair_family_from_partition_family(interval, readout_kernel.family),
        continuation_seed_pairs(interval),
    )
    saturation = generated_admissible_congruence_audit(interval, seed_pairs)
    saturated_labels = partition_readout_labels(interval, saturation.family)
    saturated_readout_kernel = readout_kernel_audit(interval, saturated_labels)
    saturated_descent = readout_descent_separation_audit(
        interval,
        saturated_labels,
    )
    return ReadoutSeedSaturationAudit(
        readout_kernel=readout_kernel,
        continuation=continuation,
        saturation=saturation,
        saturated_labels=saturated_labels,
        saturated_readout_kernel=saturated_readout_kernel,
        saturated_descent=saturated_descent,
        original_surviving_seed_rows=readout_descent_separation_failures(
            interval,
            labels,
        ),
        missing_readout_kernel_edges=_missing_family_edges(
            readout_kernel.family,
            saturation.family,
        ),
        new_saturation_edges=_missing_family_edges(
            saturation.family,
            readout_kernel.family,
        ),
    )


def _expected_local_minimal_seed_saturation_kind(
    audit: ReadoutSeedSaturationAudit,
) -> str | None:
    if not audit.readout_kernel.admissible:
        return None
    if audit.readout_kernel.kind == "universal":
        return "universal"
    if audit.readout_kernel.kind == "equality":
        return "universal" if audit.original_surviving_seed_rows else "equality"
    return None


def local_minimal_seed_saturation_dichotomy_audit(
    interval: "LocalInterval",
    labels: ReadoutLabels,
) -> LocalMinimalSeedSaturationDichotomyAudit:
    """Audit the equality/universal seed-saturation dichotomy."""

    seed_saturation = readout_seed_saturation_audit(interval, labels)
    return LocalMinimalSeedSaturationDichotomyAudit(
        seed_saturation=seed_saturation,
        interval_is_local_minimal=interval.is_local_minimal(),
        expected_saturation_kind=_expected_local_minimal_seed_saturation_kind(
            seed_saturation,
        ),
    )


def _labels_distinguish_edge(
    labels: ReadoutLabels,
    color: Color,
    left: FibrePoint,
    right: FibrePoint,
) -> bool:
    return labels[color][left] != labels[color][right]


def lost_edge_external_routing_audit(
    interval: "LocalInterval",
    descent_labels: ReadoutLabels,
    routing_labels: ReadoutLabels,
) -> LostEdgeExternalRoutingAudit:
    """Audit whether external labels distinguish edges lost by saturation.

    The routing labels are a separate ledger.  They are not included as
    descent-quotient factors, since doing so would refine the quotient and may
    make continuation seeds survive again.
    """

    dichotomy = local_minimal_seed_saturation_dichotomy_audit(
        interval,
        descent_labels,
    )
    routing_kernel = readout_kernel_audit(interval, routing_labels)
    lost_edges = dichotomy.seed_saturation.new_saturation_edges
    routed = []
    unrouted = []
    for color, left, right in lost_edges:
        if _labels_distinguish_edge(routing_labels, color, left, right):
            routed.append((color, left, right))
        else:
            unrouted.append((color, left, right))
    return LostEdgeExternalRoutingAudit(
        dichotomy=dichotomy,
        routing_labels=routing_labels,
        routing_kernel=routing_kernel,
        lost_edges=lost_edges,
        routed_edges=tuple(routed),
        unrouted_edges=tuple(unrouted),
    )


def generated_admissible_congruence_audit(
    interval: "LocalInterval", seed_pairs: PairFamily
) -> GeneratedCongruenceAudit:
    """Return closure data for the least admissible generated family."""

    pairs: Dict[Color, set[Tuple[FibrePoint, FibrePoint]]] = {
        color: {(point, point) for point in interval.fibres[color]}
        for color in interval.colors
    }
    graph_edges: Dict[Color, set[Tuple[FibrePoint, FibrePoint]]] = {
        color: set() for color in interval.colors
    }
    derivations: List[GeneratedCongruenceDerivationRow] = []
    seed_pair_count = 0

    def add_pair(
        color: Color,
        left: FibrePoint,
        right: FibrePoint,
        *,
        depth: int,
        source: str,
        crossing: Tuple[Color, Color] | None = None,
        source_pairs: Tuple[Tuple[Color, FibrePoint, FibrePoint], ...] = (),
    ) -> None:
        pairs[color].add((left, right))
        pairs[color].add((right, left))
        if left != right:
            edge = tuple(sorted((left, right), key=repr))
            if edge not in graph_edges[color]:
                graph_edges[color].add(edge)
                derivations.append(
                    GeneratedCongruenceDerivationRow(
                        depth=depth,
                        color=color,
                        left=edge[0],
                        right=edge[1],
                        source=source,
                        crossing=crossing,
                        source_pairs=source_pairs,
                    )
                )

    for color in interval.colors:
        for left, right in seed_pairs.get(color, ()):
            seed_pair_count += 1
            add_pair(color, left, right, depth=0, source="seed")

    inverse_tables = {}
    for a, b in product(interval.colors, repeat=2):
        inverse_tables[(a, b)] = {
            interval.T[(a, b, x, y)]: (x, y)
            for x in interval.fibres[a]
            for y in interval.fibres[b]
        }

    def current_family() -> Dict[Color, Partition]:
        return {
            color: canonical_partition(
                _union_blocks(interval.fibres[color], pairs[color])
            )
            for color in interval.colors
        }

    depth = 0
    while True:
        family = current_family()
        before = {color: frozenset(pairs[color]) for color in interval.colors}
        related = {
            color: partition_pairs(family[color])
            for color in interval.colors
        }
        for a, b in product(interval.colors, repeat=2):
            c, d = interval.base_R[(a, b)]
            for x1, x2 in related[a]:
                for y1, y2 in related[b]:
                    u1, v1 = interval.T[(a, b, x1, y1)]
                    u2, v2 = interval.T[(a, b, x2, y2)]
                    source_pairs = ((a, x1, x2), (b, y1, y2))
                    add_pair(
                        c,
                        u1,
                        u2,
                        depth=depth + 1,
                        source="forward_left",
                        crossing=(a, b),
                        source_pairs=source_pairs,
                    )
                    add_pair(
                        d,
                        v1,
                        v2,
                        depth=depth + 1,
                        source="forward_right",
                        crossing=(a, b),
                        source_pairs=source_pairs,
                    )
            inverse_table = inverse_tables[(a, b)]
            for u1, u2 in related[c]:
                for v1, v2 in related[d]:
                    x1, y1 = inverse_table[(u1, v1)]
                    x2, y2 = inverse_table[(u2, v2)]
                    source_pairs = ((c, u1, u2), (d, v1, v2))
                    add_pair(
                        a,
                        x1,
                        x2,
                        depth=depth + 1,
                        source="inverse_left",
                        crossing=(a, b),
                        source_pairs=source_pairs,
                    )
                    add_pair(
                        b,
                        y1,
                        y2,
                        depth=depth + 1,
                        source="inverse_right",
                        crossing=(a, b),
                        source_pairs=source_pairs,
                    )
        after = {color: frozenset(pairs[color]) for color in interval.colors}
        if after == before:
            final_family = current_family()
            component_counts, diameters = _graph_component_summaries(
                interval,
                graph_edges,
            )
            return GeneratedCongruenceAudit(
                seed_pair_count=seed_pair_count,
                stable_depth=depth,
                family=final_family,
                kind=relation_family_kind(interval, final_family),
                pair_count_rows=tuple(
                    (color, len(partition_pairs(final_family[color])))
                    for color in interval.colors
                ),
                edge_count_rows=tuple(
                    (color, len(graph_edges[color]))
                    for color in interval.colors
                ),
                component_count_rows=tuple(
                    (color, component_counts[color])
                    for color in interval.colors
                ),
                diameter_rows=tuple(
                    (color, diameters[color])
                    for color in interval.colors
                ),
                derivation_rows=tuple(derivations),
            )
        depth += 1


def _graph_component_summaries(
    interval: "LocalInterval",
    graph_edges: Mapping[Color, Iterable[Tuple[FibrePoint, FibrePoint]]],
) -> Tuple[Dict[Color, int], Dict[Color, int]]:
    component_counts = {}
    diameters = {}
    for color in interval.colors:
        adjacency = {point: set() for point in interval.fibres[color]}
        for left, right in graph_edges[color]:
            adjacency[left].add(right)
            adjacency[right].add(left)
        unseen = set(interval.fibres[color])
        component_count = 0
        max_diameter = 0
        while unseen:
            component_count += 1
            start = next(iter(unseen))
            stack = [start]
            component = set()
            while stack:
                current = stack.pop()
                if current in component:
                    continue
                component.add(current)
                unseen.discard(current)
                stack.extend(adjacency[current] - component)
            for source in component:
                distances = _graph_distances(adjacency, source)
                max_diameter = max(
                    max_diameter,
                    max(distances[target] for target in component),
                )
        component_counts[color] = component_count
        diameters[color] = max_diameter
    return component_counts, diameters


def _graph_distances(
    adjacency: Mapping[FibrePoint, set[FibrePoint]],
    source: FibrePoint,
) -> Dict[FibrePoint, int]:
    distances = {source: 0}
    queue = [source]
    cursor = 0
    while cursor < len(queue):
        current = queue[cursor]
        cursor += 1
        for neighbour in adjacency[current]:
            if neighbour in distances:
                continue
            distances[neighbour] = distances[current] + 1
            queue.append(neighbour)
    return distances


def _union_blocks(
    items: Sequence[FibrePoint],
    related_pairs: Iterable[Tuple[FibrePoint, FibrePoint]],
) -> Tuple[Tuple[FibrePoint, ...], ...]:
    parent = {item: item for item in items}

    def find(item):
        while parent[item] != item:
            parent[item] = parent[parent[item]]
            item = parent[item]
        return item

    def union(left, right) -> None:
        root_left = find(left)
        root_right = find(right)
        if root_left != root_right:
            parent[root_right] = root_left

    for left, right in related_pairs:
        union(left, right)
    blocks: Dict[FibrePoint, List[FibrePoint]] = {}
    for item in items:
        blocks.setdefault(find(item), []).append(item)
    return tuple(tuple(block) for block in blocks.values())


@dataclass(frozen=True)
class LocalInterval:
    """A coloured local extension table over a quotient braided set."""

    colors: Tuple[Color, ...]
    fibres: Mapping[Color, Tuple[FibrePoint, ...]]
    base_R: Mapping[Tuple[Color, Color], Tuple[Color, Color]]
    T: Mapping[Tuple[Color, Color, FibrePoint, FibrePoint], Tuple[FibrePoint, FibrePoint]]

    def __post_init__(self) -> None:
        object.__setattr__(self, "colors", tuple(self.colors))
        for color in self.colors:
            if color not in self.fibres:
                raise ValueError(f"missing fibre for color {color!r}")
        self.validate_base_bijection()
        self.validate_fibre_bijections()

    def validate_base_bijection(self) -> None:
        domain = {(a, b) for a in self.colors for b in self.colors}
        image = set(self.base_R.values())
        if set(self.base_R.keys()) != domain:
            raise ValueError("base_R domain must be colors x colors")
        if image != domain or len(image) != len(domain):
            raise ValueError("base_R must be a bijection on colors x colors")

    def validate_fibre_bijections(self) -> None:
        for a, b in product(self.colors, repeat=2):
            c, d = self.base_R[(a, b)]
            domain = {(x, y) for x in self.fibres[a] for y in self.fibres[b]}
            image_domain = {(x, y) for x in self.fibres[c] for y in self.fibres[d]}
            keys = {(x, y) for aa, bb, x, y in self.T if aa == a and bb == b}
            image = {self.T[(a, b, x, y)] for x, y in domain}
            if keys != domain:
                raise ValueError(f"T_{{{a},{b}}} domain mismatch")
            if image != image_domain or len(image) != len(image_domain):
                raise ValueError(f"T_{{{a},{b}}} must be a bijection")

    def apply_T_at(
        self,
        color_tuple: Sequence[Color],
        fibre_tuple: Sequence[FibrePoint],
        index: int,
    ) -> Tuple[Tuple[Color, ...], Tuple[FibrePoint, ...]]:
        colors = list(color_tuple)
        fibres = list(fibre_tuple)
        a, b = colors[index], colors[index + 1]
        x, y = fibres[index], fibres[index + 1]
        c, d = self.base_R[(a, b)]
        u, v = self.T[(a, b, x, y)]
        colors[index], colors[index + 1] = c, d
        fibres[index], fibres[index + 1] = u, v
        return tuple(colors), tuple(fibres)

    def is_colored_ybe(self) -> bool:
        return not self.colored_ybe_failures()

    def colored_ybe_failures(self) -> List[Tuple[Tuple[Color, ...], Tuple[FibrePoint, ...]]]:
        failures = []
        for a, b, c in product(self.colors, repeat=3):
            for x, y, z in product(self.fibres[a], self.fibres[b], self.fibres[c]):
                left_c, left_f = (a, b, c), (x, y, z)
                for index in (0, 1, 0):
                    left_c, left_f = self.apply_T_at(left_c, left_f, index)
                right_c, right_f = (a, b, c), (x, y, z)
                for index in (1, 0, 1):
                    right_c, right_f = self.apply_T_at(right_c, right_f, index)
                if (left_c, left_f) != (right_c, right_f):
                    failures.append(((a, b, c), (x, y, z)))
        return failures

    def product_relation(
        self,
        a: Color,
        b: Color,
        theta_a: Partition,
        theta_b: Partition,
    ) -> FrozenSet[Tuple[Tuple[FibrePoint, FibrePoint], Tuple[FibrePoint, FibrePoint]]]:
        related = set()
        for x1, y1, x2, y2 in product(
            self.fibres[a], self.fibres[b], self.fibres[a], self.fibres[b]
        ):
            if same_block(theta_a, x1, x2) and same_block(theta_b, y1, y2):
                related.add(((x1, y1), (x2, y2)))
        return frozenset(related)

    def transports_congruence_pair(
        self,
        a: Color,
        b: Color,
        theta_a: Partition,
        theta_b: Partition,
        theta_c: Partition,
        theta_d: Partition,
    ) -> bool:
        c, d = self.base_R[(a, b)]
        source_relation = self.product_relation(a, b, theta_a, theta_b)
        transported = frozenset(
            (
                self.T[(a, b, p[0], p[1])],
                self.T[(a, b, q[0], q[1])],
            )
            for p, q in source_relation
        )
        target_relation = self.product_relation(c, d, theta_c, theta_d)
        return transported == target_relation

    def transport_failure(
        self,
        a: Color,
        b: Color,
        theta_a: Partition,
        theta_b: Partition,
        theta_c: Partition,
        theta_d: Partition,
    ) -> TransportFailure | None:
        c, d = self.base_R[(a, b)]
        source_relation = self.product_relation(a, b, theta_a, theta_b)
        transported = frozenset(
            (
                self.T[(a, b, p[0], p[1])],
                self.T[(a, b, q[0], q[1])],
            )
            for p, q in source_relation
        )
        target_relation = self.product_relation(c, d, theta_c, theta_d)
        extra = sorted(transported - target_relation, key=repr)
        if extra:
            return TransportFailure(a, b, c, d, "transported_not_target", extra[0])
        missing = sorted(target_relation - transported, key=repr)
        if missing:
            return TransportFailure(a, b, c, d, "target_not_transported", missing[0])
        return None

    def is_admissible_congruence_family(self, family: Mapping[Color, Partition]) -> bool:
        for a, b in product(self.colors, repeat=2):
            c, d = self.base_R[(a, b)]
            if not self.transports_congruence_pair(
                a, b, family[a], family[b], family[c], family[d]
            ):
                return False
        return True

    def congruence_family_failure(
        self, family: Mapping[Color, Partition]
    ) -> TransportFailure | None:
        for a, b in product(self.colors, repeat=2):
            c, d = self.base_R[(a, b)]
            failure = self.transport_failure(
                a, b, family[a], family[b], family[c], family[d]
            )
            if failure is not None:
                return failure
        return None

    def semisplit_audits(self) -> List[SemisplitAudit]:
        """Audit all equality/universal mixtures, excluding extremes."""

        choices = []
        for color in self.colors:
            choices.append(
                [
                    equality_partition(self.fibres[color]),
                    universal_partition(self.fibres[color]),
                ]
            )
        all_equal = {c: equality_partition(self.fibres[c]) for c in self.colors}
        all_universal = {c: universal_partition(self.fibres[c]) for c in self.colors}
        audits = []
        seen = set()
        for parts in product(*choices):
            family = dict(zip(self.colors, parts))
            key = tuple((color, family[color]) for color in self.colors)
            if key in seen:
                continue
            seen.add(key)
            if family == all_equal or family == all_universal:
                continue
            failure = self.congruence_family_failure(family)
            audits.append(
                SemisplitAudit(
                    universal_colors=tuple(
                        color
                        for color in self.colors
                        if family[color] == universal_partition(self.fibres[color])
                    ),
                    family=family,
                    admissible=failure is None,
                    failure=failure,
                )
            )
        return audits

    def semisplit_families(self) -> List[Dict[Color, Partition]]:
        """Return admissible equality/universal mixtures, excluding extremes."""

        return [dict(audit.family) for audit in self.semisplit_audits() if audit.admissible]

    def _semisplit_partition(self, color: Color, bit: int) -> Partition:
        if bit == 0:
            return equality_partition(self.fibres[color])
        if bit == 1:
            return universal_partition(self.fibres[color])
        raise ValueError("semisplit bits must be 0 or 1")

    def semisplit_constraint_rows(self) -> List[SemisplitConstraintRow]:
        """Return exact Boolean constraints for equality/universal families.

        For each colour pair `(a,b)` with target `(c,d)`, the allowed patterns
        list exactly those equality/universal choices for
        `(a,b,c,d)` for which `T_{a,b}` transports the source product relation
        onto the target product relation.
        """

        rows = []
        for a, b in product(self.colors, repeat=2):
            c, d = self.base_R[(a, b)]
            allowed = []
            for source_a, source_b, target_c, target_d in product((0, 1), repeat=4):
                if self.transports_congruence_pair(
                    a,
                    b,
                    self._semisplit_partition(a, source_a),
                    self._semisplit_partition(b, source_b),
                    self._semisplit_partition(c, target_c),
                    self._semisplit_partition(d, target_d),
                ):
                    allowed.append((source_a, source_b, target_c, target_d))
            rows.append(
                SemisplitConstraintRow(
                    a=a,
                    b=b,
                    c=c,
                    d=d,
                    allowed_patterns=tuple(allowed),
                )
            )
        return rows

    def semisplit_boolean_assignments(self) -> List[Dict[Color, int]]:
        """Return admissible non-extreme equality/universal bit assignments."""

        rows = self.semisplit_constraint_rows()
        all_equal = {c: equality_partition(self.fibres[c]) for c in self.colors}
        all_universal = {c: universal_partition(self.fibres[c]) for c in self.colors}
        assignments = []
        seen_families = set()
        for bits in product((0, 1), repeat=len(self.colors)):
            assignment = dict(zip(self.colors, bits))
            if any(
                (
                    assignment[row.a],
                    assignment[row.b],
                    assignment[row.c],
                    assignment[row.d],
                )
                not in row.allowed_patterns
                for row in rows
            ):
                continue
            family = {
                color: self._semisplit_partition(color, assignment[color])
                for color in self.colors
            }
            if family == all_equal or family == all_universal:
                continue
            key = tuple((color, family[color]) for color in self.colors)
            if key in seen_families:
                continue
            seen_families.add(key)
            assignments.append(assignment)
        return assignments

    def pair_generated_local_minimality_audits(
        self,
    ) -> List[PairGeneratedLocalMinimalityAudit]:
        """Return exact single-pair generation audits for local-minimality.

        A finite interval is local-minimal iff every distinct pair inside a
        fibre generates the all-universal admissible relation family.  Indeed,
        any non-equality admissible family contains such a pair, and the least
        admissible family generated by that pair is contained in it.
        """

        audits = []
        for color in self.colors:
            points = self.fibres[color]
            for left_index, left in enumerate(points):
                for right in points[left_index + 1 :]:
                    generated = generated_admissible_congruence_audit(
                        self,
                        {color: ((left, right),)},
                    )
                    audits.append(
                        PairGeneratedLocalMinimalityAudit(
                            color=color,
                            left=left,
                            right=right,
                            generated=generated,
                        )
                    )
        return audits

    def pair_generated_local_minimality_failures(
        self,
    ) -> List[PairGeneratedLocalMinimalityAudit]:
        """Return pair closures that witness failure of local-minimality."""

        return [
            audit
            for audit in self.pair_generated_local_minimality_audits()
            if audit.generated.kind != "universal"
        ]

    def admissible_congruence_families(self, max_fibre_size: int = 5) -> List[Dict[Color, Partition]]:
        """Enumerate all admissible families for small fibres."""

        if any(len(self.fibres[color]) > max_fibre_size for color in self.colors):
            raise ValueError("full partition enumeration disabled for this fibre size")
        per_color = [set_partitions(self.fibres[color]) for color in self.colors]
        out = []
        for parts in product(*per_color):
            family = dict(zip(self.colors, parts))
            if self.is_admissible_congruence_family(family):
                out.append(family)
        return out

    def is_local_minimal(self, max_fibre_size: int = 5) -> bool:
        """Return the exact local-minimality verdict.

        The `max_fibre_size` argument is retained for compatibility with the
        older partition-enumeration checker.  The current criterion uses
        single-pair admissible closures and has no Bell-number fibre-size
        guard.
        """

        return not self.pair_generated_local_minimality_failures()
