from __future__ import annotations

from dataclasses import dataclass
from itertools import product
from typing import Dict, FrozenSet, Hashable, Iterable, List, Mapping, Sequence, Tuple

Color = Hashable
FibrePoint = Hashable
Block = FrozenSet[FibrePoint]
Partition = Tuple[Block, ...]
PairFamily = Mapping[Color, Iterable[Tuple[FibrePoint, FibrePoint]]]


@dataclass(frozen=True)
class TransportFailure:
    a: Color
    b: Color
    c: Color
    d: Color
    side: str
    witness: Tuple[Tuple[FibrePoint, FibrePoint], Tuple[FibrePoint, FibrePoint]]


@dataclass(frozen=True)
class SemisplitAudit:
    universal_colors: Tuple[Color, ...]
    family: Mapping[Color, Partition]
    admissible: bool
    failure: TransportFailure | None


@dataclass(frozen=True)
class SemisplitConstraintRow:
    """Allowed equality/universal bit patterns for one coloured crossing.

    Patterns are ordered as `(source_a, source_b, target_c, target_d)`, where
    `0` means equality on that fibre and `1` means universal.
    """

    a: Color
    b: Color
    c: Color
    d: Color
    allowed_patterns: Tuple[Tuple[int, int, int, int], ...]


@dataclass(frozen=True)
class GeneratedCongruenceDerivationRow:
    """First derivation of one nontrivial relation edge in a closure audit."""

    depth: int
    color: Color
    left: FibrePoint
    right: FibrePoint
    source: str
    crossing: Tuple[Color, Color] | None
    source_pairs: Tuple[Tuple[Color, FibrePoint, FibrePoint], ...]


@dataclass(frozen=True)
class GeneratedCongruenceAudit:
    seed_pair_count: int
    stable_depth: int
    family: Mapping[Color, Partition]
    kind: str
    pair_count_rows: Tuple[Tuple[Color, int], ...]
    edge_count_rows: Tuple[Tuple[Color, int], ...]
    component_count_rows: Tuple[Tuple[Color, int], ...]
    diameter_rows: Tuple[Tuple[Color, int], ...]
    derivation_rows: Tuple[GeneratedCongruenceDerivationRow, ...] = ()

    @property
    def derivation_count_rows(self) -> Tuple[Tuple[Color, int], ...]:
        return tuple(
            (color, sum(1 for row in self.derivation_rows if row.color == color))
            for color, _count in self.edge_count_rows
        )


@dataclass(frozen=True)
class PairGeneratedLocalMinimalityAudit:
    """Least admissible family generated by one nontrivial fibre pair."""

    color: Color
    left: FibrePoint
    right: FibrePoint
    generated: GeneratedCongruenceAudit


@dataclass(frozen=True)
class CoordinateKernelPairClosureAudit:
    """Least admissible family generated by one coordinate-kernel pair."""

    color: Color
    left: FibrePoint
    right: FibrePoint
    include_coretraction_kernels: bool
    generated: GeneratedCongruenceAudit


@dataclass(frozen=True)
class ContinuationSeedRow:
    """One second-output change of the strand-continuing coordinate."""

    left_color: Color
    right_color: Color
    output_left_color: Color
    output_right_color: Color
    left_input: FibrePoint
    right_input: FibrePoint
    continuing_output: FibrePoint


@dataclass(frozen=True)
class ContinuationCongruenceAudit:
    """Least admissible closure of all strand-continuation changes."""

    seed_rows: Tuple[ContinuationSeedRow, ...]
    non_rack_base_rows: Tuple[Tuple[Color, Color, Color, Color], ...]
    generated: GeneratedCongruenceAudit

    @property
    def nontrivial_seed_count(self) -> int:
        return len(self.seed_rows)

    @property
    def base_rows_are_left_rack_form(self) -> bool:
        return not self.non_rack_base_rows

    @property
    def is_strand_continuing_on_the_nose(self) -> bool:
        return self.base_rows_are_left_rack_form and not self.seed_rows

    @property
    def continuation_closure_is_universal(self) -> bool:
        return self.generated.kind == "universal"

    @property
    def continuation_closure_is_proper(self) -> bool:
        return self.generated.kind not in ("equality", "universal")

    @property
    def proves_transport_or_universal_dichotomy(self) -> bool:
        return self.base_rows_are_left_rack_form and (
            self.is_strand_continuing_on_the_nose
            or self.continuation_closure_is_universal
        )


@dataclass(frozen=True)
class ContinuationSeedPairClosureAudit:
    """Least admissible closure generated by one continuation-change pair."""

    color: Color
    left: FibrePoint
    right: FibrePoint
    seed_rows: Tuple[ContinuationSeedRow, ...]
    generated: GeneratedCongruenceAudit


@dataclass(frozen=True)
class ContinuationSeedUniversalDerivationAudit:
    """Derivation coverage of a single continuation seed's universal closure."""

    seed_closure: ContinuationSeedPairClosureAudit
    edge_count_rows: Tuple[Tuple[Color, int], ...]
    derivation_count_rows: Tuple[Tuple[Color, int], ...]
    missing_derivation_count_rows: Tuple[Tuple[Color, int], ...]

    @property
    def closure_is_universal(self) -> bool:
        return self.seed_closure.generated.kind == "universal"

    @property
    def every_edge_has_derivation(self) -> bool:
        return all(count == 0 for _color, count in self.missing_derivation_count_rows)

    @property
    def proves_single_seed_universal_derivation(self) -> bool:
        return self.closure_is_universal and self.every_edge_has_derivation


def equality_partition(items: Sequence[FibrePoint]) -> Partition:
    return canonical_partition(frozenset([item]) for item in items)


def universal_partition(items: Sequence[FibrePoint]) -> Partition:
    return (frozenset(items),)


def canonical_partition(blocks: Iterable[Iterable[FibrePoint]]) -> Partition:
    frozen = [frozenset(block) for block in blocks if block]
    return tuple(
        sorted(frozen, key=lambda block: (len(block), tuple(sorted(map(repr, block)))))
    )


def same_block(partition: Partition, a: FibrePoint, b: FibrePoint) -> bool:
    return any(a in block and b in block for block in partition)


def partition_pairs(partition: Partition) -> FrozenSet[Tuple[FibrePoint, FibrePoint]]:
    pairs = set()
    for block in partition:
        for left in block:
            for right in block:
                pairs.add((left, right))
    return frozenset(pairs)


def set_partitions(items: Sequence[FibrePoint]) -> List[Partition]:
    """Enumerate set partitions. Suitable only for small audit examples."""

    ordered = list(items)
    if not ordered:
        return [tuple()]
    first, rest = ordered[0], ordered[1:]
    if not rest:
        return [(frozenset([first]),)]
    out: List[Partition] = []
    for partition in set_partitions(rest):
        out.append(canonical_partition([frozenset([first]), *partition]))
        for i, block in enumerate(partition):
            new_blocks = list(partition)
            new_blocks[i] = block.union([first])
            out.append(canonical_partition(new_blocks))
    unique = []
    seen = set()
    for partition in out:
        if partition not in seen:
            seen.add(partition)
            unique.append(partition)
    return unique


def relation_family_kind(
    interval: "LocalInterval", family: Mapping[Color, Partition]
) -> str:
    equality = all(len(family[color]) == len(interval.fibres[color]) for color in interval.colors)
    universal = all(
        family[color] == universal_partition(interval.fibres[color])
        for color in interval.colors
    )
    if equality:
        return "equality"
    if universal:
        return "universal"
    if any(family[color] == universal_partition(interval.fibres[color]) for color in interval.colors):
        return "semisplit_or_mixed"
    return "proper_mixed"


def _pairs_from_value_fibres(
    domain: Sequence[FibrePoint],
    values_by_input: Mapping[FibrePoint, FibrePoint],
) -> Tuple[Tuple[FibrePoint, FibrePoint], ...]:
    fibres: Dict[FibrePoint, List[FibrePoint]] = {}
    for item in domain:
        fibres.setdefault(values_by_input[item], []).append(item)
    pairs = []
    for block in fibres.values():
        for left in block:
            for right in block:
                if left != right:
                    pairs.append((left, right))
    return tuple(pairs)


def coordinate_kernel_seed_pairs(
    interval: "LocalInterval",
    *,
    include_coretraction_kernels: bool = False,
) -> Dict[Color, Tuple[Tuple[FibrePoint, FibrePoint], ...]]:
    """Return nontrivial coordinate-kernel pairs for a local interval.

    By default this uses the two nondegeneracy coordinate families:
    `y -> pr_1 T(x,y)` and `x -> pr_2 T(x,y)`.  With
    `include_coretraction_kernels=True`, it also includes the dual coordinate
    families `x -> pr_1 T(x,y)` and `y -> pr_2 T(x,y)`.
    """

    pairs: Dict[Color, List[Tuple[FibrePoint, FibrePoint]]] = {
        color: [] for color in interval.colors
    }
    for a, b in product(interval.colors, repeat=2):
        for x in interval.fibres[a]:
            pairs[b].extend(
                _pairs_from_value_fibres(
                    interval.fibres[b],
                    {
                        y: interval.T[(a, b, x, y)][0]
                        for y in interval.fibres[b]
                    },
                )
            )
            if include_coretraction_kernels:
                pairs[b].extend(
                    _pairs_from_value_fibres(
                        interval.fibres[b],
                        {
                            y: interval.T[(a, b, x, y)][1]
                            for y in interval.fibres[b]
                        },
                    )
                )
        for y in interval.fibres[b]:
            pairs[a].extend(
                _pairs_from_value_fibres(
                    interval.fibres[a],
                    {
                        x: interval.T[(a, b, x, y)][1]
                        for x in interval.fibres[a]
                    },
                )
            )
            if include_coretraction_kernels:
                pairs[a].extend(
                    _pairs_from_value_fibres(
                        interval.fibres[a],
                        {
                            x: interval.T[(a, b, x, y)][0]
                            for x in interval.fibres[a]
                        },
                    )
                )
    return {
        color: tuple(sorted(set(color_pairs), key=repr))
        for color, color_pairs in pairs.items()
    }


def generated_admissible_congruence_family(
    interval: "LocalInterval", seed_pairs: PairFamily
) -> Dict[Color, Partition]:
    """Return the least admissible family containing the given seed pairs.

    The closure repeatedly transports related product pairs through every
    coloured bijection `T_{a,b}` and through its inverse.  Since the fibres are
    finite, this reaches the least equivalence-family whose product relations
    are transported exactly by all local tables.
    """

    return dict(generated_admissible_congruence_audit(interval, seed_pairs).family)


def coordinate_kernel_pair_closure_audits(
    interval: "LocalInterval",
    *,
    include_coretraction_kernels: bool = False,
) -> Tuple[CoordinateKernelPairClosureAudit, ...]:
    """Return single-pair closures for coordinate-kernel degeneracies."""

    audits = []
    seed_pairs = coordinate_kernel_seed_pairs(
        interval,
        include_coretraction_kernels=include_coretraction_kernels,
    )
    seen = set()
    for color in interval.colors:
        for left, right in seed_pairs[color]:
            if left == right:
                continue
            key = (color, tuple(sorted((left, right), key=repr)))
            if key in seen:
                continue
            seen.add(key)
            generated = generated_admissible_congruence_audit(
                interval,
                {color: ((left, right),)},
            )
            audits.append(
                CoordinateKernelPairClosureAudit(
                    color=color,
                    left=left,
                    right=right,
                    include_coretraction_kernels=include_coretraction_kernels,
                    generated=generated,
                )
            )
    return tuple(audits)


def coordinate_kernel_pair_closure_failures(
    interval: "LocalInterval",
    *,
    include_coretraction_kernels: bool = False,
) -> Tuple[CoordinateKernelPairClosureAudit, ...]:
    """Return coordinate-kernel pair closures that are not universal."""

    return tuple(
        audit
        for audit in coordinate_kernel_pair_closure_audits(
            interval,
            include_coretraction_kernels=include_coretraction_kernels,
        )
        if audit.generated.kind != "universal"
    )


def continuation_seed_rows(
    interval: "LocalInterval",
) -> Tuple[ContinuationSeedRow, ...]:
    """Return rows where the rack-continuing second output changes state.

    This is meaningful after the base row is in left rack convention, so that
    `base_R(a,b)=(a*b,a)`.  Rows whose second output colour is not `a` are
    reported separately by `continuation_congruence_audit`.
    """

    rows: List[ContinuationSeedRow] = []
    for a, b in product(interval.colors, repeat=2):
        c, d = interval.base_R[(a, b)]
        if d != a:
            continue
        for x in interval.fibres[a]:
            for y in interval.fibres[b]:
                _u, v = interval.T[(a, b, x, y)]
                if v != x:
                    rows.append(
                        ContinuationSeedRow(
                            left_color=a,
                            right_color=b,
                            output_left_color=c,
                            output_right_color=d,
                            left_input=x,
                            right_input=y,
                            continuing_output=v,
                        )
                    )
    return tuple(rows)


def continuation_seed_pairs(
    interval: "LocalInterval",
) -> Dict[Color, Tuple[Tuple[FibrePoint, FibrePoint], ...]]:
    """Return seed pairs `x ~ v` forced by non-strand-continuing outputs."""

    pairs: Dict[Color, set[Tuple[FibrePoint, FibrePoint]]] = {
        color: set() for color in interval.colors
    }
    for row in continuation_seed_rows(interval):
        pairs[row.left_color].add((row.left_input, row.continuing_output))
    return {
        color: tuple(sorted(color_pairs, key=repr))
        for color, color_pairs in pairs.items()
    }


def continuation_congruence_audit(
    interval: "LocalInterval",
) -> ContinuationCongruenceAudit:
    """Audit the continuation-change closure used in descent separation."""

    non_rack_base_rows = tuple(
        (a, b, c, d)
        for a, b in product(interval.colors, repeat=2)
        for c, d in (interval.base_R[(a, b)],)
        if d != a
    )
    seed_rows = continuation_seed_rows(interval)
    generated = generated_admissible_congruence_audit(
        interval,
        continuation_seed_pairs(interval),
    )
    return ContinuationCongruenceAudit(
        seed_rows=seed_rows,
        non_rack_base_rows=non_rack_base_rows,
        generated=generated,
    )


def continuation_seed_pair_closure_audits(
    interval: "LocalInterval",
) -> Tuple[ContinuationSeedPairClosureAudit, ...]:
    """Return single-seed closures for continuation-change pairs.

    In a local-minimal rack-base interval, every nontrivial continuation
    change has either equality closure or universal closure.  Since the seed
    pair itself is nontrivial, equality is impossible, so universal closure is
    the only valid local-minimal outcome.
    """

    rows_by_pair: Dict[Tuple[Color, FibrePoint, FibrePoint], List[ContinuationSeedRow]] = {}
    for row in continuation_seed_rows(interval):
        key = (
            row.left_color,
            *tuple(sorted((row.left_input, row.continuing_output), key=repr)),
        )
        rows_by_pair.setdefault(key, []).append(row)
    audits = []
    for color, left, right in sorted(rows_by_pair, key=repr):
        generated = generated_admissible_congruence_audit(
            interval,
            {color: ((left, right),)},
        )
        audits.append(
            ContinuationSeedPairClosureAudit(
                color=color,
                left=left,
                right=right,
                seed_rows=tuple(rows_by_pair[(color, left, right)]),
                generated=generated,
            )
        )
    return tuple(audits)


def continuation_seed_pair_closure_failures(
    interval: "LocalInterval",
) -> Tuple[ContinuationSeedPairClosureAudit, ...]:
    """Return continuation seed-pair closures that are not universal."""

    return tuple(
        audit
        for audit in continuation_seed_pair_closure_audits(interval)
        if audit.generated.kind != "universal"
    )


def continuation_seed_universal_derivation_audits(
    interval: "LocalInterval",
) -> Tuple[ContinuationSeedUniversalDerivationAudit, ...]:
    """Return derivation coverage for every universal continuation seed.

    The generated-congruence engine records the first transport/inverse
    derivation of every nontrivial edge it creates.  For a universal closure,
    this audit exposes that edge-by-edge certificate so the descent-separation
    proof target can be checked seed-by-seed.
    """

    audits = []
    for seed_closure in continuation_seed_pair_closure_audits(interval):
        edge_counts = dict(seed_closure.generated.edge_count_rows)
        derivation_counts = dict(seed_closure.generated.derivation_count_rows)
        missing = tuple(
            (
                color,
                edge_counts[color] - derivation_counts.get(color, 0),
            )
            for color, _count in seed_closure.generated.edge_count_rows
        )
        audits.append(
            ContinuationSeedUniversalDerivationAudit(
                seed_closure=seed_closure,
                edge_count_rows=seed_closure.generated.edge_count_rows,
                derivation_count_rows=seed_closure.generated.derivation_count_rows,
                missing_derivation_count_rows=missing,
            )
        )
    return tuple(audits)


def continuation_seed_universal_derivation_failures(
    interval: "LocalInterval",
) -> Tuple[ContinuationSeedUniversalDerivationAudit, ...]:
    """Return seed derivation audits that do not certify universal closure."""

    return tuple(
        audit
        for audit in continuation_seed_universal_derivation_audits(interval)
        if not audit.proves_single_seed_universal_derivation
    )


def generated_admissible_congruence_audit(
    interval: "LocalInterval", seed_pairs: PairFamily
) -> GeneratedCongruenceAudit:
    """Return closure data for the least admissible generated family."""

    pairs: Dict[Color, set[Tuple[FibrePoint, FibrePoint]]] = {
        color: {(point, point) for point in interval.fibres[color]}
        for color in interval.colors
    }
    graph_edges: Dict[Color, set[Tuple[FibrePoint, FibrePoint]]] = {
        color: set() for color in interval.colors
    }
    derivations: List[GeneratedCongruenceDerivationRow] = []
    seed_pair_count = 0

    def add_pair(
        color: Color,
        left: FibrePoint,
        right: FibrePoint,
        *,
        depth: int,
        source: str,
        crossing: Tuple[Color, Color] | None = None,
        source_pairs: Tuple[Tuple[Color, FibrePoint, FibrePoint], ...] = (),
    ) -> None:
        pairs[color].add((left, right))
        pairs[color].add((right, left))
        if left != right:
            edge = tuple(sorted((left, right), key=repr))
            if edge not in graph_edges[color]:
                graph_edges[color].add(edge)
                derivations.append(
                    GeneratedCongruenceDerivationRow(
                        depth=depth,
                        color=color,
                        left=edge[0],
                        right=edge[1],
                        source=source,
                        crossing=crossing,
                        source_pairs=source_pairs,
                    )
                )

    for color in interval.colors:
        for left, right in seed_pairs.get(color, ()):
            seed_pair_count += 1
            add_pair(color, left, right, depth=0, source="seed")

    inverse_tables = {}
    for a, b in product(interval.colors, repeat=2):
        inverse_tables[(a, b)] = {
            interval.T[(a, b, x, y)]: (x, y)
            for x in interval.fibres[a]
            for y in interval.fibres[b]
        }

    def current_family() -> Dict[Color, Partition]:
        return {
            color: canonical_partition(
                _union_blocks(interval.fibres[color], pairs[color])
            )
            for color in interval.colors
        }

    depth = 0
    while True:
        family = current_family()
        before = {color: frozenset(pairs[color]) for color in interval.colors}
        related = {
            color: partition_pairs(family[color])
            for color in interval.colors
        }
        for a, b in product(interval.colors, repeat=2):
            c, d = interval.base_R[(a, b)]
            for x1, x2 in related[a]:
                for y1, y2 in related[b]:
                    u1, v1 = interval.T[(a, b, x1, y1)]
                    u2, v2 = interval.T[(a, b, x2, y2)]
                    source_pairs = ((a, x1, x2), (b, y1, y2))
                    add_pair(
                        c,
                        u1,
                        u2,
                        depth=depth + 1,
                        source="forward_left",
                        crossing=(a, b),
                        source_pairs=source_pairs,
                    )
                    add_pair(
                        d,
                        v1,
                        v2,
                        depth=depth + 1,
                        source="forward_right",
                        crossing=(a, b),
                        source_pairs=source_pairs,
                    )
            inverse_table = inverse_tables[(a, b)]
            for u1, u2 in related[c]:
                for v1, v2 in related[d]:
                    x1, y1 = inverse_table[(u1, v1)]
                    x2, y2 = inverse_table[(u2, v2)]
                    source_pairs = ((c, u1, u2), (d, v1, v2))
                    add_pair(
                        a,
                        x1,
                        x2,
                        depth=depth + 1,
                        source="inverse_left",
                        crossing=(a, b),
                        source_pairs=source_pairs,
                    )
                    add_pair(
                        b,
                        y1,
                        y2,
                        depth=depth + 1,
                        source="inverse_right",
                        crossing=(a, b),
                        source_pairs=source_pairs,
                    )
        after = {color: frozenset(pairs[color]) for color in interval.colors}
        if after == before:
            final_family = current_family()
            component_counts, diameters = _graph_component_summaries(
                interval,
                graph_edges,
            )
            return GeneratedCongruenceAudit(
                seed_pair_count=seed_pair_count,
                stable_depth=depth,
                family=final_family,
                kind=relation_family_kind(interval, final_family),
                pair_count_rows=tuple(
                    (color, len(partition_pairs(final_family[color])))
                    for color in interval.colors
                ),
                edge_count_rows=tuple(
                    (color, len(graph_edges[color]))
                    for color in interval.colors
                ),
                component_count_rows=tuple(
                    (color, component_counts[color])
                    for color in interval.colors
                ),
                diameter_rows=tuple(
                    (color, diameters[color])
                    for color in interval.colors
                ),
                derivation_rows=tuple(derivations),
            )
        depth += 1


def _graph_component_summaries(
    interval: "LocalInterval",
    graph_edges: Mapping[Color, Iterable[Tuple[FibrePoint, FibrePoint]]],
) -> Tuple[Dict[Color, int], Dict[Color, int]]:
    component_counts = {}
    diameters = {}
    for color in interval.colors:
        adjacency = {point: set() for point in interval.fibres[color]}
        for left, right in graph_edges[color]:
            adjacency[left].add(right)
            adjacency[right].add(left)
        unseen = set(interval.fibres[color])
        component_count = 0
        max_diameter = 0
        while unseen:
            component_count += 1
            start = next(iter(unseen))
            stack = [start]
            component = set()
            while stack:
                current = stack.pop()
                if current in component:
                    continue
                component.add(current)
                unseen.discard(current)
                stack.extend(adjacency[current] - component)
            for source in component:
                distances = _graph_distances(adjacency, source)
                max_diameter = max(
                    max_diameter,
                    max(distances[target] for target in component),
                )
        component_counts[color] = component_count
        diameters[color] = max_diameter
    return component_counts, diameters


def _graph_distances(
    adjacency: Mapping[FibrePoint, set[FibrePoint]],
    source: FibrePoint,
) -> Dict[FibrePoint, int]:
    distances = {source: 0}
    queue = [source]
    cursor = 0
    while cursor < len(queue):
        current = queue[cursor]
        cursor += 1
        for neighbour in adjacency[current]:
            if neighbour in distances:
                continue
            distances[neighbour] = distances[current] + 1
            queue.append(neighbour)
    return distances


def _union_blocks(
    items: Sequence[FibrePoint],
    related_pairs: Iterable[Tuple[FibrePoint, FibrePoint]],
) -> Tuple[Tuple[FibrePoint, ...], ...]:
    parent = {item: item for item in items}

    def find(item):
        while parent[item] != item:
            parent[item] = parent[parent[item]]
            item = parent[item]
        return item

    def union(left, right) -> None:
        root_left = find(left)
        root_right = find(right)
        if root_left != root_right:
            parent[root_right] = root_left

    for left, right in related_pairs:
        union(left, right)
    blocks: Dict[FibrePoint, List[FibrePoint]] = {}
    for item in items:
        blocks.setdefault(find(item), []).append(item)
    return tuple(tuple(block) for block in blocks.values())


@dataclass(frozen=True)
class LocalInterval:
    """A coloured local extension table over a quotient braided set."""

    colors: Tuple[Color, ...]
    fibres: Mapping[Color, Tuple[FibrePoint, ...]]
    base_R: Mapping[Tuple[Color, Color], Tuple[Color, Color]]
    T: Mapping[Tuple[Color, Color, FibrePoint, FibrePoint], Tuple[FibrePoint, FibrePoint]]

    def __post_init__(self) -> None:
        object.__setattr__(self, "colors", tuple(self.colors))
        for color in self.colors:
            if color not in self.fibres:
                raise ValueError(f"missing fibre for color {color!r}")
        self.validate_base_bijection()
        self.validate_fibre_bijections()

    def validate_base_bijection(self) -> None:
        domain = {(a, b) for a in self.colors for b in self.colors}
        image = set(self.base_R.values())
        if set(self.base_R.keys()) != domain:
            raise ValueError("base_R domain must be colors x colors")
        if image != domain or len(image) != len(domain):
            raise ValueError("base_R must be a bijection on colors x colors")

    def validate_fibre_bijections(self) -> None:
        for a, b in product(self.colors, repeat=2):
            c, d = self.base_R[(a, b)]
            domain = {(x, y) for x in self.fibres[a] for y in self.fibres[b]}
            image_domain = {(x, y) for x in self.fibres[c] for y in self.fibres[d]}
            keys = {(x, y) for aa, bb, x, y in self.T if aa == a and bb == b}
            image = {self.T[(a, b, x, y)] for x, y in domain}
            if keys != domain:
                raise ValueError(f"T_{{{a},{b}}} domain mismatch")
            if image != image_domain or len(image) != len(image_domain):
                raise ValueError(f"T_{{{a},{b}}} must be a bijection")

    def apply_T_at(
        self,
        color_tuple: Sequence[Color],
        fibre_tuple: Sequence[FibrePoint],
        index: int,
    ) -> Tuple[Tuple[Color, ...], Tuple[FibrePoint, ...]]:
        colors = list(color_tuple)
        fibres = list(fibre_tuple)
        a, b = colors[index], colors[index + 1]
        x, y = fibres[index], fibres[index + 1]
        c, d = self.base_R[(a, b)]
        u, v = self.T[(a, b, x, y)]
        colors[index], colors[index + 1] = c, d
        fibres[index], fibres[index + 1] = u, v
        return tuple(colors), tuple(fibres)

    def is_colored_ybe(self) -> bool:
        return not self.colored_ybe_failures()

    def colored_ybe_failures(self) -> List[Tuple[Tuple[Color, ...], Tuple[FibrePoint, ...]]]:
        failures = []
        for a, b, c in product(self.colors, repeat=3):
            for x, y, z in product(self.fibres[a], self.fibres[b], self.fibres[c]):
                left_c, left_f = (a, b, c), (x, y, z)
                for index in (0, 1, 0):
                    left_c, left_f = self.apply_T_at(left_c, left_f, index)
                right_c, right_f = (a, b, c), (x, y, z)
                for index in (1, 0, 1):
                    right_c, right_f = self.apply_T_at(right_c, right_f, index)
                if (left_c, left_f) != (right_c, right_f):
                    failures.append(((a, b, c), (x, y, z)))
        return failures

    def product_relation(
        self,
        a: Color,
        b: Color,
        theta_a: Partition,
        theta_b: Partition,
    ) -> FrozenSet[Tuple[Tuple[FibrePoint, FibrePoint], Tuple[FibrePoint, FibrePoint]]]:
        related = set()
        for x1, y1, x2, y2 in product(
            self.fibres[a], self.fibres[b], self.fibres[a], self.fibres[b]
        ):
            if same_block(theta_a, x1, x2) and same_block(theta_b, y1, y2):
                related.add(((x1, y1), (x2, y2)))
        return frozenset(related)

    def transports_congruence_pair(
        self,
        a: Color,
        b: Color,
        theta_a: Partition,
        theta_b: Partition,
        theta_c: Partition,
        theta_d: Partition,
    ) -> bool:
        c, d = self.base_R[(a, b)]
        source_relation = self.product_relation(a, b, theta_a, theta_b)
        transported = frozenset(
            (
                self.T[(a, b, p[0], p[1])],
                self.T[(a, b, q[0], q[1])],
            )
            for p, q in source_relation
        )
        target_relation = self.product_relation(c, d, theta_c, theta_d)
        return transported == target_relation

    def transport_failure(
        self,
        a: Color,
        b: Color,
        theta_a: Partition,
        theta_b: Partition,
        theta_c: Partition,
        theta_d: Partition,
    ) -> TransportFailure | None:
        c, d = self.base_R[(a, b)]
        source_relation = self.product_relation(a, b, theta_a, theta_b)
        transported = frozenset(
            (
                self.T[(a, b, p[0], p[1])],
                self.T[(a, b, q[0], q[1])],
            )
            for p, q in source_relation
        )
        target_relation = self.product_relation(c, d, theta_c, theta_d)
        extra = sorted(transported - target_relation, key=repr)
        if extra:
            return TransportFailure(a, b, c, d, "transported_not_target", extra[0])
        missing = sorted(target_relation - transported, key=repr)
        if missing:
            return TransportFailure(a, b, c, d, "target_not_transported", missing[0])
        return None

    def is_admissible_congruence_family(self, family: Mapping[Color, Partition]) -> bool:
        for a, b in product(self.colors, repeat=2):
            c, d = self.base_R[(a, b)]
            if not self.transports_congruence_pair(
                a, b, family[a], family[b], family[c], family[d]
            ):
                return False
        return True

    def congruence_family_failure(
        self, family: Mapping[Color, Partition]
    ) -> TransportFailure | None:
        for a, b in product(self.colors, repeat=2):
            c, d = self.base_R[(a, b)]
            failure = self.transport_failure(
                a, b, family[a], family[b], family[c], family[d]
            )
            if failure is not None:
                return failure
        return None

    def semisplit_audits(self) -> List[SemisplitAudit]:
        """Audit all equality/universal mixtures, excluding extremes."""

        choices = []
        for color in self.colors:
            choices.append(
                [
                    equality_partition(self.fibres[color]),
                    universal_partition(self.fibres[color]),
                ]
            )
        all_equal = {c: equality_partition(self.fibres[c]) for c in self.colors}
        all_universal = {c: universal_partition(self.fibres[c]) for c in self.colors}
        audits = []
        seen = set()
        for parts in product(*choices):
            family = dict(zip(self.colors, parts))
            key = tuple((color, family[color]) for color in self.colors)
            if key in seen:
                continue
            seen.add(key)
            if family == all_equal or family == all_universal:
                continue
            failure = self.congruence_family_failure(family)
            audits.append(
                SemisplitAudit(
                    universal_colors=tuple(
                        color
                        for color in self.colors
                        if family[color] == universal_partition(self.fibres[color])
                    ),
                    family=family,
                    admissible=failure is None,
                    failure=failure,
                )
            )
        return audits

    def semisplit_families(self) -> List[Dict[Color, Partition]]:
        """Return admissible equality/universal mixtures, excluding extremes."""

        return [dict(audit.family) for audit in self.semisplit_audits() if audit.admissible]

    def _semisplit_partition(self, color: Color, bit: int) -> Partition:
        if bit == 0:
            return equality_partition(self.fibres[color])
        if bit == 1:
            return universal_partition(self.fibres[color])
        raise ValueError("semisplit bits must be 0 or 1")

    def semisplit_constraint_rows(self) -> List[SemisplitConstraintRow]:
        """Return exact Boolean constraints for equality/universal families.

        For each colour pair `(a,b)` with target `(c,d)`, the allowed patterns
        list exactly those equality/universal choices for
        `(a,b,c,d)` for which `T_{a,b}` transports the source product relation
        onto the target product relation.
        """

        rows = []
        for a, b in product(self.colors, repeat=2):
            c, d = self.base_R[(a, b)]
            allowed = []
            for source_a, source_b, target_c, target_d in product((0, 1), repeat=4):
                if self.transports_congruence_pair(
                    a,
                    b,
                    self._semisplit_partition(a, source_a),
                    self._semisplit_partition(b, source_b),
                    self._semisplit_partition(c, target_c),
                    self._semisplit_partition(d, target_d),
                ):
                    allowed.append((source_a, source_b, target_c, target_d))
            rows.append(
                SemisplitConstraintRow(
                    a=a,
                    b=b,
                    c=c,
                    d=d,
                    allowed_patterns=tuple(allowed),
                )
            )
        return rows

    def semisplit_boolean_assignments(self) -> List[Dict[Color, int]]:
        """Return admissible non-extreme equality/universal bit assignments."""

        rows = self.semisplit_constraint_rows()
        all_equal = {c: equality_partition(self.fibres[c]) for c in self.colors}
        all_universal = {c: universal_partition(self.fibres[c]) for c in self.colors}
        assignments = []
        seen_families = set()
        for bits in product((0, 1), repeat=len(self.colors)):
            assignment = dict(zip(self.colors, bits))
            if any(
                (
                    assignment[row.a],
                    assignment[row.b],
                    assignment[row.c],
                    assignment[row.d],
                )
                not in row.allowed_patterns
                for row in rows
            ):
                continue
            family = {
                color: self._semisplit_partition(color, assignment[color])
                for color in self.colors
            }
            if family == all_equal or family == all_universal:
                continue
            key = tuple((color, family[color]) for color in self.colors)
            if key in seen_families:
                continue
            seen_families.add(key)
            assignments.append(assignment)
        return assignments

    def pair_generated_local_minimality_audits(
        self,
    ) -> List[PairGeneratedLocalMinimalityAudit]:
        """Return exact single-pair generation audits for local-minimality.

        A finite interval is local-minimal iff every distinct pair inside a
        fibre generates the all-universal admissible relation family.  Indeed,
        any non-equality admissible family contains such a pair, and the least
        admissible family generated by that pair is contained in it.
        """

        audits = []
        for color in self.colors:
            points = self.fibres[color]
            for left_index, left in enumerate(points):
                for right in points[left_index + 1 :]:
                    generated = generated_admissible_congruence_audit(
                        self,
                        {color: ((left, right),)},
                    )
                    audits.append(
                        PairGeneratedLocalMinimalityAudit(
                            color=color,
                            left=left,
                            right=right,
                            generated=generated,
                        )
                    )
        return audits

    def pair_generated_local_minimality_failures(
        self,
    ) -> List[PairGeneratedLocalMinimalityAudit]:
        """Return pair closures that witness failure of local-minimality."""

        return [
            audit
            for audit in self.pair_generated_local_minimality_audits()
            if audit.generated.kind != "universal"
        ]

    def admissible_congruence_families(self, max_fibre_size: int = 5) -> List[Dict[Color, Partition]]:
        """Enumerate all admissible families for small fibres."""

        if any(len(self.fibres[color]) > max_fibre_size for color in self.colors):
            raise ValueError("full partition enumeration disabled for this fibre size")
        per_color = [set_partitions(self.fibres[color]) for color in self.colors]
        out = []
        for parts in product(*per_color):
            family = dict(zip(self.colors, parts))
            if self.is_admissible_congruence_family(family):
                out.append(family)
        return out

    def is_local_minimal(self, max_fibre_size: int = 5) -> bool:
        """Return the exact local-minimality verdict.

        The `max_fibre_size` argument is retained for compatibility with the
        older partition-enumeration checker.  The current criterion uses
        single-pair admissible closures and has no Bell-number fibre-size
        guard.
        """

        return not self.pair_generated_local_minimality_failures()
