from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from itertools import product
from typing import Dict, Sequence, Tuple

from .artin_longitudes import FreeWord
from .finite_braided_set import Element, FiniteBraidedSet, Word
from .finite_group import FiniteGroup

TupleWord = Tuple[Element, ...]
OrbitPartition = Tuple[Tuple[TupleWord, ...], ...]


@dataclass(frozen=True)
class StructureOrbitHolonomySummary:
    n: int
    orbit_count: int
    orbit_sizes: Tuple[int, ...]
    orbit_group_sizes: Tuple[int | None, ...]
    orbit_group_exponents: Tuple[int | None, ...]
    truncated_orbit_count: int


@dataclass(frozen=True)
class StructureOrbitFactorizationSummary:
    n: int
    tuple_count: int
    orbit_count: int
    global_group_size: int | None
    global_group_exponent: int | None
    global_group_truncated: bool
    orbit_group_sizes: Tuple[int | None, ...]
    orbit_group_exponents: Tuple[int | None, ...]
    orbit_group_truncated_count: int
    product_group_size_bound: int | None
    projection_image_sizes: Tuple[int | None, ...]
    projections_match_orbit_groups: bool | None


@dataclass(frozen=True)
class StructureOrbitLawSeparation:
    n: int
    arity: int
    orbit_index: int | None
    orbit_size: int | None
    target_group_size: int | None
    separating_word: FreeWord | None
    moved_tuple: TupleWord | None
    moved_image: TupleWord | None
    truncated_orbit_count: int


def adjacent_rewrites(solution: FiniteBraidedSet, word: Sequence[Element]) -> Tuple[TupleWord, ...]:
    """Return all one-step structure rewrites of a word.

    The positive structure monoid has relations ``xy = uv`` whenever
    ``R(x,y)=(u,v)``.  On a fixed degree, applying one relation in either
    direction is the same as applying one braid generator or its inverse.
    """

    out = []
    for index in range(len(word) - 1):
        out.append(solution.apply_R_at(word, index, inverse=False))
        out.append(solution.apply_R_at(word, index, inverse=True))
    return tuple(out)


def structure_orbit(solution: FiniteBraidedSet, start: Sequence[Element]) -> Tuple[TupleWord, ...]:
    """Return the degree-fixed structure congruence class of ``start``."""

    initial = tuple(start)
    seen = {initial}
    queue = deque([initial])
    while queue:
        current = queue.popleft()
        for candidate in adjacent_rewrites(solution, current):
            if candidate in seen:
                continue
            seen.add(candidate)
            queue.append(candidate)
    return tuple(sorted(seen, key=repr))


def level_structure_orbit_partition(
    solution: FiniteBraidedSet, n: int
) -> OrbitPartition:
    """Partition ``X^n`` into structure-orbit classes."""

    unseen = set(product(solution.elements, repeat=n))
    blocks = []
    while unseen:
        start = min(unseen, key=repr)
        orbit = structure_orbit(solution, start)
        blocks.append(orbit)
        unseen.difference_update(orbit)
    return tuple(sorted(blocks, key=repr))


def orbit_lookup(partition: OrbitPartition) -> Dict[TupleWord, int]:
    """Return a tuple-to-orbit-index lookup for a structure partition."""

    lookup: Dict[TupleWord, int] = {}
    for index, block in enumerate(partition):
        for word in block:
            lookup[word] = index
    return lookup


def braid_action_preserves_structure_orbits(
    solution: FiniteBraidedSet, n: int, braid_word: Word
) -> bool:
    """Return whether a braid word preserves every degree-``n`` orbit."""

    partition = level_structure_orbit_partition(solution, n)
    lookup = orbit_lookup(partition)
    for tup in product(solution.elements, repeat=n):
        image = solution.braid_action(braid_word, tup)
        if lookup[tuple(tup)] != lookup[image]:
            return False
    return True


def _orbit_generator_permutation(
    solution: FiniteBraidedSet, orbit: Tuple[TupleWord, ...], generator: int
) -> Tuple[int, ...]:
    index = {word: i for i, word in enumerate(orbit)}
    return tuple(
        index[solution.apply_R_at(word, generator, inverse=False)]
        for word in orbit
    )


def structure_orbit_holonomy_summary(
    solution: FiniteBraidedSet,
    n: int,
    *,
    max_group_size: int | None = None,
) -> StructureOrbitHolonomySummary:
    """Return exact braid-action groups on degree-`n` structure orbits.

    The degree-`n` structure congruence classes are exactly the `B_n` orbits
    on `X^n`.  This helper computes, for each orbit separately, the finite
    permutation group generated by the adjacent braid generators restricted to
    that orbit.  A truncated orbit is reported with `None` size/exponent.
    """

    from .action_images import generated_permutation_subgroup
    from .group_laws import lcm
    from .residual import permutation_order

    partition = level_structure_orbit_partition(solution, n)
    group_sizes = []
    group_exponents = []
    truncated = 0
    for orbit in partition:
        generators = tuple(
            _orbit_generator_permutation(solution, orbit, generator)
            for generator in range(n - 1)
        )
        try:
            subgroup = generated_permutation_subgroup(
                generators, max_size=max_group_size
            )
        except ValueError:
            truncated += 1
            group_sizes.append(None)
            group_exponents.append(None)
            continue
        exponent = 1
        for permutation in subgroup:
            exponent = lcm(exponent, permutation_order(permutation))
        group_sizes.append(len(subgroup))
        group_exponents.append(exponent)
    return StructureOrbitHolonomySummary(
        n=n,
        orbit_count=len(partition),
        orbit_sizes=tuple(len(orbit) for orbit in partition),
        orbit_group_sizes=tuple(group_sizes),
        orbit_group_exponents=tuple(group_exponents),
        truncated_orbit_count=truncated,
    )


def _global_generator_permutation(
    solution: FiniteBraidedSet, tuples: Tuple[TupleWord, ...], generator: int
) -> Tuple[int, ...]:
    index = {word: i for i, word in enumerate(tuples)}
    return tuple(
        index[solution.apply_R_at(word, generator, inverse=False)]
        for word in tuples
    )


def _permutation_exponent(permutations) -> int:
    from .group_laws import lcm
    from .residual import permutation_order

    exponent = 1
    for permutation in permutations:
        exponent = lcm(exponent, permutation_order(permutation))
    return exponent


def structure_orbit_factorization_summary(
    solution: FiniteBraidedSet,
    n: int,
    *,
    max_group_size: int | None = None,
) -> StructureOrbitFactorizationSummary:
    """Compare the global fixed-degree image with orbit-holonomy factors.

    Since braid action preserves degree-`n` structure orbits, the global image
    in `Sym(X^n)` injects into the product of the internal action groups on
    those orbits.  When the global image and orbit images close under the
    configured cap, this helper verifies that the projection of the global
    image to each orbit is exactly the corresponding orbit holonomy group.
    """

    from .action_images import generated_permutation_subgroup

    partition = level_structure_orbit_partition(solution, n)
    tuples = tuple(product(solution.elements, repeat=n))
    global_generators = tuple(
        _global_generator_permutation(solution, tuples, generator)
        for generator in range(n - 1)
    )
    try:
        global_group = generated_permutation_subgroup(
            global_generators, max_size=max_group_size
        )
        global_group_size = len(global_group)
        global_group_exponent = _permutation_exponent(global_group)
        global_truncated = False
    except ValueError:
        global_group = None
        global_group_size = None
        global_group_exponent = None
        global_truncated = True

    orbit_groups = []
    orbit_group_sizes = []
    orbit_group_exponents = []
    truncated_orbits = 0
    for orbit in partition:
        generators = tuple(
            _orbit_generator_permutation(solution, orbit, generator)
            for generator in range(n - 1)
        )
        try:
            orbit_group = generated_permutation_subgroup(
                generators, max_size=max_group_size
            )
            orbit_groups.append(orbit_group)
            orbit_group_sizes.append(len(orbit_group))
            orbit_group_exponents.append(_permutation_exponent(orbit_group))
        except ValueError:
            orbit_groups.append(None)
            orbit_group_sizes.append(None)
            orbit_group_exponents.append(None)
            truncated_orbits += 1

    product_bound = 1
    if global_truncated or truncated_orbits:
        product_bound = None
    else:
        for size in orbit_group_sizes:
            if size is None:
                product_bound = None
                break
            product_bound *= size

    projection_image_sizes = []
    projections_match = None
    if global_group is not None and not truncated_orbits:
        tuple_index = {word: i for i, word in enumerate(tuples)}
        projections_match = True
        for orbit, orbit_group in zip(partition, orbit_groups):
            if orbit_group is None:
                projection_image_sizes.append(None)
                projections_match = None
                continue
            local_index = {word: i for i, word in enumerate(orbit)}
            global_indices = tuple(tuple_index[word] for word in orbit)
            projected = {
                tuple(
                    local_index[tuples[permutation[global_index]]]
                    for global_index in global_indices
                )
                for permutation in global_group
            }
            projection_image_sizes.append(len(projected))
            if projected != orbit_group:
                projections_match = False
    else:
        projection_image_sizes = [None for _orbit in partition]

    return StructureOrbitFactorizationSummary(
        n=n,
        tuple_count=len(tuples),
        orbit_count=len(partition),
        global_group_size=global_group_size,
        global_group_exponent=global_group_exponent,
        global_group_truncated=global_truncated,
        orbit_group_sizes=tuple(orbit_group_sizes),
        orbit_group_exponents=tuple(orbit_group_exponents),
        orbit_group_truncated_count=truncated_orbits,
        product_group_size_bound=product_bound,
        projection_image_sizes=tuple(projection_image_sizes),
        projections_match_orbit_groups=projections_match,
    )


def _orbit_braid_permutation(
    solution: FiniteBraidedSet,
    orbit: Tuple[TupleWord, ...],
    braid_word: Word,
) -> Tuple[int, ...]:
    index = {word: i for i, word in enumerate(orbit)}
    return tuple(index[solution.braid_action(braid_word, word)] for word in orbit)


def structure_orbit_law_separation(
    solution: FiniteBraidedSet,
    n: int,
    law_groups: Sequence[FiniteGroup],
    *,
    max_length: int,
    max_group_size: int | None = None,
) -> StructureOrbitLawSeparation:
    """Find an orbit-local finite-law separator for pure braid images.

    This is a bounded diagnostic for the normalized-law B route.  It restricts
    the standard pure generators ``A_{i,n}`` to each degree-``n`` structure
    orbit, then searches for a free word that is a law on every supplied
    detector group but evaluates nontrivially on the restricted pure-generator
    tuple.  That assigned-generator condition is exactly what is needed for
    the corresponding law braid to move a tuple.
    """

    from .action_images import (
        generated_permutation_subgroup,
        short_law_separating_permutation_assignment,
    )
    from .braid_laws import pure_braid_generator

    if n < 2:
        raise ValueError("n must be at least 2")
    arity = n - 1
    pure_braids = {
        generator: pure_braid_generator(generator + 1, n)
        for generator in range(arity)
    }
    truncated = 0
    for orbit_index, orbit in enumerate(level_structure_orbit_partition(solution, n)):
        generator_images = {
            generator: _orbit_braid_permutation(solution, orbit, braid_word)
            for generator, braid_word in pure_braids.items()
        }
        target_group_size = None
        try:
            subgroup = generated_permutation_subgroup(
                generator_images.values(),
                max_size=max_group_size,
            )
            target_group_size = len(subgroup)
        except ValueError:
            truncated += 1
        separation = short_law_separating_permutation_assignment(
            law_groups,
            generator_images,
            max_length=max_length,
        )
        if separation.separating_word is None or separation.evaluated_permutation is None:
            continue
        source_index = separation.moved_index
        if source_index is None:
            continue
        target_index = separation.evaluated_permutation[source_index]
        return StructureOrbitLawSeparation(
            n=n,
            arity=arity,
            orbit_index=orbit_index,
            orbit_size=len(orbit),
            target_group_size=target_group_size,
            separating_word=separation.separating_word,
            moved_tuple=orbit[source_index],
            moved_image=orbit[target_index],
            truncated_orbit_count=truncated,
        )
    return StructureOrbitLawSeparation(
        n=n,
        arity=arity,
        orbit_index=None,
        orbit_size=None,
        target_group_size=None,
        separating_word=None,
        moved_tuple=None,
        moved_image=None,
        truncated_orbit_count=truncated,
    )
