import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const outDir = path.join(root, "tables");
const outPath = path.join(outDir, "reduction_audit.xlsx");

const rows = [
  [
    "Area",
    "Requirement",
    "Current evidence",
    "Status",
    "Next decisive check",
  ],
  [
    "Progress summary",
    "Give proof critics a compact source-of-truth entry point.",
    "proofs/progress_summary.md records established reductions, closed branches, B-route requirements, and the current bi-free universal-corridor bottleneck.",
    "Current map",
    "Keep synchronized with proof log and zip handoff prompt.",
  ],
  [
    "Quotient/residual",
    "Define N_n, fibres X_z, delta maps, and Delta_n.",
    "Logged in sawin_status.md.",
    "Set up",
    "Use in any interval proof or counterexample.",
  ],
  [
    "Sharp obstruction",
    "Finite-G implication gives Q x A_G.",
    "Kernel/collision theorem written; sharp_obstruction_rack(Q,G) constructs the finite product rack.",
    "Reduction ready",
    "Prove uniform G or produce law sequence.",
  ],
  [
    "Purity stabilization",
    "Ensure pure-braid formulas are used only after permutation is killed.",
    "T2 factor in A_G forces Artin permutation; guardrail test added.",
    "Reduction ready",
    "Keep local branch proofs tied to full Lambda identity.",
  ],
  [
    "Rack cover",
    "Check direct rack quotient-cover shortcut.",
    "Impossible unless X is rack-type.",
    "Ruled out",
    "Use indirect detector racks only.",
  ],
  [
    "Congruence chain",
    "Local detectors compose down congruence chain.",
    "Cover/local extraction implemented; closed_local_detector_chain requires one fixed product group per closed interval before assemble_congruence_chain_rack builds Q_i=Q_{i+1} x A_{G_i}.",
    "Executable audit",
    "Check detector independence from n.",
  ],
  [
    "Master dichotomy",
    "A follows from all local detectors; B follows from one detector-free interval.",
    "proofs/master_local_dichotomy.md combines congruence induction with diagonalization.",
    "Reduction ready",
    "Prove local theorem or exhibit explicit no-finite-G local interval.",
  ],
  [
    "Local table",
    "T_{a,b} bijections satisfy coloured YBE.",
    "LocalInterval verifies finite tables.",
    "Executable audit",
    "Use symbolic proof for final candidate.",
  ],
  [
    "Local-minimality gate",
    "Route finite intervals only after exact local-minimality evidence.",
    "Single-pair closure counters expose failures and max depth; derivation rows now record the first seed/forward/inverse proof of each generated relation edge.",
    "Proof hygiene",
    "Use generated pair closures as the arbitrary-fibre certificate.",
  ],
  [
    "Semisplit",
    "Equality/universal mixtures must be tested.",
    "Relation-level lemma plus witness audit.",
    "Executable audit",
    "Prove exclusion in master theorem.",
  ],
  [
    "Finite-G detector",
    "A_G action matches recursive Artin longitudes.",
    "Bridge plus abelian matrix tests.",
    "Executable audit",
    "Use for candidate beta_j checks.",
  ],
  [
    "Rack longitude quotient",
    "Finite rack actions factor through Inn(Y) longitudes.",
    "Inner-group formula proved and tested.",
    "Reduction ready",
    "Use to show B defeats every rack.",
  ],
  [
    "Longitude factorization",
    "Residual action factors through F_n/K_G(n).",
    "Criterion stated; factorization still open.",
    "Reduction ready",
    "Prove Green/corridor factorization.",
  ],
  [
    "Longitude subgroup",
    "Compress finite-G longitude identity to V_beta(G).",
    "Profile helper, law-braid wrapper, homomorphism/product functoriality, and explicit witness calculus implemented.",
    "Reduction ready",
    "Use witness pushforward/product assembly for A factorization audits, detector quotients, and B law profiles.",
  ],
  [
    "Mover profiles",
    "Attach moved tuples to subgroup visibility rows.",
    "Total/residual helpers implemented.",
    "Executable audit",
    "Use on B candidates and detector failures.",
  ],
  [
    "Label-longitudes",
    "Labels are finite-H longitude evaluations.",
    "Sufficient condition stated.",
    "Reduction ready",
    "Prove for product and Green/corridor labels.",
  ],
  [
    "Input-dependent",
    "Allow homomorphisms depending on fibre tuple.",
    "Rack factorization exposed in code.",
    "Reduction ready",
    "Prove Green/corridor input-dependent factorization.",
  ],
  [
    "Detector action factor",
    "Residual action factors through the fixed rack detector action A_G.",
    "Action/readout criterion stated; fixed-n residual-fibre readout table audit added, including direct Sym(X) wrapper.",
    "Reduction ready",
    "Construct these readouts uniformly in n, or build a normalized-law escape.",
  ],
  [
    "Detector products",
    "Combine finite detector factors into one G.",
    "Longitude, subgroup, action, and fixed-n readout product equivalences recorded.",
    "Reduction ready",
    "Use for local G_i construction, subgroup membership, and factor readouts.",
  ],
  [
    "Product domination closure",
    "Cartesian products of dominated finite solutions stay dominated.",
    "All-n coordinatewise kernel-intersection proof plus braid-action convention test.",
    "Reduction ready",
    "Do not treat products of already dominated factors as B candidates.",
  ],
  [
    "Hereditary closure",
    "Domination passes to quotients and crossing-closed subsolutions.",
    "All-n projection/restriction kernel inclusions plus convention tests.",
    "Reduction ready",
    "Search for quotient-minimal and subsolution-minimal B candidates.",
  ],
  [
    "Nondegenerate cover",
    "Quotients of finite nondegenerate solutions stay nondegenerate.",
    "Surjectivity proof added; regression uses a nontrivial rack-product quotient.",
    "Guardrail",
    "Do not try to solve degenerate intervals by hidden nondegenerate covers.",
  ],
  [
    "Abelian longitudes",
    "Cyclic groups detect pairwise-linking exponents.",
    "Dedicated all-n detector note plus row/column product formula implemented.",
    "Reduction ready",
    "Use for pairwise-linking branches.",
  ],
  [
    "Pairwise-linking detector",
    "Give fixed cyclic G for residual labels linear in abelian longitude entries.",
    "proofs/pairwise_linking_detector.md proves the Lambda_Cm implication.",
    "Symbolic branch closed",
    "Route genuinely coloured holonomy to coboundary/product-label or bi-free corridor.",
  ],
  [
    "Residual kernel",
    "Check beta in ker Q and Lambda_G=1 implies Delta=1.",
    "Bounded failure harness implemented.",
    "Executable audit",
    "Use on local obstruction candidates.",
  ],
  [
    "Image-kernel sequence",
    "Identify fixed-degree residual image kernel.",
    "Joint image/kernel summary implemented.",
    "Exact fixed-n audit",
    "Describe kernels uniformly in n.",
  ],
  [
    "Residual dependencies",
    "Track fibre-coordinate supports after base fixing.",
    "Summary plus detector-failure classifier.",
    "Exact fixed-n audit",
    "Split coordinatewise vs multi-input holonomy.",
  ],
  [
    "Candidate search",
    "Convert local tables to quotient maps and scan groups.",
    "Bounded profile harness implemented.",
    "Executable audit",
    "Find symbolic normalized-law family.",
  ],
  [
    "Normalized laws",
    "Audit exponent-law braid shortcut.",
    "Pure-power shortcut ruled insufficient; normalized_law_sequence_gate records the order-prefix law condition and prefix audit helper.",
    "Gap clarified",
    "Need non-power law family or proof.",
  ],
  [
    "Pure-braid laws",
    "Embed free laws via A_{i,n} pure braids.",
    "Law-longitude lemma plus tests.",
    "Reduction ready",
    "Find fixed moved YBE action.",
  ],
  [
    "Last-strand law reduction",
    "Replace arbitrary symmetric-kernel pure braids by point-pushed layers while retaining actual finite-longitude kernel membership.",
    "proofs/sawin_last_strand_law_reduction.md now records only the safe necessary law condition iota_n(w) in K_G(n) => w is a law on G; proofs/last_strand_law_gap_audit.md shows the converse is false.",
    "Repaired reduction",
    "Prove a fixed S_m kills all point-pushing layers in K_{S_m}, or construct such K_{S_j} layers that move X.",
  ],
  [
    "Fadell-Neuwirth layer extraction",
    "Justify that a moving K_G braid yields a moving ordinary last-strand point-pushing law layer.",
    "proofs/fadell_neuwirth_layer_extraction_guardrail.md records deletion/splitting preservation of K_G, the recursive right-stabilized layer decomposition, and the action-triviality guardrail for right-stabilized layers.",
    "Guardrail theorem",
    "Use only the standard right-strand splitting in point-pushing fixed-variety arguments unless a new embedding-triviality proof is supplied.",
  ],
  [
    "Point-pushing action-image variety",
    "Retain the action-image variety test only as a necessary-condition/search diagnostic after the law-to-kernel gap.",
    "proofs/point_pushing_action_image_variety.md now marks the variety equivalence as superseded: variety escapes produce candidate point-pushing movers, but they require a separate K_{S_m} finite-longitude membership check.",
    "Superseded diagnostic",
    "Use variety escapes only with an actual finite-longitude kernel check; ordinary S_m-laws are insufficient.",
  ],
  [
    "Point-pushing fixed-variety criterion",
    "State the exact global equivalence between finite-rack domination and one fixed finite variety containing all point-pushing images.",
    "proofs/last_strand_law_gap_audit.md now shows the forward law-to-K_G implication used by proofs/point_pushing_fixed_variety_domination.md is false; the criterion is retained only as a necessary-condition/search heuristic.",
    "Superseded gap",
    "Use actual finite-longitude identity, not ordinary law identity, for A or B certificates.",
  ],
  [
    "Last-strand law gap",
    "Prevent replacing finite-longitude identity by ordinary group-law identity.",
    "proofs/last_strand_law_gap_audit.md gives the dihedral-rack S3-law point-pushing mover and streamed longitude check showing nonidentity S3 finite-longitude data; point_pushing_exponent_escape_audit exposes this finite row.",
    "Guardrail counterexample",
    "Repair any theorem using w in Law(G) => iota(w) in K_G; only the converse is safe.",
  ],
  [
    "Point-pushing kernel-layer criterion",
    "State the exact repaired last-strand criterion using K_G membership rather than ordinary laws.",
    "proofs/point_pushing_kernel_layer_criterion.md proves K_G dominates X iff every last-strand point-pushing braid lying in K_G acts trivially on X, and records the Artin derivative detector D_k(G) sufficient condition.",
    "Exact reformulation",
    "Characterize or eliminate moving point-pushing K_{S_j} layers; ordinary S_j-law movers are insufficient.",
  ],
  [
    "Point-pushing product-prefix obstruction",
    "Show that failure of finite-rack domination may be diagonalized using genuine point-pushing K_G layers.",
    "proofs/point_pushing_product_prefix_obstruction.md applies the kernel-layer criterion to the product-prefix groups P_j=G_1 x ... x G_j, then right-stabilizes the moving layers to obtain a normalized-law sequence.",
    "Exact B-route reduction",
    "A B proof may search for moving point-pushing layers in K_{P_j}; ordinary P_j-law words remain insufficient without the K_{P_j} check.",
  ],
  [
    "Product-prefix first-failure stratification",
    "Make the product-prefix profile monotone and normalize unbounded failures to first Brunnian rows.",
    "proofs/point_pushing_product_prefix_first_failure_stratification.md proves eta_X(k)=min{j:D_k(P_j)->P_k(X)} is finite and weakly increasing, bounded iff A holds, and unbounded tails have k_j->infinity Brunnian first failures; point_pushing_product_prefix_first_failure_audit records finite prefixes.",
    "Product-prefix fork",
    "Prove eta_X(k) is bounded, or construct an infinite product-prefix first-failure Brunnian tail.",
  ],
  [
    "Action-quotient separation",
    "Show product-prefix movers must be residually deep inside the action images P_k(X).",
    "proofs/point_pushing_action_quotient_separation.md proves w=1 in D_k(P_j) but nontrivial in P_k(X) implies the moved element survives no quotient of P_k(X) of order <= b(j); point_pushing_action_quotient_separation_audit records finite residual-depth prefixes.",
    "Residual-depth reduction",
    "Prove uniformly bounded element-separating quotients for P_k(X), or construct product-prefix Brunnian movers with unbounded separation depth.",
  ],
  [
    "Monolithic compression",
    "Compress every product-prefix action mover to a smallest separating quotient.",
    "proofs/point_pushing_monolithic_compression.md proves a minimal separating quotient of a product-prefix failure is monolithic, its moved value lands in the monolith, and its order exceeds b(j); point_pushing_monolithic_compression_audit checks finite rows.",
    "Critical quotient reduction",
    "Rule out unbounded monolithic first-failure quotients, or construct such a tail for B.",
  ],
  [
    "Monolith type split",
    "Split critical monolithic quotients into abelian and nonabelian monolith regimes.",
    "proofs/point_pushing_monolith_type_split.md proves the monolith is characteristically simple: elementary abelian (C_p)^r or S^r for a nonabelian finite simple S; point_pushing_monolithic_compression_audit records finite row type data.",
    "Two-tail reduction",
    "Rule out both unbounded elementary-abelian and nonabelian-simple-product monolith tails, or construct one for B.",
  ],
  [
    "Abelian monolith split",
    "Separate elementary-abelian monolith failures into central-depth and noncentral irreducible-module regimes.",
    "proofs/point_pushing_abelian_monolith_split.md proves that an elementary-abelian monolith has [H,M]=1 or [H,M]=M; the first case is central-extension depth and the second gives a faithful irreducible conjugation-module quotient. The monolithic audit records centralizer/action/commutator data.",
    "Two-regime abelian reduction",
    "Rule out unbounded central monolithic depth and unbounded noncentral irreducible F_p-module tails, or construct one for B.",
  ],
  [
    "Central monolith depth",
    "Split central elementary-abelian monolith failures into cyclic p-power depth and stem central-extension depth.",
    "proofs/point_pushing_central_monolith_depth.md proves that if the central monolith is not inside [H,H], abelianization separates it and minimality forces H to be cyclic p-power; otherwise M <= Z(H) cap [H,H]. The audit records derived-subgroup membership and the central depth regime.",
    "Four-tail reduction",
    "Rule out cyclic p-power depth, central stem depth, noncentral irreducible module tails, and nonabelian simple-product tails, or construct one for B.",
  ],
  [
    "Cyclic p-power tail",
    "Split cyclic central-depth failures into prime escape and p-power depth escape.",
    "proofs/point_pushing_cyclic_p_power_tail.md proves that a cyclic C_{p^e} first failure has p^e>b(j), hence either p>b(j) or p<=b(j)<p^e; proper quotients kill the bottom monolith element. The audit records p, e, and prefix regime.",
    "p-adic tail reduction",
    "Rule out unbounded cyclic prime escape and fixed-prime unbounded p-adic depth, or construct one for B.",
  ],
  [
    "Cyclic tail closure",
    "Close cyclic product-prefix monolith tails by a uniform point-pushing generator order bound.",
    "proofs/point_pushing_cyclic_tail_closure.md proves every cyclic quotient of every P_k(X) has order dividing B_X=ord(rho_X,2(sigma_1^2)); hence no cyclic p-power quotient can satisfy p^e>b(j) once b(j)>=B_X. point_pushing_cyclic_tail_bound_audit records finite convention checks.",
    "Cyclic branch closed",
    "Remaining monolithic tails: central stem, noncentral module prime/dimension/centralizer-layer, and nonabelian simple-factor/multiplicity.",
  ],
  [
    "Bounded normal generator tail",
    "Normalize every product-prefix first-failure monolithic quotient to one bounded-order normal generator.",
    "proofs/point_pushing_bounded_normal_generator_tail.md proves that in a Brunnian first failure the critical monolith M is contained in the normal closure of t=phi(h_new), with ord(t) dividing B_X. point_pushing_bounded_normal_generator_audit records finite convention checks.",
    "All remaining tails constrained",
    "Rule out the six bounded-order normal-generator tails, or construct one for B.",
  ],
  [
    "Abelian-chief relation module",
    "Linearize abelian-chief Brunnian failures as detector orbit relation-module quotients.",
    "proofs/point_pushing_abelian_chief_relation_module.md proves that a minimal abelian-chief first failure gives a nonzero, hence surjective, F_p[N_D]-module quotient Rel_D tensor F_p -> M. point_pushing_abelian_chief_relation_module_audit records finite chief-layer bookkeeping.",
    "Abelian chief linearized",
    "Rule out unbounded irreducible relation-module quotients, or construct one for B.",
  ],
  [
    "Abelian relation action split",
    "Split abelian-chief relation quotients by trivial versus nontrivial detector-orbit action.",
    "proofs/point_pushing_abelian_relation_action_split.md proves that a trivial action forces M ~= F_p and factors through coinvariants, while a nontrivial action gives a nontrivial irreducible module with [N_D,M]=M. point_pushing_abelian_relation_action_split_audit records finite row regimes.",
    "Abelian branch split",
    "Route central trivial coinvariant tails through the stem multiplier note; rule out noncentral irreducible module tails, or construct one for B.",
  ],
  [
    "Central stem relation tail",
    "Identify central trivial coinvariant tails as stem central-extension multiplier quotients.",
    "proofs/point_pushing_central_stem_relation_tail.md proves that after cyclic closure a central trivial first failure is a stem extension F_p <= Z(H) cap [H,H], hence a p-quotient of a Schur multiplier of a detector-orbit quotient. point_pushing_central_stem_relation_audit records finite row shape.",
    "Central branch homological",
    "Rule out unbounded stem multiplier/coinvariant tails, or construct one for B.",
  ],
  [
    "Module prime characteristic split",
    "Force module-prime escape into cross-characteristic rows relative to the fixed generator-order bound.",
    "proofs/point_pushing_module_prime_characteristic_split.md proves that since ord(t)|B_X, only finitely many module primes can divide B_X; any p_j->infinity module-prime tail is eventually p_j not dividing B_X. point_pushing_module_prime_characteristic_audit records finite row labels.",
    "Prime escape cross-characteristic",
    "Rule out unbounded cross-characteristic irreducible relation-module quotients, or construct one for B.",
  ],
  [
    "Active module generator split",
    "Split noncentral module tails by whether the bounded newest generator acts nontrivially on the module.",
    "proofs/point_pushing_active_module_generator_split.md proves that if the generator image in H/C_H(M) is trivial the obstruction is centralizer-layer, while a nontrivial image is a bounded-order linear operator whose conjugate commutator images generate M. point_pushing_active_module_generator_audit records finite row labels.",
    "Module branch sharpened",
    "Rule out centralizer-layer generator tails and active bounded-order linear-generator tails, or construct one for B.",
  ],
  [
    "Centralizer-layer commutator split",
    "Split centralizer-layer generator tails by the commutator subgroup of the normal closure of the bounded newest generator.",
    "proofs/point_pushing_centralizer_layer_commutator_split.md proves that if N=<<t>>_H lies in C_H(M), contains M, and is minimal as a separating row, then either [N,N]=1 or M<=Z(N) cap [N,N]. point_pushing_centralizer_layer_commutator_audit records finite row labels.",
    "Centralizer layer split",
    "Rule out abelian centralizer-layer tails and centralizer-stem tails, or construct one for B.",
  ],
  [
    "Abelian centralizer-layer prime bound",
    "Remove prime escape from abelian centralizer-layer generator tails.",
    "proofs/point_pushing_abelian_centralizer_layer_prime_bound.md proves that an abelian N=<<t>>_H containing M is p-primary and exp(N)|ord(t)|B_X, so p divides the fixed bound B_X. point_pushing_abelian_centralizer_layer_prime_audit records finite prime-support labels.",
    "Prime escape ruled out here",
    "Rule out bounded-prime bounded-exponent centralizer-layer rank/extension tails, or construct one for B.",
  ],
  [
    "Centralizer-stem multiplier tail",
    "Convert centralizer-stem generator tails into Schur-multiplier quotient form.",
    "proofs/point_pushing_centralizer_stem_multiplier_tail.md proves that if M<=Z(N) cap [N,N] for N=<<t>>_H, then 1->M->N->N/M->1 is a stem central extension and M is a quotient of H_2(N/M,Z). point_pushing_centralizer_stem_multiplier_audit records finite quotient data.",
    "Stem layer homological",
    "Rule out bounded-generator centralizer-stem multiplier tails, or construct one for B.",
  ],
  [
    "Centralizer-stem noncyclic quotient",
    "Rule out cyclic quotients in centralizer-stem multiplier rows.",
    "proofs/point_pushing_centralizer_stem_noncyclic_quotient.md proves that if N/M is cyclic and M<=Z(N), then N is abelian, contradicting M<=[N,N]. point_pushing_centralizer_stem_multiplier_audit records quotient_is_cyclic and rejects cyclic rows.",
    "Cyclic quotient ruled out",
    "Rule out noncyclic bounded-generator centralizer-stem multiplier tails, or construct one for B.",
  ],
  [
    "Centralizer-stem transport split",
    "Split noncyclic centralizer-stem multiplier quotients by internal normal generation versus ambient transport generation.",
    "proofs/point_pushing_centralizer_stem_transport_split.md proves that for q=image(t) in Q=N/M, either <<q>>_Q=Q or the quotient is generated only by the ambient transported orbit of that proper internal normal closure. point_pushing_centralizer_stem_multiplier_audit records the internal normal closure order and regime.",
    "Transport split",
    "Rule out internally normally generated bounded quotients and transport-orbit generated quotients, or construct one for B.",
  ],
  [
    "Internal stem abelianization bound",
    "Bound the abelianization of internally normally generated centralizer-stem quotients.",
    "proofs/point_pushing_internal_stem_abelianization_bound.md proves that if q=image(t) internally normally generates Q=N/M, then Q_ab is cyclic generated by q_ab and has order dividing B_X. point_pushing_centralizer_stem_multiplier_audit records quotient abelianization data.",
    "Internal abelianization bounded",
    "Rule out internal-generator tails through perfect/commutator or multiplier growth, or construct one for B.",
  ],
  [
    "Nonabelian-chief relation quotient",
    "Compress nonabelian-chief Brunnian failures to detector relation-group quotients.",
    "proofs/point_pushing_nonabelian_chief_relation_quotient.md proves that a minimal nonabelian-chief first failure has mu_H(R)=M=S^r, and the detector orbit group controls the outer action on M. point_pushing_nonabelian_chief_relation_quotient_audit records finite chief-layer bookkeeping.",
    "Nonabelian chief compressed",
    "Rule out unbounded simple-power relation-group quotients, or construct one for B.",
  ],
  [
    "Nonabelian wreath coordinate lift",
    "Put nonabelian-chief failures into transitive simple-wreath coordinate normal form.",
    "proofs/point_pushing_nonabelian_wreath_coordinate_lift.md proves that a minimal nonabelian failure embeds H faithfully in Aut(S) wr Omega with Omega transitive, the row succeeds modulo M=S^r, and failure is exactly a detector relation with a nontrivial S-coordinate. point_pushing_nonabelian_wreath_coordinate_audit records finite row shape.",
    "Nonabelian branch localized",
    "Rule out unbounded simple-wreath coordinate relation tails, or construct one for B.",
  ],
  [
    "Noncentral module tail",
    "Split noncentral elementary-abelian monolith failures by module prime, module dimension, and centralizer-extension layer.",
    "proofs/point_pushing_noncentral_module_tail.md proves |H|=p^r |H/C_H(M)| |C_H(M)/M|; an infinite tail has module prime escape, fixed-prime dimension escape, or bounded-module centralizer-layer escape. The audit records dimension, layer size, product check, and row regime.",
    "Module/extension tail reduction",
    "Rule out unbounded noncentral module primes, dimensions, and bounded-module centralizer layers, or construct one for B.",
  ],
  [
    "Nonabelian monolith tail",
    "Split nonabelian simple-product monolith failures into simple-factor escape and multiplicity escape.",
    "proofs/point_pushing_nonabelian_monolith_tail.md proves C_H(S^r)=1, hence H embeds in Aut(S) wr Sym(r); an infinite nonabelian tail has |S_j|->infinity or fixed S with r_j->infinity. The audit records centralizer triviality, H/M order, and prefix regime.",
    "Simple-product tail reduction",
    "Rule out unbounded nonabelian simple factor size and unbounded multiplicity, or construct one for B.",
  ],
  [
    "Point-pushing marked quotient criterion",
    "Replace fixed-variety containment by the exact derivative-detector marked quotient condition.",
    "proofs/point_pushing_marked_quotient_criterion.md proves A_G dominates X iff every P_k(X) is a marked quotient of D_k(G); point_pushing_marked_quotient_audit checks finite arity instances.",
    "Exact reformulation",
    "Prove one fixed G has all marked quotients D_k(G)->P_k(X), or find product-prefix derivative relations that move X.",
  ],
  [
    "Point-pushing paired graph criterion",
    "Make the finite marked quotient test a vertical-kernel graph condition.",
    "proofs/point_pushing_paired_graph_criterion.md proves D_k(G)->P_k(X) exists iff <(d_i,h_i)> has no nontrivial (1,p); point_pushing_marked_quotient_audit now exposes vertical_kernel_trivial.",
    "Exact finite criterion",
    "Prove vertical kernels vanish for all k for one fixed G, or construct an infinite product-prefix/symmetric-tail family of vertical witnesses.",
  ],
  [
    "Point-pushing vertical witness certificate",
    "Make each finite vertical-kernel B seed self-certifying at braid-action level.",
    "proofs/point_pushing_vertical_witness_certificate.md proves a word trivial in D_k(G) but moving P_k(X), with direct braid agreement and moved tuple, is a genuine point-pushing K_G mover; point_pushing_vertical_witness_certificate checks one row.",
    "Certificate shape",
    "Build an all-j product-prefix or symmetric-tail family of valid_vertical_witness rows, or prove none can occur for one fixed detector.",
  ],
  [
    "Point-pushing fixed-arity cofinality",
    "Rule out fixed point-pushing arity as a possible B obstruction.",
    "proofs/point_pushing_fixed_arity_cofinality.md uses the triangular Nielsen last-longitude automorphism to show every finite k-marked quotient of F_k is a quotient of D_k(S_m) for some m.",
    "Growth reduction",
    "The remaining global question is whether mu_X(k)=min{m:D_k(S_m)->P_k(X)} is bounded in k.",
  ],
  [
    "Point-pushing mu boundedness dichotomy",
    "State the exact A/B fork as boundedness or unboundedness of the symmetric detector degree sequence.",
    "proofs/point_pushing_mu_boundedness_dichotomy.md proves X is finite-rack dominated iff sup_k mu_X(k)<infinity; unbounded mu_X gives symmetric-tail vertical witnesses and a normalized-law obstruction.",
    "Exact growth fork",
    "Prove a symbolic bound m(X), or exhibit explicit unbounded mu_X(k_j)>j witnesses.",
  ],
  [
    "Point-pushing mu functoriality",
    "Rule out quotient and product artifacts as sources of unbounded mu growth.",
    "proofs/point_pushing_mu_functoriality.md proves quotient/domination monotonicity and the product formula mu_{X x Y}(k)=max(mu_X(k),mu_Y(k)).",
    "Structural cleanup",
    "Search for unbounded mu only in primitive components; finite products of bounded factors cannot yield B.",
  ],
  [
    "Point-pushing suffix-shuttle normal form",
    "Express every point-pushing generator by one fixed reversible two-pass finite-state schema.",
    "proofs/point_pushing_suffix_shuttle_normal_form.md expands A_{i,n} as a left R-scan, local square, and right R^{-1}-scan; point_pushing_suffix_shuttle_audit checks the convention.",
    "Finite-state reduction",
    "Prove this suffix-shuttle transducer family has bounded mu, or build unbounded vertical witnesses from it.",
  ],
  [
    "Point-pushing recursive conjugacy",
    "Reduce all point-pushing generators to suffix shifts of one recursive family.",
    "proofs/point_pushing_recursive_conjugacy.md proves a_n=rho(A_{1,n}) satisfies a_n=s_{n-1}(a_{n-1} x id)s_{n-1}^{-1} and A_{i,n}=id^{i-1} x a_{n-i+1}; point_pushing_recursive_conjugacy_audit checks finite instances.",
    "Recursive finite-state reduction",
    "Bound mu for the suffix shifts of the single family a_n, or construct unbounded vertical witnesses from that family.",
  ],
  [
    "Point-pushing jump normalization",
    "Normalize every detector-degree increase to one deletion-trivial new-strand relation.",
    "proofs/point_pushing_jump_normalization.md proves that if S_m works at arity k and fails at k+1, then the failure has a witness in ker(F_{k+1}->F_k); point_pushing_brunnian_witness_certificate checks right-based candidate rows.",
    "Relative obstruction reduction",
    "Prove R_{m,k+1} cap ker(r_k) <= N_{X,k+1} for one fixed m, or construct an unbounded family of Brunnian vertical witnesses.",
  ],
  [
    "Point-pushing Brunnian orbit criterion",
    "Replace arbitrary Brunnian words by the finite orbit-normal-closure subgroup of the new generator.",
    "proofs/point_pushing_brunnian_orbit_criterion.md proves that one-new-strand Brunnian witnesses are exactly nontrivial vertical elements in <<e>> under the old suffix paired subgroup; point_pushing_brunnian_orbit_audit checks finite rows.",
    "Exact extension criterion",
    "Prove the relative orbit-normal-closure vertical kernel is trivial for all k for one fixed m, or produce an unbounded symmetric-tail family of such vertical elements.",
  ],
  [
    "Point-pushing Brunnian relation lift",
    "Split the one-new-strand obstruction into orbit-label ambiguity and failed relation lifting.",
    "proofs/point_pushing_brunnian_relation_lift.md proves that, under the old graph hypothesis, extension holds iff the new-generator detector conjugacy orbit has a well-defined transported action label and all orbit relations lift.",
    "Relation package",
    "Prove orbit-label well-definedness plus relation lifting uniformly, or build a symmetric-tail ambiguity/relation-failure sequence.",
  ],
  [
    "Point-pushing Brunnian stabilizer gate",
    "Convert orbit-label well-definedness to a stabilizer-centralizer inclusion.",
    "proofs/point_pushing_brunnian_stabilizer_gate.md proves q(Stab(d)) <= Cent(h) iff the transported new-generator orbit label is well-defined; point_pushing_brunnian_orbit_audit now exposes the stabilizer check.",
    "First relation-lift gate",
    "Prove the stabilizer-centralizer inclusion uniformly, or construct an infinite symmetric-tail family of stabilizer failures.",
  ],
  [
    "Point-pushing Brunnian orbit quotient certificate",
    "Package the post-stabilizer relation lift as a finite graph quotient test.",
    "proofs/point_pushing_brunnian_orbit_quotient_certificate.md proves the remaining relation lift iff the paired orbit subgroup projects injectively to its detector projection, equivalently |B|=|B_D|.",
    "Final one-strand gate",
    "Prove every arity has failure_kind=none for one fixed m, or produce an infinite symmetric-tail family with stabilizer/orbit_label/orbit_relation witnesses.",
  ],
  [
    "Point-pushing Brunnian gate induction",
    "Replace all marked quotient checks by a base arity and sequential one-new-strand gates.",
    "proofs/point_pushing_brunnian_gate_induction.md proves A_G dominates X iff arity 1 is detected and every Brunnian extension row has failure_kind=none; point_pushing_brunnian_gate_prefix_audit checks finite prefixes.",
    "Exact induction criterion",
    "Prove one fixed S_m passes all gates, or construct an infinite symmetric-tail sequence of first failures.",
  ],
  [
    "Point-pushing base-arity gate",
    "Close the arity-1 point-pushing gate by the order of the pure two-strand action.",
    "proofs/point_pushing_base_arity_gate.md proves D_1(G)->P_1(X) exists whenever ord(R_X^2) divides exp(G); point_pushing_base_arity_certificate records the minimal symmetric cutoff b_X.",
    "Base gate closed",
    "Only the one-new-strand Brunnian extension gates remain in any asymptotic B tail.",
  ],
  [
    "Point-pushing base-free Brunnian tail",
    "Start symmetric-tail audits after the minimal symmetric base cutoff b_X=min{m: ord(rho_X(A_1,2)) divides lcm(1,...,m)}.",
    "proofs/point_pushing_base_free_brunnian_tail.md proves every first failure for S_j with j>=b_X must be non-base; point_pushing_base_free_brunnian_tail_prefix records finite base-free prefixes.",
    "Base-free B-tail fork",
    "Prove one fixed S_m with m>=b_X has all extension rows none, or construct an infinite certified non-base tail.",
  ],
  [
    "Point-pushing base-free thresholds",
    "Replace the remaining point-pushing fork by boundedness of base-free extension thresholds epsilon_X(K).",
    "proofs/point_pushing_base_free_thresholds.md proves bounded epsilon_X(K) is equivalent to one fixed S_m passing all Brunnian extension rows; point_pushing_base_free_threshold_audit records finite rectangle approximations.",
    "Growth-threshold fork",
    "Prove sup_K epsilon_X(K)<infinity, or construct an unbounded certified non-base tail.",
  ],
  [
    "Point-pushing base-free threshold sequence",
    "Record finite prefixes of epsilon_X(K) as a weakly increasing threshold sequence.",
    "proofs/point_pushing_base_free_threshold_sequence.md proves monotonicity and distinguishes finite threshold tables from all-K boundedness; point_pushing_base_free_threshold_prefix_audit records bounded approximations.",
    "Threshold sequence audit",
    "Use the finite prefix only as diagnostics; prove boundedness or construct an unbounded tail symbolically.",
  ],
  [
    "Point-pushing Brunnian first-failure stratification",
    "Show a negative tail can be chosen with one stable non-base failure kind.",
    "proofs/point_pushing_brunnian_first_failure_stratification.md uses fixed-arity cofinality and infinite pigeonhole to reduce B to a homogeneous infinite tail of stabilizer, orbit_label, or orbit_relation failures.",
    "B-tail stratification",
    "Construct one homogeneous infinite failure tail with explicit witness words, or prove no such tail exists.",
  ],
  [
    "Point-pushing Brunnian failure certificate",
    "Turn one non-base Brunnian gate failure into a full braid-action detector-kernel mover certificate.",
    "proofs/point_pushing_brunnian_failure_certificate.md packages a stabilizer/orbit_label/orbit_relation row with a right-based word, derivative-detector identity, and moved X-tuple; point_pushing_brunnian_failure_certificate rechecks the row with the Brunnian witness certificate.",
    "Finite B-row certificate",
    "Promote these finite rows to a homogeneous infinite symmetric-tail family, or prove no such family exists.",
  ],
  [
    "Point-pushing Brunnian tail certificate prefix",
    "Package finite symmetric first-failure prefixes into detected, uncertified, and certified non-base rows.",
    "proofs/point_pushing_brunnian_tail_certificate_prefix.md records that only stabilizer/orbit_label/orbit_relation rows with checked Brunnian failure certificates are finite B-tail rows; point_pushing_brunnian_tail_certificate_prefix summarizes finite prefixes.",
    "Finite B-prefix certificate",
    "Use the prefix certificate to guide a symbolic infinite tail construction, or prove a uniform no-tail theorem.",
  ],
  [
    "Point-pushing Brunnian normalized-prefix bridge",
    "Feed a certified non-base Brunnian row into the standard symmetric normalized-law prefix checker after right stabilization.",
    "proofs/point_pushing_brunnian_normalized_prefix_bridge.md proves a valid Brunnian failure certificate for S_j gives one symmetric normalized-law prefix row; point_pushing_brunnian_normalized_prefix_audit checks the bridge.",
    "Row-to-normalized-law bridge",
    "Construct infinitely many such rows for B, or prove a fixed S_m prevents them for A.",
  ],
  [
    "Derivative detector functoriality",
    "Show the exact D_k(G) criterion is compatible with quotients, embeddings, symmetric cofinality, and product prefixes.",
    "proofs/point_pushing_derivative_functoriality.md proves coordinate equivariance for finite group homomorphisms; point_pushing_derivative_functoriality_audit checks finite instances.",
    "Functorial bridge",
    "Use symmetric groups or product-prefix groups in the marked-quotient fork without invoking ordinary law shortcuts.",
  ],
  [
    "Symmetric derivative quotient fork",
    "State the corrected global symmetric fork replacing the false ordinary-law theorem.",
    "proofs/symmetric_derivative_quotient_fork.md proves finite-rack domination is equivalent to one S_m supplying all marked quotients D_k(S_m)->P_k(X), and failure gives S_j derivative relations that form a normalized-law obstruction after right stabilization.",
    "Exact global fork",
    "Prove the all-k marked quotient theorem for every X, or construct explicit S_j derivative relations that move one X.",
  ],
  [
    "Action images",
    "Law words vanish on fixed finite action images.",
    "Fixed-image certificate implemented.",
    "Gap clarified",
    "Control rho_X,q image growth.",
  ],
  [
    "Symmetric detector",
    "Test global G_X=Sym(X) candidate.",
    "Direct known-branch filter covers all size<=3 rows; left-nondegenerate guitar branch now routes through the derived rack; direct fixed-n readout wrapper added.",
    "Candidate audit",
    "Prove all-n context factorization outside known branches or find degenerate failure.",
  ],
  [
    "Symmetric product gate",
    "Rule out product-built B2 failures of the direct Sym(X) route.",
    "Symbolic product-closure lemma, B2 failure certificate helper, cyclic B2 detector lemma, and regression helper added.",
    "Reduction ready",
    "Use to avoid product-constructed or pure two-strand false leads.",
  ],
  [
    "Image growth",
    "Measure pure-generator images as q grows.",
    "Small growth audit incl. size-3 candidate.",
    "Executable audit",
    "Find unbounded moved nonrack interval.",
  ],
  [
    "Pure-power growth",
    "Test exponent-law B route via pure-generator orders.",
    "Size<=3 and linear F2 show bounded orders.",
    "Candidate audit",
    "Need unbounded order or non-power laws.",
  ],
  [
    "Moving-variety B",
    "Finite-variety law separation.",
    "Criterion plus assigned-generator separator helper added.",
    "Proof criterion",
    "Find fixed X whose moving H_j escapes size<=j laws.",
  ],
  [
    "Fixed-variety barrier",
    "Rule out normalized-law motion when moving holonomy stays in var(G0).",
    "All-n law-variety lemma plus bounded escape helper.",
    "Reduction ready",
    "A B proof must show finite-variety escape from every fixed finite G0.",
  ],
  [
    "Diagonal B",
    "No finite detector gives law sequence.",
    "Product diagonal and right-stabilization convention audits added.",
    "Reduction ready",
    "Use only after explicit all-G detector failure.",
  ],
  [
    "Normalized-law dichotomy",
    "Show normalized-law obstruction is forced by failure of finite-rack domination.",
    "proofs/normalized_law_domination_dichotomy.md proves finite-rack domination is equivalent to one finite group-longitude detector and that failure diagonalizes to a normalized-law sequence; local residual version included.",
    "Reduction ready",
    "Still need a positive uniform endpoint/descent theorem or an explicit interval with no finite group detector.",
  ],
  [
    "Global-local normalized fork",
    "Remove global ambiguity by reducing Sawin to the local-minimal detector theorem.",
    "proofs/global_local_normalized_fork.md proves maximal chain intervals are local-minimal, local detectors descend to a global finite rack, and local detector failure diagonalizes to a normalized-law residual obstruction; local_normalized_law_prefix_witness_audit checks one supplied local prefix.",
    "Reduction ready",
    "The only remaining theorem is fixed finite detection for each local-minimal interval, especially the bi-free universal-corridor branch.",
  ],
  [
    "Symmetric detector reduction",
    "Replace arbitrary finite group detectors by symmetric group detectors.",
    "proofs/symmetric_detector_reduction.md uses the left regular embedding G -> S_m; symmetric_detector_reduction_audit records that K_{S_m} is contained in K_G.",
    "Reduction ready",
    "Positive route may construct S_m detectors; B route may diagonalize against S_j.",
  ],
  [
    "Symmetric tower monotonicity",
    "Record K_{S_M} subset K_{S_m} for M >= m.",
    "proofs/symmetric_tower_monotonicity.md proves the fixed-point inclusion argument; symmetric_tower_monotonicity_audit checks supplied braid signatures.",
    "Reduction ready",
    "Positive detector degrees are upward closed; B invisibility to S_j implies eventual invisibility to every fixed S_m.",
  ],
  [
    "Local symmetric detector dichotomy",
    "Package the final local A/B fork into fixed S_m detection versus S_j movers for every j.",
    "proofs/local_symmetric_detector_dichotomy.md proves the dichotomy; local_symmetric_tower_prefix_sequence_audit checks finite supplied prefixes.",
    "Reduction ready",
    "Still need either a uniform proof of some m(pi,Q), or a symbolic all-j construction.",
  ],
  [
    "Symmetric repair bridge",
    "Translate a successful repair-contract product detector H(pi,Q) into one symmetric detector degree.",
    "proofs/symmetric_repair_contract_bridge.md proves that if the supplied repair contract gives H, then S_m with m>=|H| also detects; symmetric_repair_contract_bridge_audit records the bridge.",
    "Reduction ready",
    "Still need the repair contract's fixed descent readout, faithful decomposition, and all-n endpoint witnesses.",
  ],
  [
    "Endpoint-family symmetric fork",
    "Convert any finite fixed endpoint group family into a symmetric detector A/B fork.",
    "proofs/endpoint_family_symmetric_fork.md; endpoint_family_symmetric_fork_audit records the common S_m cutoff and finite symmetric-tail endpoint seed-prefix shape, and endpoint_family_symmetric_seed_audit attaches one endpoint miss to a local symmetric normalized-law row.",
    "Endpoint fork",
    "Use after constructing a finite faithful endpoint family; bounded endpoint misses remain nonfinal.",
  ],
  [
    "Symmetric-tower B certificate",
    "State the simplified constructive B data after reducing to symmetric groups.",
    "proofs/symmetric_tower_counterexample_certificate.md states that witnesses invisible to S_j for every j suffice; symmetric_normalized_law_prefix_witness_audit and local_symmetric_normalized_law_prefix_witness_audit check supplied rows.",
    "Certificate format",
    "A final B proof must still construct the all-j sequence and moved tuples symbolically.",
  ],
  [
    "Normalized-law B certificate",
    "Separate constructive B data from nonconstructive all-detector failure.",
    "proofs/normalized_law_counterexample_certificate.md states the product-prefix witness format; normalized_law_prefix_witness_audit checks one supplied prefix for product invisibility, right stabilization, and moved tuples.",
    "Certificate format",
    "A final B proof must supply these prefix witnesses for every product P_j, not just a bounded detector miss.",
  ],
  [
    "Small YBE scan",
    "Screen tiny YBE tables for law-braid motion.",
    "Size-2 full, size-3 capped scan.",
    "Bounded audit",
    "Escalate beyond tiny tables.",
  ],
  [
    "Size-3 candidates",
    "Detail nonrack tables moved by commutator law braid.",
    "Report generated; affine and S3-visible.",
    "Candidate only",
    "Need all-finite-group law sequence.",
  ],
  [
    "Green branch",
    "Audit coordinate-action monoid branch choices.",
    "Atom descent closure, descent-closed rack quotient, atom inner group, and unit-lift detector criterion recorded; two-sided Green detector list now includes atom inner groups.",
    "Executable audit",
    "Prove descent closure is trivial/absorbed and endpoint-unit subgroup membership.",
  ],
  [
    "Local-minimal Green",
    "Run Green loops through congruence-cover intervals.",
    "Universal-output Green overlaps all known.",
    "Executable audit",
    "Prove all-n finite-G detection.",
  ],
  [
    "Kernel detectors",
    "Compare kernel image vs Sym blocks.",
    "No len<=4 collisions; exact n=2 closes.",
    "Executable audit",
    "Prove symmetric kernel groups suffice.",
  ],
  [
    "Dual Green",
    "Include right-coordinate Green kernel data.",
    "Opposite audit plus two-sided Sym helper.",
    "Reduction ready",
    "Prove two-sided Green detection.",
  ],
  [
    "Opposite detectability",
    "Finite-G detectability is invariant under side-opposite solution.",
    "Strand-reversal proof plus braid-action and longitude invariance tests.",
    "Reduction ready",
    "Use same detector factors on left/right dual branches.",
  ],
  [
    "Semigroup holonomy",
    "Separate group holonomy from aperiodic reset parts.",
    "Aperiodic lemma, endpoint/product expression audits with explicit product witnesses, product-unit detector, and endpoint finite-failure flags recorded.",
    "Reduction ready",
    "Display all-n residual endpoint units as longitude expressions in a fixed unit group, or prove subgroup membership directly.",
  ],
  [
    "Green holonomy gate",
    "Separate raw atom-trivial context collapse from group-like completed-context holonomy.",
    "Loop unit groups extracted; endpoint-product flags record direct membership in one detector.",
    "Executable guardrail",
    "Prove these group-like loops factor through fixed H(pi,Q), or build B in this group part.",
  ],
  [
    "Involutive/permutation",
    "Known branch finite-rack domination.",
    "T2 for involutive; C_m twist detector plus pure-longitude tests; known_branch_detector_certificate exposes G and |A_G|.",
    "Symbolic branch proof",
    "Use as closed branch in local bottleneck routing.",
  ],
  [
    "Affine tag guardrail",
    "Prevent audit-only affine_cyclic tags from closing a local interval.",
    "Regression excludes affine_cyclic from KNOWN_TOTAL_DETECTOR_TAGS; proof note added.",
    "Proof hygiene",
    "Use affine rows only via a symbolic all-n detector branch or a closed product subbranch.",
  ],
  [
    "Structure orbits",
    "Separate product invariants from orbit holonomy.",
    "Orbit factors plus correlated global image profiled.",
    "Reduction ready",
    "Detect holonomy in correlated global image.",
  ],
  [
    "Bounded-degree images",
    "Do not use rho_X(B_n) or orbit groups as n-dependent detectors.",
    "proofs/bounded_degree_action_image_limit.md records the limitation.",
    "Guardrail",
    "Replace fixed-degree images by an all-n factorization through fixed G.",
  ],
  [
    "Orbit-law obstruction",
    "Localize normalized-law B route to one structure orbit.",
    "Assigned-generator helper; Sym-law audit has 0 tiny failures.",
    "Proof criterion",
    "Upgrade orbit-local separators to all-j sequence.",
  ],
  [
    "Context retraction",
    "Two-sided context-profile congruence.",
    "Symbolic admissible; size<=3 split.",
    "Reduction ready",
    "Prove two-sided-free branch detection.",
  ],
  [
    "Coretraction",
    "Dual two-sided input-profile congruence.",
    "Symbolic admissible; bi-free size3 known.",
    "Reduction ready",
    "Prove bi-free branch detection.",
  ],
  [
    "Bi-free rank",
    "Rank/kernel profile for bi-free rows.",
    "No untagged size3 rank/kernel rows.",
    "Candidate audit",
    "Prove rank/Green dichotomy symbolically.",
  ],
  [
    "Local bottleneck",
    "Route each local interval to a branch verdict.",
    "Router records explicit known/product detectors, one product group per closed row, and closed_detector_gaps for delegated/open rows.",
    "Reduction ledger",
    "Prove genuinely-coloured product or bi-free corridor factorization, or realize B there.",
  ],
  [
    "Bi-free corridor target",
    "State exact hypotheses, fixed H(pi,Q), and B certificate.",
    "Target note added; false rack/Hurwitz shortcuts excluded; corridor helpers now accept fixed extra detector factors for quotient/known/unit components of H(pi,Q).",
    "Open theorem target",
    "Prove all-n H(pi,Q) factorization or build normalized-law escape.",
  ],
  [
    "Bi-free endpoint factorization",
    "Assemble corridor endpoint-longitude expressions into one fixed product detector.",
    "Endpoint expression/readout/action helpers build product witnesses, verify faithful rows, and separate supplied-row proof from row-coverage claims; the Artin-defect sieve now converts displayed beta(w)p(w)^-1 endpoint values into longitude-subgroup witnesses.",
    "Assembly lemma",
    "Prove the sharpened Artin-defect endpoint lemma for every target interval.",
  ],
  [
    "Artin-defect sieve",
    "Replace arbitrary endpoint-longitude search by Artin permutation defect displays.",
    "proofs/artin_defect_longitudinalization_sieve.md proves defects beta(w)p_beta(w)^-1 lie in the normal closure of recursive longitudes; endpoint_artin_defect_audit and endpoint_product_artin_defect_audit verify supplied displays.",
    "Sharper open target",
    "Display every elementary Green/corridor endpoint generator as a finite product of Artin-defect values in fixed H(pi,Q) factors.",
  ],
  [
    "Artin detector lift",
    "Turn endpoint observers with live (m,u) labels into recursive longitude expressions.",
    "proofs/artin_detector_lift_criterion.md proves the unbounded braid recursion from finite U x U row identities; artin_detector_lift_transition_audit and artin_detector_lift_braid_audit verify rows and convention.",
    "Finite row criterion",
    "Verify the detector-lift identities for every remaining Green/corridor observer row in fixed factors.",
  ],
  [
    "Atom-inner row lift",
    "Close the rack-like atom quotient inner-group detector-lift rows.",
    "proofs/atom_inner_detector_lift_rows.md proves positive rows from L_{a*b}=L_a L_b L_a^-1 and negative rows as inverse positive rows; rack_inner_detector_lift_audit and atom_quotient_inner_detector_lift_audit expose the check.",
    "Conditional closure",
    "Still prove atom descent/totality; remaining row checks are Green kernel-block, Schutzenberger, and endpoint/unit holonomy factors.",
  ],
  [
    "Green first-output defect",
    "Replace Green kernel-block/Schutzenberger row checks by one transported defect endpoint.",
    "proofs/green_first_output_defect_criterion.md proves the row normal form from g(a)g(q)=g(q^a)g(a^q); schutzenberger_kernel_defect_pushforward_audits checks kernel pushforwards.",
    "Sharper open target",
    "Pass to the defect-kernel quotient, then handle local-only and lower endpoint/unit holonomy.",
  ],
  [
    "Green defect quotient",
    "Kill all non-defect Green/Schutzenberger row motion by a fixed quotient.",
    "proofs/green_defect_kernel_quotient_detection.md quotients each observer U_C by the normal closure Def_C of its first-output defects; projected rows are exact side-opposite rack-Artin and green_defect_kernel_quotient_audit verifies the finite quotient step.",
    "Quotient closure",
    "Prove the remaining defect-kernel endpoint D_C(beta) lies in V_beta(Def_C), preferably by Artin-defect displays.",
  ],
  [
    "Green defect potential",
    "Reduce elementary Def_C defects to a finite nonabelian coboundary on retained edge-germs.",
    "proofs/green_defect_potential_coboundary.md proves d(a,q)=eta(q^a)eta(q)^-1 after choosing a base edge per defect component; green_defect_kernel_potential_audit verifies potentials lie in Def_C and all row coboundaries match.",
    "Coboundary reduction",
    "Prove the Def_C potential is principal for Artin detector transport, or extract a normalized-law cocycle escape.",
  ],
  [
    "Artin-defect abelianization",
    "Prevent an invalid elementary Artin-defect display proof for abelian defect kernels.",
    "proofs/artin_defect_abelianization_barrier.md proves Artin permutation defects land in [K,K]; the affine Green stress row has Def_C=C3 and nonidentity row defects outside [Def_C,Def_C].",
    "Proof guardrail",
    "Use full recursive-longitude membership, endpoint cancellation, or detector-lift labels for abelian defect-kernel data.",
  ],
  [
    "Green defect abelian split",
    "Separate the finite abelian defect quotient from the commutator endpoint.",
    "proofs/green_defect_abelianization_split.md records the split Def_C -> Def_C/[Def_C,Def_C]; green_defect_abelianization_split_audit verifies the projected potential coboundaries.",
    "Reduction criterion",
    "Prove ordinary finite abelian longitude visibility for the projected endpoint, then handle the commutator residual.",
  ],
  [
    "Abelian longitude image",
    "Compute V_beta(A) exactly for any fixed finite abelian target.",
    "proofs/abelian_longitude_image_criterion.md proves V_beta(A)=<a^{m_ij}> from the recursive-longitude exponent matrix; abelian_longitude_image_audit optionally checks the matrix subgroup against exhaustive enumeration.",
    "Exact criterion",
    "Apply this matrix subgroup to the projected AbDef_C endpoint, then route the remaining commutator endpoint.",
  ],
  [
    "Green balanced gauge",
    "Split raw Green/Schutzenberger first-output defects into Artin-visible commutators plus terminal gauge.",
    "proofs/green_balanced_defect_gauge_decomposition.md proves d=[A,Q]*Q(CA^-1)^-1Q^-1; row audits now expose second_output_gauge and balanced_decomposition_holds.",
    "Reduction criterion",
    "Prove terminal gauge holonomy lies in the fixed endpoint/unit longitude subgroup.",
  ],
  [
    "Terminal gauge criterion",
    "Turn terminal second-output gauge holonomy into the standard endpoint-longitude certificate target.",
    "proofs/terminal_gauge_longitudinalization_criterion.md proves the gauge telescope and records terminal_gauge_* audits that reuse endpoint expression/product witnesses.",
    "Certificate criterion",
    "Supply all-n terminal gauge certificates in fixed factors, or extract normalized-law gauge escape.",
  ],
  [
    "Terminal gauge Artin-defect target",
    "State the strongest commutator-level shortcut for the corridor branch.",
    "proofs/terminal_gauge_artin_defect_target.md records that a pure Artin-defect display would put terminal gauge endpoints in V_beta(U), but now points to the abelianization guardrail.",
    "Guarded target",
    "Use only after abelian terminal holonomy has been killed or lifted by ordinary longitude witnesses.",
  ],
  [
    "Terminal gauge abelianization barrier",
    "Prevent a false pure Artin-defect proof for abelian terminal gauge holonomy.",
    "proofs/terminal_gauge_abelianization_barrier.md proves Artin permutation defects lie in [U,U]; artin_defect_abelianization_barrier_audit reports endpoints outside [U,U].",
    "Proof guardrail",
    "Prove abelianized terminal endpoints by the abelian matrix criterion, then handle the commutator/perfect-residual correction.",
  ],
  [
    "Principal gauge extension",
    "Close lower endpoint/unit holonomy when the surviving gauge row is a principal finite rack-extension cocycle.",
    "proofs/principal_gauge_extension_detector.md proves the rack-cocycle criterion; principal_gauge_extension_detector_audit builds A x U and checks Inn(A x U) detector-lift rows.",
    "Closed subcase",
    "Prove principal-gauge normal form for every surviving corridor gauge row, or extract a nonprincipal normalized-law seed.",
  ],
  [
    "Transport-state rackification",
    "Remove principality for strand-continuing finite gauge rows by enlarging the rack state to A x E.",
    "proofs/transport_state_rackification_detector.md proves the rackification lemma; transport_state_rackification_audit builds A x E and checks Inn(A x E) detector-lift rows.",
    "Closed subcase",
    "Prove descent separation: non-strand-continuing motion is fully visible in Green/Schutzenberger readouts.",
  ],
  [
    "Continuation congruence gate",
    "Turn non-strand-continuing lower motion into a least admissible congruence closure.",
    "proofs/continuation_congruence_descent_gate.md; continuation_congruence_audit seeds x~v and reuses the generated congruence closure engine.",
    "Reduction criterion",
    "Handle the universal continuation corridor by Green/Schutzenberger visibility, or build a normalized-law escape.",
  ],
  [
    "Elementary continuation closure",
    "Rule out collective-only universal continuation in local-minimal intervals.",
    "proofs/elementary_continuation_closure.md; continuation_seed_pair_closure_audits closes each nontrivial x~v seed separately.",
    "Reduction criterion",
    "Prove Green/Schutzenberger visibility or normalized-law escape for one representative elementary continuation seed.",
  ],
  [
    "Universal continuation derivation",
    "Expose the edge-by-edge finite derivation certificate generated by one universal continuation seed.",
    "proofs/universal_continuation_derivation_certificate.md; continuation_seed_universal_derivation_audits compares edge counts with recorded derivation rows.",
    "Reduction criterion",
    "Route each derived edge through fixed Green/Schutzenberger/atom readouts, or choose one derived edge as the normalized-law seed.",
  ],
  [
    "Continuation readout propagation",
    "Show that an admissible fixed readout containing one continuation seed contains the whole generated closure.",
    "proofs/continuation_readout_propagation.md; continuation_seed_readout_propagation_audits records admissibility, seed containment, and missing generated edges.",
    "Reduction criterion",
    "Prove representative seed visibility in an admissible fixed readout; derived edges then propagate automatically.",
  ],
  [
    "Readout-kernel admissibility",
    "Certify when finite fibrewise detector labels define an admissible local congruence kernel.",
    "proofs/readout_kernel_admissibility.md; readout_kernel_audit builds the kernel family and records exact transport failures.",
    "Reduction criterion",
    "Construct fixed Green/Schutzenberger/atom/unit labels whose kernel is admissible and contains each representative continuation seed.",
  ],
  [
    "Readout descent separation",
    "Combine readout-kernel admissibility and continuation seed killing into a strand-continuing quotient certificate.",
    "proofs/readout_descent_separation_certificate.md; readout_descent_separation_audit records the kernel, propagation audits, and surviving seed rows.",
    "Reduction criterion",
    "Construct fixed detector labels that make this audit pass in every local-minimal bottleneck interval.",
  ],
  [
    "Readout quotient interval",
    "Construct the explicit finite local interval on readout-kernel blocks.",
    "proofs/readout_kernel_quotient_interval.md; quotient_interval_by_family and readout_kernel_quotient_interval build the descended local table.",
    "Reduction criterion",
    "After a passing descent-separation audit, apply transport-state rackification to the explicit strand-continuing quotient row.",
  ],
  [
    "Product readout kernels",
    "Assemble finitely many fixed detector labels into one tuple-valued readout.",
    "proofs/product_readout_kernel_assembly.md; product_readout_kernel_audit checks factor kernels, the product kernel, and the meet identity.",
    "Reduction criterion",
    "Construct Green/Schutzenberger/atom/unit factors separately, then assemble the fixed product readout for descent separation.",
  ],
  [
    "Product descent separation",
    "Track exactly which continuation seeds survive a tuple-valued product readout.",
    "proofs/product_readout_descent_separation.md; product_readout_descent_separation_audit checks factor seed survival and product descent separation.",
    "Reduction criterion",
    "Each factor must kill every representative continuation seed; one killing factor is not enough because product kernels are meets.",
  ],
  [
    "Readout seed saturation",
    "Compute the least admissible coarsening forced by one readout factor plus all continuation seeds.",
    "proofs/readout_seed_saturation.md; readout_seed_saturation_audit records saturation, new edges, and saturated descent separation.",
    "Reduction criterion",
    "In local-minimal intervals a non-killing admissible equality factor saturates to universal, so lost information must be routed elsewhere.",
  ],
  [
    "Local-minimal seed dichotomy",
    "Use local-minimality to rule out hidden proper seed-saturated quotients.",
    "proofs/local_minimal_seed_saturation_dichotomy.md; local_minimal_seed_saturation_dichotomy_audit checks the equality/universal saturation expectation.",
    "Reduction criterion",
    "Any equality-kernel factor missing a nontrivial seed collapses to universal; prove external routing for information lost by that collapse.",
  ],
  [
    "Local-minimal descent readout collapse",
    "Collapse combined descent-separating readout kernels in local-minimal intervals.",
    "proofs/local_minimal_descent_readout_collapse.md; local_minimal_descent_readout_collapse_audit checks that an admissible readout killing continuation seeds is equality with no nontrivial seeds, or universal once any nontrivial seed exists.",
    "Structural guardrail",
    "Route universal/constant-observer lost information through fixed endpoint families, or construct a normalized-law escape.",
  ],
  [
    "Lost-edge external routing",
    "Separate descent quotient labels from external labels that remember collapsed edges.",
    "proofs/lost_edge_external_routing.md; lost_edge_external_routing_audit lists lost, routed, and unrouted saturation edges.",
    "Reduction criterion",
    "Do not add routing labels back to the descent quotient; prove their fixed-factor longitude visibility separately.",
  ],
  [
    "Routed edge endpoint witnesses",
    "Attach product endpoint-longitude certificates to externally routed lost edges.",
    "proofs/routed_lost_edge_endpoint_witness.md; routed_lost_edge_endpoint_witness_audit checks routed-edge coverage by endpoint product-expression audits.",
    "Reduction criterion",
    "Every routed lost edge still needs a fixed-factor recursive-longitude witness; missing witnesses are not B without normalized laws.",
  ],
  [
    "Chart-transport collapse",
    "Avoid separate endpoint-longitude proofs for transported or chart-conjugate copies of elementary generators.",
    "proofs/chart_transport_collapse.md; conjugate_longitude_subgroup_witness shows V_beta(G) is normal at certificate level.",
    "Reduction ready",
    "Prove one representative elementary generator per finite chart-conjugacy orbit.",
  ],
  [
    "Descent separation target",
    "State the final A-route theorem: all residual endpoint motion separates into fixed Green/Sch, atom, and transport-rack readouts.",
    "proofs/descent_separation_transport_rack_closure.md records the target; later unit-continuation, mixed-unit, triangular, kink-predecessor, and master-local notes route the remaining descent-separation cases.",
    "Closed by final assembly",
    "Audit the route through proofs/master_local_residual_positive_closure.md and proofs/final_completion_audit.md.",
  ],
  [
    "Unit-continuation final obstruction",
    "Split the constant-observer universal-continuation case into nonunit impossibility and unit endpoint holonomy.",
    "proofs/unit_continuation_final_obstruction.md specializes unit_factorization_audit to Theta^cont=Nabla and K^O=Nabla.",
    "Routed by later closure",
    "Follow the two-sided unit, mixed-unit, triangular, and kink-predecessor rows to the master-local positive closure.",
  ],
  [
    "Two-sided unit collapse",
    "Split the final continuation rows into strand-continuing, two-sided unit nondegenerate, and mixed-unit context recovery.",
    "proofs/two_sided_unit_collapse.md; two_sided_unit_collapse_audit records coordinate-section units, non-two-sided rows, and mixed rows.",
    "Routed by triangular closure",
    "Mixed-unit rows pass through rank-profile and triangular reductions; two-sided unit and strand-continuing rows are closed.",
  ],
  [
    "Mixed-unit companion separation",
    "Show every noninjective coordinate-section kernel is separated by the companion output coordinate.",
    "proofs/mixed_unit_companion_separation.md; section_kernel_companion_audit records section collisions and companion outputs.",
    "Reduction criterion",
    "Route companion-shuttle edges through fixed readouts, or upgrade a shuttle cycle to normalized laws.",
  ],
  [
    "Mixed-unit rank-profile collapse",
    "Route proper section-kernel profiles through Green/Schutzenberger readouts and leave only constant-section triangular rows.",
    "proofs/rank_profile_collapse_mixed_unit.md; section_rank_profile_collapse_audit records ranks, kernel kinds, and images.",
    "Routed by triangular closure",
    "Constant-section triangular rows are handled by the triangular bundle, constant-column, Latin split, and kink-predecessor notes.",
  ],
  [
    "Triangular bundle partition",
    "Show bijective constant-section triangular rows are finite bundle partitions over the constant output map.",
    "proofs/constant_section_triangular_bundle_partition.md; triangular_bundle_audit records constant-map fibres and companion image blocks.",
    "Routed by triangular closure",
    "The recovery inverse and constant-column collapse reduce the bundle residue to Latin-unit triangular rows.",
  ],
  [
    "Triangular recovery inverse",
    "Compute the inverse of a triangular bundle row from block-label recovery plus within-block companion inverse.",
    "proofs/triangular_bundle_recovery_inverse.md; triangular_recovery_audit records output-to-source recovery entries.",
    "Routed by triangular closure",
    "Constant-column collapse and Latin YBE split remove the non-Latin recovery residue and isolate companion shear.",
  ],
  [
    "Constant-column collapse",
    "Show hidden nonunit opposite columns in triangular rows force product/permutation form, leaving only Latin-unit triangular rows.",
    "proofs/constant_column_collapse_triangular.md; triangular_column_collapse_audit records companion sections, opposite columns, product-collapse rows, and Latin-unit rows.",
    "Reduced to Latin closure",
    "Latin-unit rows are handled by the Latin YBE split, one-colour collapse, and kink-predecessor cancellation.",
  ],
  [
    "Latin triangular YBE split",
    "Separate alpha transport from companion shear in the Latin-unit triangular residue.",
    "proofs/latin_triangular_ybe_split.md; latin_triangular_ybe_audit records alpha-cocycle, middle-companion, and endpoint-shear YBE equations.",
    "Routed by kink closure",
    "Alpha transport routes to product/permutation holonomy; companion shear is eliminated by one-colour and rack-kink cancellation.",
  ],
  [
    "One-colour Latin triangular collapse",
    "Rule out nontrivial one-colour Latin-unit triangular YBE rows.",
    "proofs/one_colour_latin_triangular_collapse.md; one_color_latin_triangular_collapse_audit records alpha identity, companion identity, and rejected Latin shear candidates.",
    "Colour reduction",
    "Any remaining companion-shear obstruction must be genuinely multi-colour.",
  ],
  [
    "Kink-predecessor Latin cancellation",
    "Use rack kink predecessors to prove rack-base Latin-unit triangular rows have singleton fibres.",
    "proofs/kink_predecessor_latin_triangular_cancellation.md; rack_kink_latin_triangular_collapse_audit records rack form, kink predecessors, alpha identities, and predecessor-column constancy.",
    "Local closure input",
    "Feeds the master local positive closure by eliminating the final rack-base Latin-unit triangular obstruction.",
  ],
  [
    "Master local positive closure",
    "Assemble the fixed detector product H(pi,Q), the bi-free corridor closure, sharp obstruction step, and congruence-chain induction.",
    "proofs/master_local_residual_positive_closure.md is now treated as a candidate assembly template; proofs/proof_critic_gap_audit.md finds that the endpoint expressions, faithful decomposition, and descent separation are not yet proved.",
    "Gap found",
    "Prove uniform descent-separation and endpoint-longitudinalization, or construct normalized-law B.",
  ],
  [
    "Proof critic gap audit",
    "Record the external proof-critic rejection of the candidate A closure and identify the missing theorem package.",
    "proofs/proof_critic_gap_audit.md states that bifree endpoint factorization is conditional, descent separation remains unproved, atom descent/routing is conditional, and terminal gauge is reduced but not killed.",
    "Current gap",
    "Supply the missing fixed-factor endpoint expressions and faithful residual decomposition uniformly in n.",
  ],
  [
    "Descent-endpoint repair contract",
    "Turn the proof-critic gap into a precise sufficient theorem package.",
    "proofs/descent_endpoint_repair_contract.md proves that a fixed descent-separating readout, fixed endpoint groups, faithful reconstruction, and all-n V_beta witnesses imply the local finite-detector implication; descent_endpoint_repair_contract_audit bundles supplied certificates and rejects mismatched routed-edge descent ledgers.",
    "Repair target",
    "Construct this readout/witness package for every bottleneck interval, or extract a normalized-law counterexample from a finite failure.",
  ],
  [
    "Superseded completion audit",
    "Keep the earlier internal completion checklist as historical context only.",
    "proofs/final_completion_audit.md is marked superseded by proofs/proof_critic_gap_audit.md.",
    "Superseded",
    "Do not cite this file as outcome A without repairing the proof-critic gap.",
  ],
  [
    "Unit-continuation abelian-kernel lift",
    "Split the final unit endpoint into finite abelianization plus commutator-kernel correction.",
    "proofs/unit_continuation_abelian_kernel_lift.md; normal_quotient_longitude_lift_audit checks quotient witness, lifted witness, and kernel witness.",
    "Reduction criterion",
    "Prove abelian matrix witnesses and commutator-kernel witnesses for S_beta in the fixed unit group.",
  ],
  [
    "Unit-continuation abelian quotient audit",
    "Isolate the first finite quotient checkpoint for terminal unit endpoints.",
    "proofs/unit_continuation_abelian_quotient_audit.md; unit_composite_abelianization_audit projects the final unit composite to U/[U,U] and checks membership in V_beta of that abelian quotient.",
    "Executable criterion",
    "Use before any commutator-level Artin-defect claim; passing leaves only the commutator correction, failing gives an abelian quotient seed.",
  ],
  [
    "Unit-continuation derived series",
    "Iterate the abelian-kernel split through the finite derived series of the fixed unit group.",
    "proofs/unit_continuation_derived_series_reduction.md; derived_series_audit records solvable collapse/perfect residual, and unit_composite_derived_series_lift_audit checks supplied stage witnesses and the combined endpoint witness.",
    "Certificate criterion",
    "Supply derived quotient witnesses stage-by-stage; solvable unit groups close when the final residual is identity, nonsolvable cases need a perfect-residual witness.",
  ],
  [
    "Unit-continuation perfect residual",
    "Make the last nonsolvable terminal-unit checkpoint explicit.",
    "proofs/unit_continuation_perfect_residual_audit.md; unit_perfect_residual_longitude_audit restricts U(M) to its stable perfect residual P and tests the final residual endpoint against V_beta(P).",
    "Certificate criterion",
    "Supply a perfect-residual recursive-longitude witness, or upgrade a perfect-residual finite miss to normalized laws.",
  ],
  [
    "Perfect-residual normalized seed",
    "Attach a nonsolvable terminal-unit finite miss to one local normalized-law prefix row.",
    "proofs/unit_perfect_residual_normalized_seed.md; unit_perfect_residual_normalized_seed_audit pairs a local product-prefix row with a perfect-residual identity-signature miss and explicit same-readout assertions.",
    "B-seed certificate",
    "Use only as one row of an all-j normalized-law construction; a bounded miss remains nonfinal.",
  ],
  [
    "Perfect-residual symmetric seed",
    "Replace product-prefix bookkeeping by a symmetric-tower row for terminal perfect residual misses.",
    "proofs/unit_perfect_residual_symmetric_seed.md; unit_perfect_residual_symmetric_seed_audit checks a local S_j row, j-strand stabilization, j >= |P|, and the attached perfect-residual finite miss; unit_perfect_residual_symmetric_tower_prefix_audit checks finite tail prefixes starting at |P|.",
    "B-seed certificate",
    "Use for nonsolvable terminal-unit B attempts; an all-j family is still required.",
  ],
  [
    "Perfect-residual symmetric dichotomy",
    "Remove the third-case ambiguity for one faithful terminal perfect-residual readout channel.",
    "proofs/unit_perfect_residual_symmetric_dichotomy.md proves that either some S_m with m >= |P| kills the channel uniformly in n, or every j >= |P| supplies a symmetric-tail endpoint seed.",
    "Channel dichotomy",
    "Use with faithfulness/readout attachment; still need all endpoint channels for A or an explicit YBE interval for B.",
  ],
  [
    "Perfect-residual finite-channel fork",
    "Assemble finitely many terminal perfect-residual channels into one symmetric A/B fork.",
    "proofs/unit_perfect_residual_finite_channel_fork.md proves that either one S_M kills all terminal perfect-residual channels, or the finite family supplies an unbounded symmetric-tail normalized-law seed.",
    "Channel-family dichotomy",
    "Use for the nonsolvable terminal-unit family; still need a uniform bound for A or explicit rows for B.",
  ],
  [
    "Unit-continuation derived product detector",
    "Assemble terminal-unit derived-series certificates into one fixed product detector.",
    "proofs/unit_continuation_derived_product_detector.md; unit_composite_product_derived_series_lift_audit embeds each factor's combined witness into prod_i U(M_i) and verifies the endpoint tuple.",
    "Product certificate",
    "Use for intervals with several endpoint/unit monoids so the sharp obstruction theorem sees one fixed group.",
  ],
  [
    "Bi-free subgroup certificate",
    "Profile candidate words against fixed corridor detector factors.",
    "Helper, extra-factor target support, direct-product subgroup audit, and tests added; affine commutator seen by S3 block factor.",
    "Executable audit",
    "Upgrade finite certificates to all-n factorization or law sequence.",
  ],
  [
    "Bi-free certificate audit",
    "Apply corridor certificate to local-minimal cover corpus.",
    "Size3: 116 product_finite_g, 12 nondegenerate, 6 known_total, 0 product/corridor targets.",
    "Bounded audit",
    "Prove arbitrary-fibre theorem or find normalized-law escape.",
  ],
  [
    "Bi-free exact audit",
    "Close fixed-index image using the same corridor detector factor list.",
    "Affine stress row n=2: 12 states, no kernel/collision failure; product subgroup check matches factor product.",
    "Exact fixed-n audit",
    "Upgrade fixed-n closure to all-n corridor factorization.",
  ],
  [
    "Kernel closure",
    "Close coordinate kernels.",
    "Equality=nondegenerate; elementary kernel-pair closures must be universal in local-minimal degenerate rows.",
    "Reduction ready",
    "Control universal kernel-closure branch or refine nonminimal intervals.",
  ],
  [
    "Kernel corridor",
    "Distinguish seed-only vs transported universal closures.",
    "Size<=3: no semisplit leaks; LocalMasterBottleneckSummary now records elementary output-kernel pair counts/failures/depth.",
    "Candidate audit",
    "Prove lemma or find normalized-law escape along universal pair corridors.",
  ],
  [
    "Universal corridor target",
    "State remaining universal-kernel A/B branch.",
    "Affine depth 1 rows are involutive.",
    "Open",
    "Prove detector or find law escape.",
  ],
  [
    "Corridor-Green bridge",
    "Cross-tab universal corridors with Green hidden loops.",
    "Size<=3 overlap has 0 untagged intervals.",
    "Candidate audit",
    "Prove bridge symbolically.",
  ],
  [
    "Product-permutation",
    "Normalize swapped and direct universal branches.",
    "H_prod explicit; coboundaries telescope; closed product detector groups added to bottleneck summary.",
    "Executable audit",
    "Prove H_prod words are longitude products.",
  ],
  [
    "Swapped nondegenerate base",
    "Swapped product extension over nondegenerate quotient is nondegenerate.",
    "All-n fibre-bijection proof added; regression fixture checks the known product row.",
    "Reduction ready",
    "Route such rows to the left-nondegenerate/guitar branch, not to product holonomy.",
  ],
  [
    "Identity-base product",
    "Reduce identity-base product holonomy to swapped K_a or direct identities.",
    "Central-label/direct-trivial reducers plus cyclic detector implemented.",
    "Reduction ready",
    "Use as known product subbranch; obstruction needs non-identity colours.",
  ],
  [
    "Product closed labels",
    "Closed product holonomy as finite labels.",
    "Exact n=2 all-base audit: 0 untagged failures; known-row miss fixed by S4 factor.",
    "Exact fixed-n audit",
    "Upgrade fixed-tuple certificates to all-n product lemma.",
  ],
  [
    "Product witnesses",
    "Avoid false common-assignment shortcut.",
    "Route audit records common-assignment failure, per-label witnesses, and subgroup membership.",
    "Executable audit",
    "Use only as route bookkeeping; prove subgroup condition symbolically.",
  ],
  [
    "Product subgroup",
    "Closed labels lie in subgroup generated by longitude values.",
    "Subgroup audit implemented for product labels.",
    "Reduction criterion",
    "Prove subgroup membership for all product intervals or find failure.",
  ],
  [
    "Product primitivity",
    "Certify product local-minimality via pair closures in the label groupoid.",
    "Swapped/direct label pair-closure helpers added; no partition enumeration required.",
    "Reduction criterion",
    "Use before applying product holonomy or closed-label B route.",
  ],
  [
    "Product holonomy normalization",
    "Gauge-normalize product label words to the actual finite holonomy group.",
    "Helpers and subgroup audit added; coboundary is identity, pairwise branch is C_m-detected, and certificate groups are exposed.",
    "Reduction criterion",
    "Prove all-n longitude-subgroup membership in normalized product holonomy groups.",
  ],
  [
    "Product holonomy subgroup scan",
    "Check normalized holonomy subgroup convention in smallest arbitrary product corpus.",
    "Two-colour/two-point fibres: 92 product branch scans; 2048 nonidentity normalized holonomy rows; 0 subgroup failures.",
    "Candidate audit",
    "Search beyond fibre size 2/colour size 2 or prove normalized product holonomy theorem.",
  ],
  [
    "Product holonomy exact scan",
    "Close fixed-degree normalized holonomy images without word-length cutoff on representative rows.",
    "5 exact scenarios; 0 truncations; raw holonomy misses 1 known-branch row; adding S4 removes that miss.",
    "Candidate audit",
    "Use full detector product, not raw holonomy alone, in product theorem or B search.",
  ],
  [
    "Product subgroup scan",
    "Stress subgroup criterion in smallest arbitrary product corpus.",
    "2-colour fibre-2 all-base scan: 0 failures.",
    "Candidate audit",
    "Escalate beyond fibre size 2 or prove symbolically.",
  ],
  [
    "Closed-label B route",
    "Diagonalize failure of every closed-label detector.",
    "Obstruction criterion plus bounded helper.",
    "Reduction ready",
    "Use after explicit all-G product failure.",
  ],
  [
    "2-colour fibre-2",
    "Enumerate identity/flip-base local intervals.",
    "No unknown primitive examples.",
    "Candidate audit",
    "Search larger colour/fibre patterns.",
  ],
  [
    "2-colour fibre-2 all bases",
    "Enumerate arbitrary local tables over all 2-point bases.",
    "120 local-minimal; no untagged universal corridors.",
    "Candidate audit",
    "Escalate fibre size or prove symbolic branch.",
  ],
  [
    "2-colour fibre-3 product",
    "Enumerate S3 swapped/direct product labels.",
    "Swapped 2064/direct 24 primitive; router sends all to product_finite_g, 0 open product targets.",
    "Candidate audit",
    "Prove product-groupoid theorem.",
  ],
  [
    "3-colour fibre-2 product",
    "Enumerate S2 product labels over all size-3 quotient bases via F2 linear equations.",
    "2472 primitive rows; fibre2 affine router sends all to product_finite_g, 0 open product targets.",
    "Candidate audit",
    "Use fibre-size-two affine detector branch; prove arbitrary-fibre product-groupoid theorem.",
  ],
  [
    "Linear F2",
    "Enumerate all linear bijective maps on F2^2.",
    "97 YBE tables; no unknown primitive examples; 0 two-strand Sym-gate failures.",
    "Candidate audit",
    "Search higher-rank affine patterns.",
  ],
  [
    "Affine F2",
    "Enumerate translated affine maps on F2^2.",
    "481 YBE; depth1 universals all involutive.",
    "Candidate audit",
    "Search non-affine or higher-rank affine.",
  ],
  [
    "Affine-linear Sym stress",
    "Stress the direct Sym(X) two-strand gate in larger affine-linear families.",
    "proofs/affine_linear_direct_symmetric_stress.md records reported F2^3 and F3^2 affine-linear scans with 0 bad direct-Sym two-strand rows; every crossing order divides 2*lcm(1,...,|X|).",
    "Guardrail",
    "Do not treat this as proof; the remaining obstruction is all-n terminal gauge longitudinalization.",
  ],
  [
    "Known branches",
    "Do not re-open eliminated cases as final obstacles.",
    "Branch list recorded in proof log.",
    "Bookkept",
    "Focus on arbitrary fibres/colours.",
  ],
  [
    "Master theorem",
    "Find uniform G(pi,Q) for local-minimal interval.",
    "Kernel/Schutzenberger group candidate isolated.",
    "Open",
    "Prove detection or realize escape.",
  ],
  [
    "Counterexample path",
    "Explicit X, symbolic YBE, beta_j, moved tuple.",
    "No candidate yet.",
    "Open",
    "Search for normalized-law behavior.",
  ],
  [
    "GPT-5.5 Pro audit",
    "Ask critic before finalizing A or B.",
    "Awaiting final candidate.",
    "Pending",
    "Use Browser/Chrome for final audit.",
  ],
];

await fs.mkdir(outDir, { recursive: true });
const workbook = Workbook.create();
const sheet = workbook.worksheets.add("Reduction Audit");
sheet.getRangeByIndexes(0, 0, rows.length, rows[0].length).values = rows;
sheet.getRange("A1:E1").format = {
  fill: "#1F4E79",
  font: { bold: true, color: "#FFFFFF" },
};
sheet.getRange("A:E").format.wrapText = true;
sheet.getRange("A:A").format.columnWidthPx = 150;
sheet.getRange("B:B").format.columnWidthPx = 330;
sheet.getRange("C:C").format.columnWidthPx = 350;
sheet.getRange("D:D").format.columnWidthPx = 120;
sheet.getRange("E:E").format.columnWidthPx = 330;
sheet.getRange(`A2:E${rows.length}`).format.rowHeightPx = 64;
sheet.freezePanes.freezeRows(1);

const statusRange = sheet.getRange(`D2:D${rows.length}`);
statusRange.conditionalFormats.add("containsText", {
  text: "Open",
  format: { fill: "#FCE4D6", font: { color: "#9C0006" } },
});
statusRange.conditionalFormats.add("containsText", {
  text: "Executable",
  format: { fill: "#E2F0D9", font: { color: "#375623" } },
});
statusRange.conditionalFormats.add("containsText", {
  text: "Conditional",
  format: { fill: "#FFF2CC", font: { color: "#7F6000" } },
});

if (process.env.RENDER_PREVIEW === "1") {
  const preview = await workbook.render({
    sheetName: "Reduction Audit",
    range: `A1:E${rows.length}`,
    scale: 1,
    format: "png",
  });
  await fs.writeFile(
    path.join(outDir, "reduction_audit_preview.png"),
    new Uint8Array(await preview.arrayBuffer()),
  );
}

const errors = await workbook.inspect({
  kind: "match",
  searchTerm: "#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",
  options: { useRegex: true, maxResults: 50 },
  summary: "formula error scan",
});
console.log(errors.ndjson);

const output = await SpreadsheetFile.exportXlsx(workbook);
await output.save(outPath);
console.log(outPath);
process.exit(0);
