from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt


ROOT = Path(__file__).resolve().parents[1]
STATUS_MD = ROOT / "proofs" / "sawin_status.md"
EXTRA_MD = [ROOT / "proofs" / "progress_summary.md"]
EXTRA_MD.append(ROOT / "proofs" / "gpt55_pro_remaining_issues_prompt.md")
EXTRA_MD.append(ROOT / "proofs" / "semisplit_families.md")
EXTRA_MD.append(ROOT / "proofs" / "local_minimality_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "finite_group_longitudes.md")
EXTRA_MD.append(ROOT / "proofs" / "pairwise_linking_detector.md")
EXTRA_MD.append(ROOT / "proofs" / "finite_rack_longitude_quotient.md")
EXTRA_MD.append(ROOT / "proofs" / "sharp_obstruction_theorem.md")
EXTRA_MD.append(ROOT / "proofs" / "purity_stabilization.md")
EXTRA_MD.append(ROOT / "proofs" / "finite_longitude_factorization_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "longitude_subgroup_profile.md")
EXTRA_MD.append(ROOT / "proofs" / "longitude_subgroup_functoriality.md")
EXTRA_MD.append(ROOT / "proofs" / "longitude_subgroup_products.md")
EXTRA_MD.append(ROOT / "proofs" / "label_longitude_factorization.md")
EXTRA_MD.append(ROOT / "proofs" / "input_dependent_longitude_factorization.md")
EXTRA_MD.append(ROOT / "proofs" / "fixed_detector_action_factorization.md")
EXTRA_MD.append(ROOT / "proofs" / "fixed_detector_readout_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "detector_product_groups.md")
EXTRA_MD.append(ROOT / "proofs" / "detector_action_products.md")
EXTRA_MD.append(ROOT / "proofs" / "product_domination_closure.md")
EXTRA_MD.append(ROOT / "proofs" / "hereditary_domination_closure.md")
EXTRA_MD.append(ROOT / "proofs" / "nondegenerate_cover_obstruction.md")
EXTRA_MD.append(ROOT / "proofs" / "rack_cover_obstruction.md")
EXTRA_MD.append(ROOT / "proofs" / "residual_kernel_checks.md")
EXTRA_MD.append(ROOT / "proofs" / "quotient_image_kernel_exact_sequence.md")
EXTRA_MD.append(ROOT / "proofs" / "residual_dependency_support.md")
EXTRA_MD.append(ROOT / "proofs" / "congruence_chain_mechanics.md")
EXTRA_MD.append(ROOT / "proofs" / "master_local_dichotomy.md")
EXTRA_MD.append(ROOT / "proofs" / "bounded_obstruction_search.md")
EXTRA_MD.append(ROOT / "proofs" / "normalized_law_attempts.md")
EXTRA_MD.append(ROOT / "proofs" / "normalized_law_sequence_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "diagonal_normalized_obstruction.md")
EXTRA_MD.append(ROOT / "proofs" / "normalized_law_domination_dichotomy.md")
EXTRA_MD.append(ROOT / "proofs" / "global_local_normalized_fork.md")
EXTRA_MD.append(ROOT / "proofs" / "symmetric_detector_reduction.md")
EXTRA_MD.append(ROOT / "proofs" / "symmetric_tower_monotonicity.md")
EXTRA_MD.append(ROOT / "proofs" / "local_symmetric_detector_dichotomy.md")
EXTRA_MD.append(ROOT / "proofs" / "sawin_last_strand_law_reduction.md")
EXTRA_MD.append(ROOT / "proofs" / "fadell_neuwirth_layer_extraction_guardrail.md")
EXTRA_MD.append(ROOT / "proofs" / "rack_point_pushing_operator_label_invariant.md")
EXTRA_MD.append(ROOT / "proofs" / "rack_point_pushing_operator_label_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "finite_augmented_artin_envelope_route.md")
EXTRA_MD.append(ROOT / "proofs" / "finite_augmented_artin_envelope_route_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "finite_augmented_artin_envelope_pressure_tests.md")
EXTRA_MD.append(ROOT / "proofs" / "finite_augmented_artin_envelope_pressure_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "finite_derived_hurwitz_envelope.md")
EXTRA_MD.append(ROOT / "proofs" / "derived_hurwitz_envelope_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "degenerate_preimage_memory_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "degenerate_preimage_memory_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "edge_memory_tower_prefix.md")
EXTRA_MD.append(ROOT / "proofs" / "edge_memory_tower_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_edge_transducer_tower.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_edge_transducer_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_group_hurwitz_compression_pressure.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_group_hurwitz_compression_pressure_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_point_pushing_surface.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_point_pushing_surface_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_point_pushing_tiny_corpus.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_point_pushing_tiny_corpus_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_artin_envelope_cohomology.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_artin_envelope_cohomology_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_point_forgetting_restriction.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_point_forgetting_restriction_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_deletion_square_restriction.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_deletion_square_restriction_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_deletion_cube_restriction.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_deletion_cube_restriction_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_vertical_defect_transform.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_vertical_defect_transform_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_vertical_defect_transport.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_vertical_defect_transport_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_vertical_peiffer_square.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_vertical_peiffer_square_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_vertical_peiffer_cube_transport.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_vertical_peiffer_cube_transport_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_finite_base_pullback_gauge.md")
EXTRA_MD.append(ROOT / "proofs" / "prefix_finite_base_pullback_gauge_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "pullback_coskeletal_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "pullback_coskeletal_criterion_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "ybe_coskeletal_mechanism.md")
EXTRA_MD.append(ROOT / "proofs" / "ybe_coskeletal_mechanism_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "ybe_brunnian_derivative_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "ybe_brunnian_derivative_gate_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "ybe_crossed_square_residual_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "ybe_crossed_square_residual_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "ybe_finite_state_rack_cover_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "ybe_finite_state_rack_cover_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "ybe_equivariant_reconstruction_closure.md")
EXTRA_MD.append(ROOT / "proofs" / "ybe_equivariant_reconstruction_closure_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "transport_isomorphic_gluing_boundary.md")
EXTRA_MD.append(ROOT / "proofs" / "ybe_guitar_decoder_boundary.md")
EXTRA_MD.append(ROOT / "proofs" / "ybe_guitar_decoder_boundary_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "ybe_inverse_branch_determinization_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "ybe_inverse_branch_determinization_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_action_image_variety.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_fixed_variety_domination.md")
EXTRA_MD.append(ROOT / "proofs" / "last_strand_law_gap_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_kernel_layer_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_product_prefix_obstruction.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_product_prefix_first_failure_stratification.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_action_quotient_separation.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_monolithic_compression.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_chief_layer_tail_split.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_monolith_type_split.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_abelian_monolith_split.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_central_monolith_depth.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_cyclic_p_power_tail.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_cyclic_tail_closure.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_bounded_normal_generator_tail.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_abelian_chief_relation_module.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_abelian_relation_action_split.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_central_stem_relation_tail.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_module_prime_characteristic_split.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_active_module_generator_split.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_centralizer_layer_commutator_split.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_abelian_centralizer_layer_prime_bound.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_centralizer_stem_multiplier_tail.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_centralizer_stem_noncyclic_quotient.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_centralizer_stem_transport_split.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_internal_stem_abelianization_bound.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_transport_residual_quotient_split.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_transport_residual_abelianization_bound.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_nonabelian_chief_relation_quotient.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_nonabelian_wreath_coordinate_lift.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_noncentral_module_tail.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_nonabelian_monolith_tail.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_marked_quotient_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_paired_graph_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_vertical_witness_certificate.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_fixed_arity_cofinality.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_mu_boundedness_dichotomy.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_mu_functoriality.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_suffix_shuttle_normal_form.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_recursive_conjugacy.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_jump_normalization.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_brunnian_orbit_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_brunnian_relation_lift.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_brunnian_stabilizer_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_brunnian_orbit_quotient_certificate.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_brunnian_gate_induction.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_base_arity_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_base_free_brunnian_tail.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_base_free_thresholds.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_base_free_threshold_sequence.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_brunnian_first_failure_stratification.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_brunnian_failure_certificate.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_brunnian_tail_certificate_prefix.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_brunnian_normalized_prefix_bridge.md")
EXTRA_MD.append(ROOT / "proofs" / "point_pushing_derivative_functoriality.md")
EXTRA_MD.append(ROOT / "proofs" / "symmetric_derivative_quotient_fork.md")
EXTRA_MD.append(ROOT / "proofs" / "symmetric_repair_contract_bridge.md")
EXTRA_MD.append(ROOT / "proofs" / "normalized_law_counterexample_certificate.md")
EXTRA_MD.append(ROOT / "proofs" / "symmetric_tower_counterexample_certificate.md")
EXTRA_MD.append(ROOT / "proofs" / "endpoint_family_symmetric_fork.md")
EXTRA_MD.append(ROOT / "proofs" / "pure_braid_law_embedding.md")
EXTRA_MD.append(ROOT / "proofs" / "action_image_law_obstruction.md")
EXTRA_MD.append(ROOT / "proofs" / "moving_variety_counterexample_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "fixed_variety_barrier.md")
EXTRA_MD.append(ROOT / "proofs" / "assigned_generator_law_separation.md")
EXTRA_MD.append(ROOT / "proofs" / "moving_action_images.md")
EXTRA_MD.append(ROOT / "proofs" / "symmetric_detector_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "universal_symmetric_detector_target.md")
EXTRA_MD.append(ROOT / "proofs" / "direct_symmetric_known_branches.md")
EXTRA_MD.append(ROOT / "proofs" / "two_strand_symmetric_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "two_strand_known_branch_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "two_strand_guitar_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "two_strand_product_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "pure_power_growth_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "rack_full_twist_order_bound.md")
EXTRA_MD.append(ROOT / "proofs" / "coxeter_vs_full_twist_guardrail.md")
EXTRA_MD.append(ROOT / "proofs" / "coordinate_dependency_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "small_ybe_law_search.md")
EXTRA_MD.append(ROOT / "proofs" / "size3_candidate_detail.md")
EXTRA_MD.append(ROOT / "proofs" / "green_branch_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "green_atom_quotient_layer.md")
EXTRA_MD.append(ROOT / "proofs" / "green_atom_descent_closure.md")
EXTRA_MD.append(ROOT / "proofs" / "green_atom_rack_lift_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "local_minimal_green_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "kernel_detector_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "dual_green_symmetry.md")
EXTRA_MD.append(ROOT / "proofs" / "opposite_detectability_closure.md")
EXTRA_MD.append(ROOT / "proofs" / "green_detector_group_candidate.md")
EXTRA_MD.append(ROOT / "proofs" / "finite_semigroup_holonomy_route.md")
EXTRA_MD.append(ROOT / "proofs" / "rees_rectangle_cocycle_flatness_target.md")
EXTRA_MD.append(ROOT / "proofs" / "rees_rectangle_cocycle_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "rees_braid_cocycle_obstruction_pattern.md")
EXTRA_MD.append(ROOT / "proofs" / "rees_braid_cocycle_obstruction_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_holonomy_longitude_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_factorization_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_composite_longitude_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_composite_longitude_route_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "endpoint_longitude_expression_certificate.md")
EXTRA_MD.append(ROOT / "proofs" / "endpoint_unit_dichotomy.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_section_detection_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_section_product_detector.md")
EXTRA_MD.append(ROOT / "proofs" / "green_holonomy_factorization_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "green_section_transport_rigidity_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "green_section_transport_rigidity_gate_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "green_section_transport_prefix.md")
EXTRA_MD.append(ROOT / "proofs" / "green_section_transport_prefix_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "involutive_permutation_detector.md")
EXTRA_MD.append(ROOT / "proofs" / "affine_cyclic_guardrail.md")
EXTRA_MD.append(ROOT / "proofs" / "structure_orbit_reduction.md")
EXTRA_MD.append(ROOT / "proofs" / "structure_orbit_holonomy_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "structure_orbit_law_obstruction.md")
EXTRA_MD.append(ROOT / "proofs" / "bounded_degree_action_image_limit.md")
EXTRA_MD.append(ROOT / "proofs" / "symmetric_law_separator_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "left_nondegenerate_guitar_branch.md")
EXTRA_MD.append(ROOT / "proofs" / "retraction_dichotomy.md")
EXTRA_MD.append(ROOT / "proofs" / "coretraction_dichotomy.md")
EXTRA_MD.append(ROOT / "proofs" / "context_retraction_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "kernel_closure_dichotomy.md")
EXTRA_MD.append(ROOT / "proofs" / "kernel_corridor_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "universal_corridor_target.md")
EXTRA_MD.append(ROOT / "proofs" / "corridor_green_bridge.md")
EXTRA_MD.append(ROOT / "proofs" / "bifree_rank_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "local_master_bottleneck_ledger.md")
EXTRA_MD.append(ROOT / "proofs" / "bifree_universal_corridor_factorization_target.md")
EXTRA_MD.append(ROOT / "proofs" / "bifree_corridor_endpoint_factorization.md")
EXTRA_MD.append(ROOT / "proofs" / "artin_defect_longitudinalization_sieve.md")
EXTRA_MD.append(ROOT / "proofs" / "artin_detector_lift_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "atom_inner_detector_lift_rows.md")
EXTRA_MD.append(ROOT / "proofs" / "green_first_output_defect_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "green_defect_kernel_quotient_detection.md")
EXTRA_MD.append(ROOT / "proofs" / "green_defect_potential_coboundary.md")
EXTRA_MD.append(ROOT / "proofs" / "artin_defect_abelianization_barrier.md")
EXTRA_MD.append(ROOT / "proofs" / "green_defect_abelianization_split.md")
EXTRA_MD.append(ROOT / "proofs" / "abelian_longitude_image_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "green_balanced_defect_gauge_decomposition.md")
EXTRA_MD.append(ROOT / "proofs" / "terminal_gauge_longitudinalization_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "terminal_gauge_artin_defect_target.md")
EXTRA_MD.append(ROOT / "proofs" / "terminal_gauge_abelianization_barrier.md")
EXTRA_MD.append(ROOT / "proofs" / "principal_gauge_extension_detector.md")
EXTRA_MD.append(ROOT / "proofs" / "transport_state_rackification_detector.md")
EXTRA_MD.append(ROOT / "proofs" / "continuation_congruence_descent_gate.md")
EXTRA_MD.append(ROOT / "proofs" / "elementary_continuation_closure.md")
EXTRA_MD.append(ROOT / "proofs" / "universal_continuation_derivation_certificate.md")
EXTRA_MD.append(ROOT / "proofs" / "continuation_readout_propagation.md")
EXTRA_MD.append(ROOT / "proofs" / "readout_kernel_admissibility.md")
EXTRA_MD.append(ROOT / "proofs" / "readout_descent_separation_certificate.md")
EXTRA_MD.append(ROOT / "proofs" / "local_minimal_descent_readout_collapse.md")
EXTRA_MD.append(ROOT / "proofs" / "readout_kernel_quotient_interval.md")
EXTRA_MD.append(ROOT / "proofs" / "product_readout_kernel_assembly.md")
EXTRA_MD.append(ROOT / "proofs" / "product_readout_descent_separation.md")
EXTRA_MD.append(ROOT / "proofs" / "readout_seed_saturation.md")
EXTRA_MD.append(ROOT / "proofs" / "local_minimal_seed_saturation_dichotomy.md")
EXTRA_MD.append(ROOT / "proofs" / "lost_edge_external_routing.md")
EXTRA_MD.append(ROOT / "proofs" / "routed_lost_edge_endpoint_witness.md")
EXTRA_MD.append(ROOT / "proofs" / "chart_transport_collapse.md")
EXTRA_MD.append(ROOT / "proofs" / "descent_separation_transport_rack_closure.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_continuation_final_obstruction.md")
EXTRA_MD.append(ROOT / "proofs" / "two_sided_unit_collapse.md")
EXTRA_MD.append(ROOT / "proofs" / "mixed_unit_companion_separation.md")
EXTRA_MD.append(ROOT / "proofs" / "rank_profile_collapse_mixed_unit.md")
EXTRA_MD.append(ROOT / "proofs" / "constant_section_triangular_bundle_partition.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_bundle_recovery_inverse.md")
EXTRA_MD.append(ROOT / "proofs" / "constant_column_collapse_triangular.md")
EXTRA_MD.append(ROOT / "proofs" / "latin_triangular_ybe_split.md")
EXTRA_MD.append(ROOT / "proofs" / "one_colour_latin_triangular_collapse.md")
EXTRA_MD.append(ROOT / "proofs" / "kink_predecessor_latin_triangular_cancellation.md")
EXTRA_MD.append(ROOT / "proofs" / "master_local_residual_positive_closure.md")
EXTRA_MD.append(ROOT / "proofs" / "final_completion_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "proof_critic_gap_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "descent_endpoint_repair_contract.md")
EXTRA_MD.append(ROOT / "proofs" / "finite_linear_overlap_resolution.md")
EXTRA_MD.append(ROOT / "proofs" / "overlap_resolution_verdict.md")
EXTRA_MD.append(ROOT / "proofs" / "nonlinear_overlap_reduction_after_linear_closure.md")
EXTRA_MD.append(ROOT / "proofs" / "nonlinear_overlap_refined_obstruction.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_recovery_unit_observer.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_recovery_detector_lift_fork.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_recovery_longitude_expression_certificate.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_recovery_derived_series_fork.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_recovery_symmetric_endpoint_fork.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_recovery_kink_completion_deficit.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_recovery_side_dual_completion.md")
EXTRA_MD.append(ROOT / "proofs" / "right_rack_kink_latin_triangular_cancellation.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_latin_ybe_projection_consistency.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_k_left_defect_ledger.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_k_left_kernel_closure.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_k_left_structural_independence.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_k_left_recovery_routing.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_k_left_missing_row_profile.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_k_left_rack_cardinality_closure.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_k_left_coordinate_unit_routing.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_k_left_partial_constant_closure.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_k_left_partial_constant_continuation_route.md")
EXTRA_MD.append(ROOT / "proofs" / "triangular_k_left_side_dual_replacement_ledger.md")
EXTRA_MD.append(ROOT / "proofs" / "universal_continuation_identity_routing.md")
EXTRA_MD.append(ROOT / "proofs" / "universal_continuation_identity_endpoint_witness.md")
EXTRA_MD.append(ROOT / "proofs" / "universal_continuation_symmetric_endpoint_fork.md")
EXTRA_MD.append(ROOT / "proofs" / "mixed_unit_context_symmetric_endpoint_fork.md")
EXTRA_MD.append(ROOT / "proofs" / "post_linear_remaining_finite_system.md")
EXTRA_MD.append(ROOT / "proofs" / "post_linear_completion_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_continuation_abelian_kernel_lift.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_continuation_abelian_quotient_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_continuation_derived_series_reduction.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_continuation_perfect_residual_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_perfect_residual_normalized_seed.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_perfect_residual_symmetric_seed.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_perfect_residual_symmetric_dichotomy.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_perfect_residual_finite_channel_fork.md")
EXTRA_MD.append(ROOT / "proofs" / "unit_continuation_derived_product_detector.md")
EXTRA_MD.append(ROOT / "proofs" / "bifree_corridor_subgroup_certificate.md")
EXTRA_MD.append(ROOT / "proofs" / "bifree_corridor_certificate_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "bifree_corridor_exact_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "product_permutation_branch.md")
EXTRA_MD.append(ROOT / "proofs" / "swapped_product_nondegenerate_base.md")
EXTRA_MD.append(ROOT / "proofs" / "product_label_words.md")
EXTRA_MD.append(ROOT / "proofs" / "product_label_group_detector.md")
EXTRA_MD.append(ROOT / "proofs" / "product_holonomy_normalization.md")
EXTRA_MD.append(ROOT / "proofs" / "product_closed_label_cocycle.md")
EXTRA_MD.append(ROOT / "proofs" / "product_longitude_witness_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "product_longitude_route_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "product_longitude_subgroup_criterion.md")
EXTRA_MD.append(ROOT / "proofs" / "product_holonomy_subgroup_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "product_holonomy_exact_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "product_subgroup_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "product_exact_closed_label_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "product_closed_label_obstruction.md")
EXTRA_MD.append(ROOT / "proofs" / "product_coboundary_telescope.md")
EXTRA_MD.append(ROOT / "proofs" / "fibre2_product_branch.md")
EXTRA_MD.append(ROOT / "proofs" / "product_holonomy_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "identity_base_product_branch.md")
EXTRA_MD.append(ROOT / "proofs" / "one_colour_product_branch.md")
EXTRA_MD.append(ROOT / "proofs" / "two_colour_fibre2_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "two_colour_fibre2_all_bases_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "two_colour_fibre3_product_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "three_colour_fibre2_product_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "linear_f2_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "affine_f2_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "affine_f2_full_twist_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "affine_f2_point_pushing_audit.md")
EXTRA_MD.append(ROOT / "proofs" / "affine_linear_direct_symmetric_stress.md")
OUT = ROOT / "proofs" / "sawin_proof_log.docx"


def add_markdownish(document: Document, text: str) -> None:
    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        if not line:
            document.add_paragraph()
            continue
        if line.startswith("# "):
            document.add_heading(line[2:], level=0)
        elif line.startswith("## "):
            document.add_heading(line[3:], level=1)
        elif line.startswith("### "):
            document.add_heading(line[4:], level=2)
        elif line.startswith("- "):
            document.add_paragraph(line[2:], style="List Bullet")
        elif line.startswith("> "):
            p = document.add_paragraph(line[2:])
            p.paragraph_format.left_indent = Inches(0.25)
            for run in p.runs:
                run.italic = True
        else:
            document.add_paragraph(line)


def main() -> None:
    document = Document()
    section = document.sections[0]
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.8)
    section.left_margin = Inches(0.9)
    section.right_margin = Inches(0.9)

    styles = document.styles
    styles["Normal"].font.name = "Arial"
    styles["Normal"].font.size = Pt(10)
    styles["Heading 1"].font.name = "Arial"
    styles["Heading 1"].font.size = Pt(16)
    styles["Heading 2"].font.name = "Arial"
    styles["Heading 2"].font.size = Pt(12)

    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title.add_run("Sawin finite-rack domination proof log")
    title_run.bold = True
    title_run.font.name = "Arial"
    title_run.font.size = Pt(18)
    subtitle = document.add_paragraph("Working audit generated from proofs/*.md")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    document.add_paragraph()
    add_markdownish(document, STATUS_MD.read_text(encoding="utf-8"))
    for extra in EXTRA_MD:
        document.add_page_break()
        add_markdownish(document, extra.read_text(encoding="utf-8"))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    document.save(OUT)
    print(OUT)


if __name__ == "__main__":
    main()
