import json
import sys
from dataclasses import asdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from ybe_domination import (  # noqa: E402
    FiniteBraidedSet,
    prefix_edge_transducer_audit,
)


OUT_JSON = ROOT / "proofs" / "prefix_edge_transducer_audit.json"
OUT_MD = ROOT / "proofs" / "prefix_edge_transducer_audit.md"


def _audit_dict(name, solution, audit):
    row = asdict(audit)
    row["name"] = name
    row["table"] = {repr(key): value for key, value in solution.R.items()}
    row["all_generator_updates_bijective"] = (
        audit.all_generator_updates_bijective
    )
    row["all_point_forgetting_maps_well_defined"] = (
        audit.all_point_forgetting_maps_well_defined
    )
    row["verifies_prefix_edge_transducer_prefix"] = (
        audit.verifies_prefix_edge_transducer_prefix
    )
    return row


def build_report():
    nondegenerate_prefix_witness = FiniteBraidedSet(
        (0, 1),
        {
            (0, 0): (1, 0),
            (0, 1): (0, 0),
            (1, 0): (1, 1),
            (1, 1): (0, 1),
        },
    )
    degenerate_identity = FiniteBraidedSet(
        (0, 1),
        {
            (0, 0): (0, 0),
            (0, 1): (0, 1),
            (1, 0): (1, 0),
            (1, 1): (1, 1),
        },
    )
    rows = []
    for name, solution in (
        ("nondegenerate_prefix_witness", nondegenerate_prefix_witness),
        ("degenerate_identity_prefix_transducer", degenerate_identity),
    ):
        rows.append(
            _audit_dict(name, solution, prefix_edge_transducer_audit(solution))
        )
    report = {
        "description": (
            "Finite left-prefix path-transducer audit for degenerate memory."
        ),
        "rows": rows,
    }
    OUT_JSON.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    OUT_MD.write_text(render_markdown(report), encoding="utf-8")
    return report


def render_markdown(report):
    lines = [
        "# Prefix edge transducer audit",
        "",
        "Date: 2026-06-03",
        "",
        "This generated audit checks the finite left-prefix path transducer",
        "suggested by the degenerate-memory pressure test.  The prefix",
        "monoid is generated by the first-coordinate maps `lambda_x`, and",
        "a tuple is encoded by edges `(P,x,P lambda_x)`.  The audit checks",
        "the left-prefix identity, arity-three braid relation, arity-four",
        "generator bijectivity, and point-forgetting maps with fibre sizes",
        "bounded by `|X|`.",
        "",
        "This is not yet the group-Hurwitz quotient required by the finite",
        "augmented Artin-envelope lemma.  It is a finite transducer tower",
        "whose remaining obstruction is whether the prefix monoid memory",
        "can be compressed into one fixed finite group-Hurwitz base plus",
        "bounded-exponent vertical noise.",
        "",
        "## Rows",
        "",
    ]
    for row in report["rows"]:
        lines.extend(
            [
                f"### {row['name']}",
                "",
                f"- element count: `{row['element_count']}`;",
                (
                    "- left-prefix monoid size: "
                    f"`{row['left_prefix_monoid_size']}`;"
                ),
                f"- edge state count: `{row['edge_state_count']}`;",
                f"- arity-3 path count: `{row['arity3_path_count']}`;",
                f"- arity-4 path count: `{row['arity4_path_count']}`;",
                (
                    "- arity-3 encoding injective: "
                    f"`{row['arity3_encoding_injective']}`;"
                ),
                (
                    "- arity-4 encoding injective: "
                    f"`{row['arity4_encoding_injective']}`;"
                ),
                (
                    "- left-prefix identity holds: "
                    f"`{row['left_prefix_identity_holds']}`;"
                ),
                (
                    "- generator updates bijective: "
                    f"`{tuple(tuple(item) for item in row['generator_updates_bijective'])}`;"
                ),
                (
                    "- braid relation on prefix paths: "
                    f"`{row['braid_relation_on_prefix_paths']}`;"
                ),
                (
                    "- point-forgetting maps well-defined: "
                    f"`{tuple(tuple(item) for item in row['point_forgetting_well_defined'])}`;"
                ),
                (
                    "- point-forgetting max fibre sizes: "
                    f"`{tuple(tuple(item) for item in row['point_forgetting_max_fibre_sizes'])}`;"
                ),
                (
                    "- forgetting fibres bounded by element count: "
                    f"`{row['forgetting_fibres_bounded_by_element_count']}`;"
                ),
                (
                    "- verifies prefix-edge transducer prefix: "
                    f"`{row['verifies_prefix_edge_transducer_prefix']}`."
                ),
                "",
            ]
        )
    lines.extend(
        [
            "## Meaning",
            "",
            "The prefix-edge transducer is a finite, canonical way to run",
            "degenerate braid moves without choosing inverse images of",
            "noninjective `lambda_x` maps.  It records real ordered-neighbour",
            "memory and updates interior forgetting by rescanning prefixes.",
            "The next route-(1) gate is sharper: either group-complete this",
            "finite transducer into a fixed finite group-Hurwitz tower, or",
            "find a finite degenerate solution whose `Q_X(3), Q_X(4), ...`",
            "vertical behaviour cannot be absorbed by bounded-exponent",
            "noise over any fixed group-Hurwitz base.",
            "",
        ]
    )
    return "\n".join(lines)


def main():
    report = build_report()
    print(OUT_JSON)
    print(OUT_MD)
    print(json.dumps(report["rows"], sort_keys=True))


if __name__ == "__main__":
    main()
