import json
import sys
from dataclasses import asdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from ybe_domination import green_section_transport_rigidity_gate_audit  # noqa: E402


OUT_JSON = ROOT / "proofs" / "green_section_transport_rigidity_gate_audit.json"
OUT_MD = ROOT / "proofs" / "green_section_transport_rigidity_gate_audit.md"


def build_report():
    audit = green_section_transport_rigidity_gate_audit()
    report = asdict(audit)
    report["case_keys"] = audit.case_keys
    report["records_green_section_transport_rigidity_gate"] = (
        audit.records_green_section_transport_rigidity_gate
    )
    OUT_JSON.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    OUT_MD.write_text(render_markdown(report), encoding="utf-8")
    return report


def render_markdown(report):
    lines = [
        "# Green section transport rigidity gate audit",
        "",
        "Date: 2026-06-03",
        "",
        "This generated audit records the precise decision point for the",
        "Green/corridor section-holonomy problem.  The comparison of hidden",
        "section branches must be made inside the actual deterministic",
        "completed-context category generated by supported YBE rows.  Raw",
        "Green, Rees, or Schutzenberger coordinate normalization is not enough.",
        "",
        "## Flags",
        "",
        (
            "- actual supported transport required: "
            f"`{report['actual_supported_transport_required']}`;"
        ),
        (
            "- raw Rees/Schutzenberger shortcut rejected: "
            f"`{report['raw_rees_normalization_rejected']}`;"
        ),
        (
            "- recurrent hidden component required: "
            f"`{report['recurrent_hidden_component_required']}`;"
        ),
        (
            "- cyclic p-primary fibre required: "
            f"`{report['cyclic_p_primary_fibre_required']}`;"
        ),
        (
            "- positive rigidity condition recorded: "
            f"`{report['positive_rigidity_condition_recorded']}`;"
        ),
        (
            "- negative countercertificate recorded: "
            f"`{report['negative_countercertificate_recorded']}`;"
        ),
        (
            "- finite-depth group gate connected: "
            f"`{report['finite_depth_group_gate_connected']}`;"
        ),
        (
            "- records Green section transport rigidity gate: "
            f"`{report['records_green_section_transport_rigidity_gate']}`."
        ),
        "",
        "## Formulas",
        "",
        f"- actual transport: `{report['actual_transport_formula']}`;",
        f"- positive rigidity: `{report['positive_rigidity_formula']}`;",
        f"- countercertificate: `{report['countercertificate_formula']}`.",
        "",
        "## Rows",
        "",
    ]
    for case in report["cases"]:
        lines.extend(
            [
                f"### {case['key']}",
                "",
                f"- role: `{case['role']}`;",
                f"- statement: {case['statement']};",
                f"- consequence: {case['consequence']}.",
                "",
            ]
        )
    lines.extend(
        [
            "## Meaning",
            "",
            "A positive proof must show actual-transport rigidity: if two",
            "admissible section branches are connected by a supported completed",
            "context transport and keep the same recurrent hidden component",
            "alive, then they induce the same unit on the cyclic p-primary",
            "section quotient.",
            "",
            "A negative proof must construct the corresponding objectwise",
            "countercertificate: a finite bijective YBE solution, a full regular",
            "Green class, actual comparable hidden section branches, and unequal",
            "automorphisms in `Aut(C_{p^m})`.  Formal Green or Schutzenberger",
            "motion is not sufficient.",
            "",
        ]
    )
    return "\n".join(lines)


def main():
    report = build_report()
    print(OUT_JSON)
    print(OUT_MD)
    print(
        json.dumps(
            {
                "case_keys": report["case_keys"],
                "records": report["records_green_section_transport_rigidity_gate"],
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
