import json
import sys
from dataclasses import asdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from ybe_domination import ybe_crossed_square_residual_audit  # noqa: E402


OUT_JSON = ROOT / "proofs" / "ybe_crossed_square_residual_audit.json"
OUT_MD = ROOT / "proofs" / "ybe_crossed_square_residual_audit.md"


def build_report():
    audit = ybe_crossed_square_residual_audit()
    report = asdict(audit)
    report["case_keys"] = audit.case_keys
    report["records_crossed_square_residual_criterion"] = (
        audit.records_crossed_square_residual_criterion
    )
    OUT_JSON.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    OUT_MD.write_text(render_markdown(report), encoding="utf-8")
    return report


def render_markdown(report):
    lines = [
        "# YBE crossed-square residual audit",
        "",
        "Date: 2026-06-03",
        "",
        "This generated audit records the crossed-square algebra behind the",
        "residual double-deletion quotient from the Brunnian derivative gate.",
        "The quotient is not just a loose remainder: it has a boundary part and",
        "a Moore-Peiffer cycle part.  A positive finite-operator proof must kill",
        "both, while a counterexample must leave one of them nonzero after",
        "edge degeneracies, Peiffer mutual terms, and fixed-base pullback are",
        "removed.",
        "",
        "## Flags",
        "",
        (
            "- crossed-square model identified: "
            f"`{report['crossed_square_model_identified']}`;"
        ),
        (
            "- edge-degenerate subgroup identified: "
            f"`{report['edge_degenerate_subgroup_identified']}`;"
        ),
        (
            "- Peiffer mutual subgroup identified: "
            f"`{report['peiffer_mutual_subgroup_identified']}`;"
        ),
        (
            "- fixed-base pullback subgroup identified: "
            f"`{report['fixed_base_pullback_subgroup_identified']}`;"
        ),
        (
            "- residual exact sequence recorded: "
            f"`{report['residual_exact_sequence_recorded']}`;"
        ),
        (
            "- boundary obstruction identified: "
            f"`{report['boundary_obstruction_identified']}`;"
        ),
        (
            "- Moore-Peiffer obstruction identified: "
            f"`{report['moore_peiffer_obstruction_identified']}`;"
        ),
        (
            "- Peiffer-complete vanishing theorem recorded: "
            f"`{report['peiffer_complete_vanishing_theorem_recorded']}`;"
        ),
        (
            "- obstruction invariant form recorded: "
            f"`{report['obstruction_invariant_form_recorded']}`;"
        ),
        (
            "- records crossed-square residual criterion: "
            f"`{report['records_crossed_square_residual_criterion']}`."
        ),
        "",
        "## Formulas",
        "",
        f"- crossed-square vertices: `{tuple(report['crossed_square_vertices'])}`;",
        f"- residual quotient: `{report['residual_quotient_formula']}`;",
        f"- exact sequence: `{report['exact_sequence_formula']}`;",
        f"- boundary obstruction: `{report['boundary_obstruction_formula']}`;",
        f"- Moore-Peiffer obstruction: `{report['moore_peiffer_obstruction_formula']}`;",
        f"- compact vanishing: `{report['compact_vanishing_formula']}`;",
        f"- countercertificate invariant: `{report['obstruction_invariant_formula']}`.",
        "",
        "## Rows",
        "",
    ]
    for case in report["cases"]:
        lines.extend(
            [
                f"### {case['key']}",
                "",
                f"- role: `{case['role']}`;",
                f"- statement: {case['statement']};",
                f"- consequence: {case['consequence']}.",
                "",
            ]
        )
    lines.extend(
        [
            "## Meaning",
            "",
            "The double-deletion residual quotient `R_{p,q}^I` is controlled by",
            "a crossed square.  The boundary quotient detects Brunnian",
            "bisections whose one-face boundary is not generated by edge,",
            "Peiffer, or base terms.  The Moore-Peiffer quotient detects",
            "square-internal cycles invisible on both one-deletion faces.",
            "",
            "Thus the positive route is now Peiffer-completeness of the",
            "finite labelled deletion square.  The negative route is a family",
            "of invariants `chi_I` on the Moore kernel that vanish on edge,",
            "Peiffer, and base pullback subgroups but not on a chosen",
            "high-arity Brunnian class.",
            "",
        ]
    )
    return "\n".join(lines)


def main():
    report = build_report()
    print(OUT_JSON)
    print(OUT_MD)
    print(
        json.dumps(
            {
                "case_keys": report["case_keys"],
                "records": report["records_crossed_square_residual_criterion"],
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
