from __future__ import annotations

import json
import sys
from collections import Counter
from itertools import combinations
from pathlib import Path
from typing import Sequence

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "tools"))

from run_affine_f2_audit import affine_solution  # noqa: E402
from run_affine_f2_q3_pressure_audit import (  # noqa: E402
    DIMENSION,
    _block_matrix,
    _entry,
    _linear_ybe_block_rows,
    _matrix_rank,
    _matrix_signature,
    _precompute_products,
    _right_multiplication_solutions,
)
from ybe_domination import (  # noqa: E402
    FiniteBraidedSet,
    branch_tags,
    one_state_invariant_observer_partition,
    proper_subsolution_subsets,
    small_rack_prefix_obstruction_rows,
)

OUT_JSON = ROOT / "proofs" / "affine_f2_q3_rigid_pressure_core_audit.json"
OUT_MD = ROOT / "proofs" / "affine_f2_q3_rigid_pressure_core_audit.md"


def _row_bits(block: int, row: int) -> int:
    return sum(_entry(block, row, col) << col for col in range(DIMENSION))


def _l12_rows(blocks: tuple[int, int, int, int]) -> tuple[int, ...]:
    a_block, b_block, c_block, d_block = blocks
    rows = []
    for row in range(DIMENSION):
        rows.append(_row_bits(a_block, row) | (_row_bits(b_block, row) << DIMENSION))
    for row in range(DIMENSION):
        rows.append(_row_bits(c_block, row) | (_row_bits(d_block, row) << DIMENSION))
    for row in range(DIMENSION):
        rows.append(1 << (2 * DIMENSION + row))
    return tuple(rows)


def _l23_rows(blocks: tuple[int, int, int, int]) -> tuple[int, ...]:
    a_block, b_block, c_block, d_block = blocks
    rows = tuple(1 << row for row in range(DIMENSION))
    shifted = []
    for row in range(DIMENSION):
        shifted.append(
            (_row_bits(a_block, row) << DIMENSION)
            | (_row_bits(b_block, row) << (2 * DIMENSION))
        )
    for row in range(DIMENSION):
        shifted.append(
            (_row_bits(c_block, row) << DIMENSION)
            | (_row_bits(d_block, row) << (2 * DIMENSION))
        )
    return rows + tuple(shifted)


def _matrix_vector(rows: tuple[int, ...], vector: int) -> int:
    output = 0
    for row_index, mask in enumerate(rows):
        if (mask & vector).bit_count() & 1:
            output |= 1 << row_index
    return output


def _matrix_product(
    left_rows: tuple[int, ...],
    right_rows: tuple[int, ...],
) -> tuple[int, ...]:
    output = []
    for mask in left_rows:
        row = 0
        index = 0
        active = mask
        while active:
            if active & 1:
                row ^= right_rows[index]
            active >>= 1
            index += 1
        output.append(row)
    return tuple(output)


def _linear_rows_6(blocks: tuple[int, int, int, int]) -> tuple[int, ...]:
    a_block, b_block, c_block, d_block = blocks
    rows = []
    for row in range(DIMENSION):
        rows.append(_row_bits(a_block, row) | (_row_bits(b_block, row) << DIMENSION))
    for row in range(DIMENSION):
        rows.append(_row_bits(c_block, row) | (_row_bits(d_block, row) << DIMENSION))
    return tuple(rows)


def _identity_rows(size: int) -> tuple[int, ...]:
    return tuple(1 << index for index in range(size))


def affine_square_is_identity(blocks: tuple[int, int, int, int], offset: int) -> bool:
    rows = _linear_rows_6(blocks)
    return (
        _matrix_product(rows, rows) == _identity_rows(2 * DIMENSION)
        and (_matrix_vector(rows, offset) ^ offset) == 0
    )


def valid_affine_offsets(blocks: tuple[int, int, int, int]) -> tuple[int, ...]:
    """Return offsets satisfying the affine YBE equation for a linear block."""

    l12 = _l12_rows(blocks)
    l23 = _l23_rows(blocks)
    good = []
    for offset in range(1 << (2 * DIMENSION)):
        t12 = offset
        t23 = offset << DIMENSION
        left = _matrix_vector(l12, _matrix_vector(l23, t12)) ^ _matrix_vector(
            l12, t23
        ) ^ t12
        right = _matrix_vector(l23, _matrix_vector(l12, t23)) ^ _matrix_vector(
            l23, t12
        ) ^ t23
        if left == right:
            good.append(offset)
    return tuple(good)


def offset_tuple(offset: int) -> tuple[int, ...]:
    return tuple((offset >> index) & 1 for index in range(2 * DIMENSION))


def offset_string(offset: int) -> str:
    return "".join(str(entry) for entry in offset_tuple(offset))


def generated_congruence_block_count(
    solution: FiniteBraidedSet,
    seed: tuple[object, object],
) -> int:
    """Compute the least YBE congruence generated by one pair."""

    elements = tuple(solution.elements)
    index = {element: position for position, element in enumerate(elements)}
    parent = list(range(len(elements)))
    queue = []

    def find(position: int) -> int:
        while parent[position] != position:
            parent[position] = parent[parent[position]]
            position = parent[position]
        return position

    def union(left: int, right: int) -> None:
        root_left = find(left)
        root_right = find(right)
        if root_left == root_right:
            return
        parent[root_right] = root_left
        queue.append((left, right))

    union(index[seed[0]], index[seed[1]])
    while queue:
        left_index, right_index = queue.pop()
        left = elements[left_index]
        right = elements[right_index]
        for probe in elements:
            for out_left, out_right in (
                (solution.R[(left, probe)], solution.R[(right, probe)]),
                (solution.R[(probe, left)], solution.R[(probe, right)]),
            ):
                union(index[out_left[0]], index[out_right[0]])
                union(index[out_left[1]], index[out_right[1]])

    return len({find(index) for index in range(len(elements))})


def quotient_rigidity_witness(
    solution: FiniteBraidedSet,
) -> tuple[bool, tuple[object, object, int] | None]:
    elements = tuple(solution.elements)
    for left, right in combinations(elements, 2):
        block_count = generated_congruence_block_count(solution, (left, right))
        if block_count != 1:
            return False, (left, right, block_count)
    return True, None


def _pressure_rows(solution: FiniteBraidedSet) -> tuple[dict[str, object], ...]:
    rows = small_rack_prefix_obstruction_rows(
        solution,
        max_rack_size=3,
        max_arity=3,
        max_detector_size=64,
        state_limit=50_000,
    )
    return tuple(
        {
            "detector_prefix_length": row.detector_prefix_length,
            "detector_size": row.detector_size,
            "arity": row.arity,
            "obstruction_found": row.obstruction_found,
            "truncated": row.audit.truncated,
            "joint_image_size": row.audit.joint_image_size,
            "solution_image_size": row.audit.solution_image_size,
            "detector_image_size": row.audit.detector_image_size,
            "kernel_size": row.audit.kernel_size,
            "first_witness_word": row.audit.first_witness_word,
            "first_moved_tuple": None
            if row.audit.first_moved_tuple is None
            else repr(row.audit.first_moved_tuple),
            "first_moved_tuple_image": None
            if row.audit.first_moved_tuple_image is None
            else repr(row.audit.first_moved_tuple_image),
        }
        for row in rows
    )


def build_report() -> dict[str, object]:
    products = _precompute_products()
    right_solutions = _right_multiplication_solutions(products)
    counts: Counter[str] = Counter()
    valid_offset_histogram: Counter[int] = Counter()
    rank_histogram: Counter[tuple[int, int]] = Counter()
    first_quotient_failure = None
    first_candidate = None

    for blocks in _linear_ybe_block_rows(products, right_solutions):
        a_block, b_block, c_block, d_block = blocks
        counts["linear_ybe_block_count"] += 1
        b_rank = _matrix_rank(b_block)
        c_rank = _matrix_rank(c_block)
        rank_histogram[(b_rank, c_rank)] += 1
        offsets = valid_affine_offsets(blocks)
        valid_offset_histogram[len(offsets)] += 1
        counts["affine_ybe_table_count"] += len(offsets)
        if b_rank >= DIMENSION or c_rank >= DIMENSION:
            counts["bidegenerate_failed"] += len(offsets)
            continue

        matrix = _block_matrix(*blocks)
        for offset in offsets:
            if affine_square_is_identity(blocks, offset):
                counts["noninvolutive_failed"] += 1
                continue
            counts["terminal_without_flip_count"] += 1
            solution = affine_solution(matrix, offset_tuple(offset), DIMENSION)
            observer_blocks = len(one_state_invariant_observer_partition(solution))
            if observer_blocks != 1:
                counts["observer_failed"] += 1
                continue
            counts["observer_rigid"] += 1
            subsolution_count = len(proper_subsolution_subsets(solution))
            if subsolution_count:
                counts["subsolution_failed"] += 1
                continue
            counts["subsolution_rigid"] += 1
            quotient_rigid, witness = quotient_rigidity_witness(solution)
            if not quotient_rigid:
                counts["quotient_failed"] += 1
                if first_quotient_failure is None:
                    first_quotient_failure = {
                        "matrix": _matrix_signature(matrix),
                        "offset": offset_string(offset),
                        "witness": repr(witness),
                    }
                continue
            counts["rigid_structural_survivor_count"] += 1
            if first_candidate is None:
                first_candidate = {
                    "blocks": list(blocks),
                    "matrix": _matrix_signature(matrix),
                    "offset": offset_string(offset),
                    "branch_tags": list(branch_tags(solution)),
                    "observer_partition_block_count": observer_blocks,
                    "proper_subsolution_count": subsolution_count,
                    "pair_generated_quotient_rigid": True,
                    "not_flip_across": True,
                    "not_flip_across_reason": (
                        "subsolution-rigid rows cannot have a flip-across "
                        "decomposition, since each side would be a proper "
                        "crossing-closed subsolution"
                    ),
                    "pressure_rows": _pressure_rows(solution),
                }

    pressure_rows = () if first_candidate is None else first_candidate["pressure_rows"]
    first_full_prefix_pressure = next(
        (
            row
            for row in pressure_rows
            if row["detector_prefix_length"] == 5 and row["obstruction_found"]
        ),
        None,
    )
    if first_candidate is not None:
        first_candidate["first_full_size3_prefix_pressure"] = first_full_prefix_pressure
        first_candidate["finite_rigid_pressure_core_candidate"] = (
            first_full_prefix_pressure is not None
        )

    return {
        "title": "Affine F2^3 rigid pressure core audit",
        "dimension": DIMENSION,
        "counts": dict(counts),
        "rank_histogram": {
            f"B_rank={key[0]},C_rank={key[1]}": count
            for key, count in sorted(rank_histogram.items())
        },
        "valid_offset_count_histogram": {
            str(key): count for key, count in sorted(valid_offset_histogram.items())
        },
        "first_quotient_failure": first_quotient_failure,
        "first_rigid_pressure_candidate": first_candidate,
        "conclusion": (
            "The affine F_2^3 family contains finite rigid-pressure-core "
            "candidates in the falsifiable finite-prefix sense: 3360 rows "
            "survive the bidegenerate, noninvolutive, observer-rigid, "
            "subsolution-rigid, and pair-generated quotient-rigid filters. "
            "The first survivor has nontrivial kernel pressure against the "
            "product prefix containing all rack representatives of size at "
            "most 3. This is not a Sawin counterexample; it is the first "
            "serious candidate table whose pressure must be tested cofinally "
            "or explained by a larger finite rack detector."
        ),
    }


def render_markdown(report: dict[str, object]) -> str:
    counts = report["counts"]
    candidate = report["first_rigid_pressure_candidate"]
    lines = [
        "# Affine F2^3 Rigid Pressure Core Audit",
        "",
        "This generated audit applies the rigid-pressure-core filters to the",
        "affine-linear `F_2^3` family using the linear YBE block equations",
        "and affine offset equations.  It is a finite-prefix pressure audit,",
        "not a Sawin counterexample.",
        "",
        "## Census",
        "",
        f"- linear YBE blocks: `{counts['linear_ybe_block_count']}`;",
        f"- affine YBE tables: `{counts['affine_ybe_table_count']}`;",
        f"- failed bidegeneracy: `{counts['bidegenerate_failed']}`;",
        f"- failed noninvolutivity: `{counts['noninvolutive_failed']}`;",
        "- bidegenerate noninvolutive rows before flip testing: "
        f"`{counts['terminal_without_flip_count']}`;",
        f"- failed observer-rigidity: `{counts['observer_failed']}`;",
        f"- observer-rigid rows: `{counts['observer_rigid']}`;",
        f"- failed subsolution-rigidity: `{counts['subsolution_failed']}`;",
        f"- subsolution-rigid rows: `{counts['subsolution_rigid']}`;",
        f"- failed quotient-rigidity: `{counts['quotient_failed']}`;",
        "- rigid structural survivors: "
        f"`{counts['rigid_structural_survivor_count']}`.",
        "",
        "Rank histogram:",
        "",
        "```text",
    ]
    lines.extend(f"{key}: {value}" for key, value in report["rank_histogram"].items())
    lines.extend(
        [
            "```",
            "",
            "Valid-offset histogram:",
            "",
            "```text",
        ]
    )
    lines.extend(
        f"{key} valid offsets: {value} linear blocks"
        for key, value in report["valid_offset_count_histogram"].items()
    )
    lines.extend(["```", ""])
    if candidate is None:
        lines.extend(["## Candidate", "", "No rigid structural survivor was found."])
    else:
        pressure = candidate["first_full_size3_prefix_pressure"]
        lines.extend(
            [
                "## First Rigid Pressure Candidate",
                "",
                "Matrix rows:",
                "",
                "```text",
            ]
        )
        lines.extend(candidate["matrix"])
        lines.extend(
            [
                "```",
                "",
                f"- offset: `{candidate['offset']}`;",
                f"- branch tags: `{candidate['branch_tags']}`;",
                "- pair-generated quotient-rigid: "
                f"`{candidate['pair_generated_quotient_rigid']}`;",
                f"- not flip-across: `{candidate['not_flip_across']}`;",
                "- finite rigid-pressure-core candidate: "
                f"`{candidate['finite_rigid_pressure_core_candidate']}`.",
                "",
                "First pressure row for the full size-`<=3` rack prefix:",
                "",
            ]
        )
        if pressure is None:
            lines.append("- none found in the checked prefix.")
        else:
            lines.extend(
                [
                    f"- detector prefix length: `{pressure['detector_prefix_length']}`;",
                    f"- detector size: `{pressure['detector_size']}`;",
                    f"- arity: `{pressure['arity']}`;",
                    f"- obstruction found: `{pressure['obstruction_found']}`;",
                    f"- truncated: `{pressure['truncated']}`;",
                    f"- witness word: `{pressure['first_witness_word']}`;",
                    f"- moved tuple: `{pressure['first_moved_tuple']}`;",
                    f"- moved image: `{pressure['first_moved_tuple_image']}`.",
                ]
            )
    lines.extend(["", "## Conclusion", "", report["conclusion"]])
    return "\n".join(lines) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    if argv not in (None, ()):
        raise SystemExit("no arguments are supported")
    report = build_report()
    OUT_JSON.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    OUT_MD.write_text(render_markdown(report), encoding="utf-8")
    print(OUT_JSON)
    print(OUT_MD)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(tuple(sys.argv[1:])))
